### ISSUE TITLE
How do I implement caching?

### ISSUE THREAD

**Issue by cschroeter** [ngrx/store#101]
I would like to avoid calling an API twice, if the service has already been called. 

Now I wonder where to put this logic. Do the service handle the "caching" (e.g ReplaySubject) or does  a smart component "subscribe" to the store and just calls the service in case there is no data available.

Thoughts?

**Comment by sentyaev** [comment]
There is very simple solution for that.
Let's say you have UserService which handles fetching data from api. 
In case you need some caching, you can implement wrapper.

```
interface IUserService {
  loadUser(id: string): IUser;
}
class UserService implements IUserService  {
  constructor(_http: Http) { }
  loadUser(id: string): IUser { ... }
}
class CachingUserService implements IUserService  {
  constructor(userService: UserService, cache: SomeCache) { }
  loadUser(id: string): IUser {
    let user = cache.get(id);
    if (!user) {
      return userService.loadUser(id);
    }
    return user;
  }
}
```

And your components will depend on IUserService and DI will do the rest.

**Comment by cschroeter** [comment]
Ah this is a nice idea. Thank you !
