### ISSUE TITLE
How to properly handle smart/dumb components and store interaction

### ISSUE THREAD

**Issue by Merott** [ngrx/store#105]
I'm currently working on a view an in app that shows a number of tiles in two separate tabs, a _Home_ tab and a _Recent_ tab. Each tile is a `TileComponent`. Multiple tiles can be grouped together, and form a `TileGroupComponent`. When you click on a tile, you're taken to a view specific to that item.

The `TileComponent` is the lowest-level component that I have. So, I implement the `TileComponent` as a dumb component. Good.

I then have the `TileGroupComponent`, which I'd also like to implement as a dumb component. I don't feel it actually could have any business logic since all it does is render a few tiles in a group presentation. It makes no logical sense to have any application logic in it.

Now, I'd like to handle clicks on tiles, so that the app will navigate to the specific view for that item. In my `TileGroupComponent` template I handle `click` events on my tiles by emitting a `tileClick` event. 

``` html
<tile *ngFor="let tile of tiles" (click)="tileClick.emit(tile)"></tile>
```

That `tileClick` event is handled by my smart component called `HomeComponent`, where the `TileGroupComponent` is rendered. The smart component dispatches an action to the store. What happens next is irrelevant.

``` html
<home>
  <tile-group 
    *ngFor="let tileGroup of tileGroups"
    (tileClick)="dispatchToStore($event)">
  </tile-group>
</home>
```

But then, I also have the `RecentComponent`, which is similar to `HomeComponent`, but shows recently accessed tiles, as the name suggests. I'd obviously like to not repeat myself from `HomeComponent`, so what am I to do when implementing `RecentComponent`?

---

My original question ended there, and as I wrote that, my computer played the role of a "Rubber Duck", so I have managed to answer myself - sort of - I think - maybe. I'd still like to read someone else's opinion.
- I don't really like to put the responsibility of dispatching to the store on `TileGroupComponent` since I think it makes no logical sense to belong there.
- The other option is to introduce a new container component, that both `HomeComponent` and `RecentComponent` will render as their top-level component. Makes sense to me. Does it to you?
- What are any other/better options?

**Comment by spicywhitefish** [comment]
Suggestion: Move shared action-dispatching code to a separate `Injectable`, solely responsible for dispatching actions to the store. Looking ahead, your dispatchers would handle connecting to APIs with `Http`, subscribing to the response `Observable`, and dispatching "~FOO_DATA_RETRIEVED" actions to the store. This is the pattern I'm using in my application.

**Comment by Merott** [comment]
I think my challenge here is where to put code that handles the `click` events and dispatches the appropriate action (whether directly or indirectly through another service), without causing code duplication.

The best way I can think of is for both `HomeComponent` and `RecentComponent` to contain a common top-level container that would be responsible for dispatching the action.

**Comment by bzums** [comment]
So the redundancy you name is only calling a service which is dispatching an action (if you would outsource the dispatching to a service)? Is there a practical reasoon to avoid such a redundancy?

However, if you have a common top-level component it makes you can delegate responsibility. However, when your application will grow, it may make sense to split up responsibility, I think you should not always delegate everything to the top-level.

**Comment by firecube** [comment]
As @spicywhitefish suggests you should inject a TileService into both HomeComponent and RecentComponent.  This service should create and dispatch the action to the store.

**Comment by robwormald** [comment]
Pretty much agree with all the suggestions here.
