### ISSUE TITLE
provideStore not working since update of angular to rc

### ISSUE THREAD

**Issue by jusefb** [ngrx/store#106]
Doing this in the boot.ts file:

`import {bootstrap} from "angular2/platform/browser";
import {HTTP_PROVIDERS, Http} from "angular2/http";
import {MainApp} from "./main/app";

import "rxjs/BehaviorSubject";
import 'rxjs/add/operator/map';

import {provideStore} from '@ngrx/store';
import {users} from "./users/reducers/user.reducer";
import {UserService} from "./users/services/user.service";

//register the store
bootstrap(MainApp, [
    HTTP_PROVIDERS,
    UserService,
    provideStore({users})
])
.catch(err => console.error(err));`

produces the following error:

"Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object]"

This was working fine before RC.

Cheers

Jusef

**Comment by littleStudent** [comment]
I dont think this is an issue with ngrx/store.
did you clean your node_modules? (old angular should be gone)

you still reference `import {bootstrap} from "angular2/platform/browser";`
But for rc0 it changed to `import {bootstrap} from '@angular/platform-browser-dynamic';`

**Comment by jusefb** [comment]
Yup, that is it. Thank you very much and apologies for waisting your time, still trying to get to the grips with all the new updates.
