### ISSUE TITLE
Angular 2 rc 1 support

### ISSUE THREAD

**Issue by ruiwanguk** [ngrx/store#107]
Hi, 

I am creating an issue to check whether there is any plan to support Angular 2 rc.1. Would the current version work with rc 1?

Regards,
Rui

**Comment by kylecordes** [comment]
The version in package.json has a "^" constraint - I suggest giving it a try. (Rob, and many other Angular team folks, are here at ng-conf, but I suspect when they all return home and recover from the amazing progress over the last week, we'll see lots of tidying up of A2 and related libraries.)

**Comment by HonnKing** [comment]
I'm getting `TypeError: store_1.provideStore is not a function` from my main when I try to use it with Angular 2.0.0 rc1 and rxjs 5.0.0 beta 6. Is that a compatibility issue or am I just using it wrong? I'm using the example shown in the readme.

**Comment by HonnKing** [comment]
My errors where just config issues on my side. I've tried the current version with Angular2 rc.1 and at least the basic cases seem to work.

**Comment by robwormald** [comment]
Closing as it appears you've found a resolution.
