### ISSUE TITLE
provideStore - issue on bootstrap.

### ISSUE THREAD

**Issue by nithinpeter** [ngrx/store#118]
`import { provideStore } from '@ngrx/store';
import { counter } from './ngrx/reducers'

bootstrap(AppComponent, [
      ROUTER_PROVIDERS, 
      provideStore({counter})
    ]
  ).then(success => console.log(`Bootstrap success`))
  .catch(error => console.log(error));`

it causes Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object] on bootstrap.

**Comment by requiemforameme** [comment]
I am getting the same error. I will let you know if I find a resolution.

**Comment by laurelnaiad** [comment]
You might want to put a breakpoint on your bootstrap line, check what you have for provideStore (and/or examine the network tab of your browser devtools). You may have wound up with the wrong object due to an import/module mapping problem.

**Comment by requiemforameme** [comment]
The error only occurred for me in the middle of "migrating" from angular2-beta to the release candidate. I guess some files from the previous @ngrx version were cached by Webstorm.  I would recommend doing what @laurelnaiad said.

**Comment by abotz** [comment]
What does your counter code look like?

**Comment by robwormald** [comment]
Is this still an issue? Did you get any resolution? I'm going to close it for inactivity, please request a re-open if you still have an issue, and provide a reproduction in a plunker.
