### ISSUE TITLE
[Design] How does a RestApi service retrieve JWT token

### ISSUE THREAD

**Issue by BrainCrumbz** [ngrx/store#119]
We're trying to find the _right_ way (as in _designed correctly_) to provide JWT access token to a service class responsible for communicating with REST API backend.

Let's see if this picture (kind of Activity Diagram) helps common understanding:

![login-auth-saga-api_2](https://cloud.githubusercontent.com/assets/3185573/15193791/e1c38048-17bf-11e6-887b-b4b926851ee8.png)

`LoginSaga`, when doing login:
1. asks `RestApiService` for all needed authorization info (id_token, access_token, ...)
2. commands `AuthStorageService` to store info locally (e.g. in LocalStorage, SessionStorage, ...)
3. dispatches actions with those info, so to indirectly update app store and `AppState`, that now holds the token as well

Later, when some visual component needs a remote protected resource, `ProtectedResourceSaga`:
1. asks `RestApiService` for remote resource, specifying that it is a protected resource.

Now the question: **how can `RestApiService` get a hold of current access token?**

ideally, our thought is that all `ProtectedResourceSaga`s around should not be bothered with retrieving token from store and passing it to `RestApiService`. They should just command to perform an _authenticated_ request, as opposed to a simple, un-authenticated one. Although, from a design point of view, this seems the best fit choice, as sagas already know about current state.

Thus, `RestApiService` should be somehow provided/updated with token info by someone. Or it should ask for that directly from the store ... but this last one sounds quite bad. In the first case, `LoginSaga`, acting already as a kind of orchestrator, could pass token info in `RestApiService`.

Other points to keep in mind:
1. There are components that form a kind of _model - domain - state_ layer, while other form a kind of _I/O - Side effects_ layer, 
1. Model layer should _use_ IO layer, and IO layer should not be aware of Model layer
1. Should `RestApiService` keep a state on its own (e.g. the last stored token)? Or should instead receive token on every needed request, and keep no state about that?

I tried looking for some similar reasoning in redux and redux-saga, but could not find any. 

Thoughts?

**Comment by robwormald** [comment]
Don't overthink this:
http://plnkr.co/edit/qhOZjOA8Tfm3IvK1cwHW

**Comment by BrainCrumbz** [comment]
Thanks for suggestion. We're relatively new to redux-style unidirectional flow, and we're looking for the most streamlined/repeatable way to implement all those typical round-trips from component to REST API and back again.

**Comment by robwormald** [comment]
I see you're contrib'ing over on ngrx/effects, so I'm going to close this :)
