### ISSUE TITLE
why need state?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#122]
Hi,
I wondered why did State should be needed? I can save my data on service, and getting by injection.
what are the purpose for using a State over Service Injection?

**Comment by iamdey** [comment]
Could you be more specific ? I mean may be the question is "why this package?"

In that case, look at the first line of the readme:

> RxJS powered state management inspired by Redux for Angular2 apps

so if you don't know redux, you may start here: https://www.npmjs.com/package/redux and here https://egghead.io/series/getting-started-with-redux it is oriented for react but it is not important.

**Comment by robwormald** [comment]
Please take questions like this to the gitter channel - https://gitter.im/ngrx/store
