### ISSUE TITLE
Please add notes into README for SystemJS to improve documentation

### ISSUE THREAD

**Issue by silentHoo** [ngrx/store#123]
It took me some time to find out how to import @ngrx into my SystemJS project. A sub-title would help others too. I found this issue with a sample: https://github.com/ngrx/devtools/issues/10#issuecomment-203916791

**Comment by robwormald** [comment]
Feel like sending a PR?

**Comment by katrotz** [comment]
Also if using SystemJS with JSPM, the packages could be installed from npm registry, which JSPM handles pretty decently:

`jspm install npm:@ngrx/store`

Tested with latest jspm@0.17.0

**Comment by MikeRyanDev** [comment]
As @robwormald has mentioned, we'll happily accept a PR. 

cc @btroncone
