### ISSUE TITLE
HMR support without middleware in 2.0

### ISSUE THREAD

**Issue by tjoskar** [ngrx/store#125]
Hi,

I'm using webpack with [HMR](https://webpack.github.io/docs/hot-module-replacement.html) and have implemented a really naive solution to keep the application state between module replacements:

``` javascript
const appStateName = 'appStateName';
const reducers = { navigation, comments /* etc. */ };
const prevState = () => {
    return window[appStateName];
};
const reducerPostMiddleware = state => {
    return state.do(val => {
        window[appStateName] = val;
    });
};

if (development) {
    bootstrap(MyComponent, [
        provideStore(reducers, prevState()),
        usePostMiddleware(reducerPostMiddleware)
    ]);
}
```

But since the middleware APIs have been removed within `ngrx/store@2.0.0`, I have to come up with another solution. 
Is there any plans for supporting HMR in the core lib?

**Comment by robwormald** [comment]
It shouldn't really require anything in core, as far as i'm aware:
- initialState can be passed into the bootstrap method
- you just need a listener to subscribe to the store and cache the latest state

No? I'm open to it in general but I dislike the idea of having to make specific changes to store to support ____ use case - this is a lot of why we dropped the complications in 2.0

**Comment by tjoskar** [comment]
You are absolutely right! I don't know what I was thinking. 
Thanks!
