### ISSUE TITLE
Does ngrx/store handle async actions?

### ISSUE THREAD

**Issue by nareshbhatia** [ngrx/store#126]
I am just starting to look at ngrx/store. Looking through the docs, I can't figure out if it will handle async actions (similar to http://redux.js.org/docs/advanced/AsyncActions.html). What is the recommended way to handle actions that fire http calls? Should these be handled outside of the store?

**Comment by fxck** [comment]
@ngrx/effects

**Comment by nareshbhatia** [comment]
Awesome! Will start looking at that.
