### ISSUE TITLE
When I use `select`, the suscription don't works

### ISSUE THREAD

**Issue by Grmiade** [ngrx/store#127]
My component:

``` ts
export class LoginComponent implements OnInit {

  private loginForm: ControlGroup;
  private auth: Observable<any>;

  constructor(
    private store: Store<AppState>,
    private authService: AuthService,
    private formBuilder: FormBuilder
  ) {
    this.auth = store.select('auth');
  }

  ngOnInit() {
    this.auth.subscribe(state => console.log(state));
    this.loginForm = this.formBuilder.group({
      'email': ['', Validators.required],
      'password': ['', Validators.required],
    });
  }

  login() {
    this.authService.login(
      this.loginForm.controls['email'].value,
      this.loginForm.controls['password'].value
    );
  }
}
```

``` ts
@Injectable()
export class AuthService {
  login(email, password) {
    // this.firebase.auth.login({email, password});
    this.store.dispatch({
      type: LOGIN_REQUEST,
    });
  }
}
```

If I use the `select` method, I don't see the next state in my console, the subscription via select don't work :/
But if I use `this.store.subscribe(state => console.log(state));` instead of `this.auth.subscribe(state => console.log(state));` it works anew, when an action is dispatched, my new state is logged in my console. An idea ? I use the new 2.0.0 version.

**Comment by abdulhaq-e** [comment]
Try to make a plnkr.

There are many possibilities, for a start, are you sure you have a reducer named `auth`?

**Comment by robwormald** [comment]
This is typically because you're not returning a new reference in the reducer. We'd need to see the reducer code to answer this question.

**Comment by Grmiade** [comment]
My reducer:

``` ts
import { ActionReducer, Action } from '@ngrx/store';

import { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILED } from './auth.constants';

export interface AuthState {
  logging: boolean;
  user?: any;
  error?: { code: string, message: string };
}

const defaultState = {
  logging: false,
};

export const authReducer: ActionReducer<AuthState> = (state: AuthState = defaultState,
                                                      action: Action) => {
  switch (action.type) {
    case LOGIN_REQUEST:
      return Object.assign(state, { logging: true, error: null });

    case LOGIN_SUCCESS:
      return Object.assign(state, { logging: false, user: action.payload });

    case LOGIN_FAILED:
      return Object.assign(state, { logging: false, error: action.payload });

    default:
      return state;
  }

};
```

The first log works but not the following.

<img width="1421" alt="capture d ecran 2016-06-04 a 00 22 01" src="https://cloud.githubusercontent.com/assets/11244106/15794369/8865f9f8-29ea-11e6-9cfb-26857bf0d2b7.png">

How I can use the 2.0.0 version of `@ngrx/store` in a Plunker ?

**Comment by friksa** [comment]
All your Object.assign lines need an extra {}, as follows:
return Object.assign({}, state, { logging: true, error: null });

**Comment by Grmiade** [comment]
OH! -_- Sorry for that.
It works! Thanks so much !

**Comment by friksa** [comment]
You're welcome!
