### ISSUE TITLE
Reducer not called

### ISSUE THREAD

**Issue by SebastianStehle** [ngrx/store#129]
Hi,

I tried two approaches to define the reducer:

// #1  From the start page
export const editorReducer: ActionReducer<EditorState> = (state: EditorState, action: Action) => {

// #2  Simple function
export const editorReducer: (state: EditorState, action: any) => EditorState = (state: EditorState, action: any) => {

Both reducers are called with an init action, but reducer #2 ist not called for all other actions. Why?

**Comment by robwormald** [comment]
It's near impossible to answer this question without some more information. Can you reproduce it in a plunker please? The latter doesn't look valid at all to me.

**Comment by pietro909** [comment]
Actually the second example is not valid JS.

**Comment by nosachamos** [comment]
Either

`export const editorReducer: ActionReducer = (state: EditorState, action: Action) => {`

Or 

`export const editorReducer:  (state: EditorState, action: Action) = (state: EditorState, action: Action) => {`

Or 

`export const editorReducer = (state: EditorState, action: Action) => {`
...Although really you should be writing:

`export const editor:  ActionReducer<EditorState> = (state: EditorState, action: Action) => {`

... I think this could be closed.
