### ISSUE TITLE
passing an observable/async prop to a React subcomponent

### ISSUE THREAD

**Issue by cmelion** [ngrx/store#131]
Simple strings (message) are easy to inject as props, does anyone have a recommendation supporting observables(items)?

Working example of react sub-component:  https://cmelion.github.io/generator-ng2-webpack/about

```
/// <reference path="../../../../../../typings/tsd.d.ts" />

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import {Observable} from 'rxjs/Observable';
import {Item} from '../../index.async';

// No type definition available quick and dirty require instead
var NotificationSystem = require('react-notification-system');

class NGReactProps {
    public message: string;
    public items: Observable<Array<Item>>;
}

class NGReactComponent extends React.Component<NGReactProps, any> {
    private _notificationSystem = null;

    constructor(props:NGReactProps) {
        super(props);
    }

    componentDidMount() {
        //noinspection TypeScriptUnresolvedVariable
        this._notificationSystem = this.refs.notificationSystem;
    }

    _addNotification() {
        this._notificationSystem.addNotification({
            message: this.props.message,
            level: 'success'
        });
    }

    render() {
        return (
            <div>
                <p>Say Hello From React!</p>
                <p>
                    <button onClick={this._addNotification.bind(this)}>Hello</button>
                </p>
                <NotificationSystem ref="notificationSystem" />
            </div>
        )
    }
}

export class NGReact{
    static initialize(message, items){
        ReactDOM.render(<NGReactComponent message={message} items={items}/>, document.getElementById('ng-react-component'));
    }

}
```

**Comment by robwormald** [comment]
This is such a bonkers crazy idea I'm not sure whether to help you out or ban you from opening issues here ever again ;-)

In pure react-land I'd just use the setState() method and call that with an Observable. In pure angular-land i'd use ngOnChanges (probably?) if I was doing a weird wrapper interop thing.

I can't even. cc @blesh because he probably does this kind of weird stuff more than me.

**Comment by cmelion** [comment]
@robwormald Hah!  Yes, the insanity of it all is not lost on me.  I appreciate you not banning me outright ;-)

**Comment by benlesh** [comment]
Injecting an observable via props is no different than injecting a function via props (think click handlers, etc). That's totally legit. The one thing in there that is an anti-pattern in react is using refs to get a child component and call a method on it, but that doesn't seem necessary. Instead, you'd push the value into it with props and let react decide what it should update.

**Comment by benlesh** [comment]
BTW it's cool you've found a pattern for using a react component within ng2 if you need to.

**Comment by cmelion** [comment]
@blesh thanks for the feedback.  Credit for react within ng2 goes to @thelgevold:  http://www.syntaxsuccess.com/viewarticle/integrating-react-with-angular-2.0
