### ISSUE TITLE
Created example application with @ngrx/store

### ISSUE THREAD

**Issue by pavanpodila** [ngrx/store#133]
Hi,
         I have recently built an example application using @ngrx/store: https://github.com/sapientglobalmarkets/staffer/tree/master/staffer-ng2-ngrxstore

This uses some idiomatic redux techniques and ideas that I have learnt from this repo. I would be happy if you can do a quick review and also include this in the examples section. I can submit a PR for that.

Great job with the project so far!

Thanks!
Pavan

**Comment by btroncone** [comment]
@pavanpodila Could you submit a PR to include this with repos in the resources section of upcoming docs? Great work! https://github.com/ngrx/ngrx.github.io/blob/master/store/help/resources.md

**Comment by pavanpodila** [comment]
Thanks! here is the [PR](https://github.com/ngrx/ngrx.github.io/pull/1)

**Comment by btroncone** [comment]
I have closed the PR and will instead include this in my personal examples repo, thanks!

**Comment by pavanpodila** [comment]
Ok. Thanks!
