### ISSUE TITLE
Subscribe method returns `undefined`

### ISSUE THREAD

**Issue by Grmiade** [ngrx/store#134]
I would have liked unsubscribe my subscription to the store but it returns `undefined`.
If I execute this line `this.todos$ = store.select('todos').subscribe(todos => console.log(todos));`, `this.todos$` will be undefined. So I can't call `this.todos$.unsubscribe();` :/

You could find an example here:
http://plnkr.co/edit/orw0sCdeYeRZPLv8qmmE?p=preview

It's a bug or a mistake on my part?
I follow this https://gist.github.com/btroncone/a6e4347326749f938510#container-component

**Comment by r-park** [comment]
Try this:

``` javascript
this.todos$ = store.select('todos');
let unsubscribe = this.todos$.subscribe(todos => console.log(todos));
unsubscribe();
```

The `subscribe()` call returns the unsubscribe function.

**Comment by Grmiade** [comment]
It works :/ Thanks

**Comment by shprink** [comment]
Actually it is more like this:

```
store.select('todos')
.subscribe(todos => console.log(todos))
.unsubscribe();
```

`subscribe` does not return a function but an object that has the `unsubscribe` function

**Comment by katrotz** [comment]
That still happens for me (@ngrx/store@2.2.1, rxjs@5.0.0-beta.12):

```
const subscriber = this.store.select('applications').let(selectors.getItem(applicationId)).subscribe(application => {
      // subscriber is undefined

      setTimeout(() => {
            // subscriber is defined
      });
});
```

**Comment by KwintenP** [comment]
@katrotz This is actually logical behaviour. You're not supposed to handle the subscription object (which u are calling subscriber) in your subscribe method. The subscription/subscriber object is used to unsubscribe from your observable. You won't need to do this from within you subscribe method. You'll do this on a specific event such as a component destroy or something similar.

I've created a JSBin that demonstrates that this is normal in plain RXJS http://jsbin.com/tezorur/18/edit?js,console

If you need to unsubscribe your observable on a specific value being passed you can use the 'takeWhile' operator (https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/takewhile.md).

**Comment by katrotz** [comment]
@KwintenP Thank you for the explanation - this behaviour makes perfect sense.
