### ISSUE TITLE
Clarification on whether Redux is a dependency or not...

### ISSUE THREAD

**Issue by NathanWalker** [ngrx/store#14]
There's a lot of excitement around Redux and I've been trying to refactor a large application to use it with Angular2. There's also a lot of information out there right now (some of it rather confusing) on the subject. 

I really like the simplicity of this and am thinking about starting with this as a way forward to implement Redux in the app.

On first glance, I thought it might be a helper for angular2 on top of Redux.
Just a suggestion: it may help to state in the README that this let's you architect your application using the Redux concepts and is independent of https://github.com/rackt/redux ?

Also a comparison between the 2 like what is missing here in comparison? (maybe nothing).
Are the goals here to be an angular2 way of implementing Redux in an application and as such, provide all the concepts the other provides so as to mirror it in a sense?

**Comment by gsans** [comment]
Good points. I think this is a superior replacement. 

For an Angular 2 example using Redux I'm currently working on a post (not published yet) using this plunker https://plnkr.co/edit/9vfKMTOCWcCBEx7P8VL2?p=preview inspired by a recent video course by Dan Abramov (using React)

**Comment by NathanWalker** [comment]
@gsans can't wait to read it! 

One thing I've seen going around is the usage of `payload` which seems to really make a few things cleaner:

```
addTodo(text){  
  return {
    type: ADD_TODO,
    payload: {
      id: this.nextToDoId++,
      text: text,
      completed: false
    }
  };
};
```

Then your reducer can be more concise:

```
case TodoActions.ADD_TODO: 
    return {
      todos: state.todos.concat(action.payload),
      currentFilter: state.currentFilter
    };
```

The prop name could be anything, like for myself, I'd probably use `data`, but I'd like it if things like that became apparent standards to stick with...

btw, please post your article here when you publish it :+1:

**Comment by gsans** [comment]
Sure. I have used 'data' with Flux.

I think this implementation detail is up to the developer with the only
requirement on the action.type. Also it doesn't work that well for some
cases like TOGGLE_TODO or REMOVE_TODO with just an id in the payload or
cases with no payload at all. So I can't tell there's a sound general
advice available here.

On the previous plunker I am following Redux author examples on his latest
course. I guess is fine to use either.

**Comment by NathanWalker** [comment]
Good point on the actions that are just passing id's etc.
Makes sense leaving up to dev.

**Comment by robwormald** [comment]
I did change the README to say "redux-inspired" but happy to accept PR's to clarify further.

RE: payload or not - this is a pattern implemented in https://github.com/acdlite/flux-standard-action - i'm ambivalent on it, but it is implemented in the current version: https://github.com/ngrx/store/blob/master/src/store.ts#L11

The trouble comes with making the Action as an interface - without _some_ key to stick arbitrary data under its harder to type accurately, hence the usage of payload.

**Comment by NathanWalker** [comment]
I think your commit 87f880d575eb25aced7490a4ec64c2868ec8bedc is probably enough. 
At least this closed issue will be around if others have questions :)
