### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by pglaser-engineer** [ngrx/store#143]
Hi, 

I am trying to consume ngrx/store from within an existing angular2 application. To do a sanity check on my build, I copied the contents of the app directory of the todos sample app into my app and tried to compile. My build process is to run npm install against a package.json file (see below). I am not using Angular-CLI -- I hope that that's not a requirement. I also copied the contents of the sample app's typings.json to my own typings.json. 

I got these errors: 

`Error:(4, 22) TS2415: Class 'SyncSubject<T>' incorrectly extends base class 'Subject<T>'.
 Types of property '_subscribe' are incompatible.
 Type '(subscriber: Subscriber<T>) => AnonymousSubscription | Function | void' is not assignable to type '(subscriber: Subscriber<T>) => Subscription'.
 Type 'AnonymousSubscription | Function | void' is not assignable to type 'Subscription'.
 Type 'AnonymousSubscription' is not assignable to type 'Subscription'.
 Property 'isUnsubscribed' is missing in type 'AnonymousSubscription'.

Error:(56, 5) TS2339: Property 'combineLatest' does not exist on type 'typeof Observable'.`

In a separate project, I had tried integrating some of the code from the shopping cart sample app, and instead got this error: 

`Error:(12, 5) TS2425: Class 'BehaviorSubject<T>' defines instance member property 'select', but extended class 'Store<T>' defines it as instance member function.`

This is my package.json: 
`{
  "name": "web",
  "version": "1.0.0-SNAPSHOT",
  "dependencies": {
    "@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",
    "@ngrx/store": "^2.0.0",
    "@ngrx/core": "^1.0.0",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.8",
    "systemjs": "^0.19.8",
    "zone.js": "^0.6.12"

  },
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-ts": "~5.3.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-jasmine": "~0.5.2",
    "grunt-contrib-yuidoc": "~0.5.0",
    "grunt-template-jasmine-istanbul": "~0.2.5",
    "grunt-template-jasmine-requirejs": "~0.1.7",
    "grunt-contrib-uglify": "~0.2.5",
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
    "typescript": "^1.7.5",
    "typings":"^0.6.8",
    "bootstrap": "^3.3.6"
  },
  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  }
}
`

Please advise. 
Thanks.

**Comment by r-park** [comment]
Try downgrading to `"rxjs": "5.0.0-beta.6"` — ngrx/store has the following peer dependencies:

```
"peerDependencies": {
    "@ngrx/core": "^1.0.0",
    "rxjs": "5.0.0-beta.6",
    "@angular/core": "^2.0.0-rc.1"
}
```

**Comment by damsorian** [comment]
I have the same problem .... and I have `rxjs": "5.0.0-beta.6` ...

**Comment by damsorian** [comment]
I have this error:
`Error:(4, 22) TS2415: Class 'SyncSubject<T>' incorrectly extends base class 'Subject<T>'.
 Types of property '_subscribe' are incompatible.
 Type '(subscriber: Subscriber<T>) => AnonymousSubscription | Function | void' is not assignable to type '(subscriber: Subscriber<T>) => Subscription'.
 Type 'AnonymousSubscription | Function | void' is not assignable to type 'Subscription'.
 Type 'AnonymousSubscription' is not assignable to type 'Subscription'.
 Property 'isUnsubscribed' is missing in type 'AnonymousSubscription'.`

**Comment by patrickkeller** [comment]
Same issue here. It is not related to rxjs or ts version. I tried downgrading to other version and the problem persists

**Comment by MikeRyanDev** [comment]
If you are encountering this error, this probably means you have upgraded to a beta of rxjs greater than beta 6. At the moment, ngrx and Angular 2 have a hard dependency on rxjs@5.0.0-beta.6
