### ISSUE TITLE
Using with Facebook SDK

### ISSUE THREAD

**Issue by zeeshanjan82** [ngrx/store#146]
I have started using ngrx/store and am following the angular2-advanced-seed project. However I have a question. I am integrating facebook login with my app and had initially put all the calls to the facebook sdk inside the component functions including OnInit function of the component. Now as I have implemented ngrx/store and have created a separate LoginService which has a function named facebook() where I am calling the following code:

``` js
  facebook(login: Login): void {
    this.track(LOGIN_ACTIONS.FACEBOOK, { label: 'Login with facebook' });
    this.store.dispatch({ type: LOGIN_ACTIONS.FACEBOOK, payload: login });
  }
```

this will call the switch case, but I fail to understand where should I put the following code in the LoginService:

``` js
      this.fb.login().then(
        (response: FacebookLoginResponse) => console.log(response),
        (error: any) => console.error(error)
      );
```

The LoginReducer has switch case conditions and I don't think I have to place this code inside the switch case condition as that is outside the LoginService.

**Comment by zeeshanjan82** [comment]
I have slightly changed the approach, now I am using facebook SDK related code inside my component, however after I validate user from facebook and get back the token, I pass this token along with other details like UserId e.t.c to the reducer through facebook event and then I am able to get the payload inside the switch case of the reducer. However I have a question, after getting the payload inside the reducer's switch case shld I be calling any REST APIs get POST, GET inside the switch case of the reducer or is there any other way of doing this. I mean is the switch case of the reducer only to alter states or can we call Backend APIs  inside it as well?

**Comment by littleStudent** [comment]
Your reducers should be side-effect free. So they should not make any REST calls.
There are 2 good ways to accomplish what you want.

### Services Approach

In your service where you get login callback, you can simply use your custom facebook service to make an API call. The result of this API call can then be dispatched to ngrx/store, which then can be picked up by your components.

### ngrx/effects Approach

Take a look at [ngrx/effects](https://github.com/ngrx/effects)
It is built to handle side effects. In your case this would mean that when you dispatch your `LOGIN_ACTIONS.FACEBOOK`, you dispatch a second action `FACEBOOK_ACTIONS.<whatever>`. The login is handled by the reducer as before and the second action gets picked up by an effect.

Take a look at https://github.com/ngrx/example-app/. A lot of basic cases are already covered in this example.

**Comment by zeeshanjan82** [comment]
thanks @littleStudent will go over the example app again as well as look at ngrx/effects

**Comment by littleStudent** [comment]
No problem. The [gitter channel](https://gitter.im/ngrx/store) is also a good place for such questions.
Lots of helpful people in there!

**Comment by zeeshanjan82** [comment]
Thanks @littleStudent I have one more question and would highly appreciate if you can answer my question: As I understand ngrx/store lets us make the application totally even driven based similar to Redux in React world. Now my question is if my popup which authenticates users against facebook returns valid data and I need to redirect user to another screen or route which I have already defined on app.component. Now where shld I put the logic for redirecting user to another route? shld it reside inside the component or inside the Reducer. It cannot reside inside the component as then I need to make the service call promise based but then what is the use of the Reducer. I understand it is used to detect state change and debug it but then I can debug the service function as well. My confusion is that after a call goes to the reducer it then shld be calling the other route in my app?
