### ISSUE TITLE
Pattern to take the last value of an observable in store

### ISSUE THREAD

**Issue by bzums** [ngrx/store#147]
Hi all,

I have a question regarding the behaviour of observables proivded by the ngrx store (or maybe even regarding the behavior of observables in general...). Given the following simplified service class where I abstract the communication with the ngrx store for the rest of the application:

``` typescript
@Injectable()
export class ContentService {

  public content: Observable<any>;
  //...

  constructor(private store: Store<any>, private http: Http) {
    this.content = store.select(state => state.contentReducer.content);
    //...
  }

  updateContent() {
    this.content.take(1).subscribe(content => {
      // do http call or so which will dispatch an action on success etc.
    });
  }

  //...
}
```

I am wondering whether `this.content.take(1).subscribe(content => {...` is a good idea and/or whether I do anything conceptually wrong. The use case is that `content` is manipulated via various actions and at some point i want to fire an http request with the "latest" value of `content`. Since the ngrx store gives us `Observables` and not something like `BehaviorSubject` there is no other way to get the "latest" value, or is it? 

Furthermore, can I rely on the code inside the subscribe callback to always run or is there a setup where that is not the case? In other words: is the callback function in `subscribe` guaranteed to run synchonously?

**Comment by littleStudent** [comment]
in store version 1.x there was a `getValue()` which got removed in 2.0

There is a special migration section that explains exactly your usecase
https://github.com/ngrx/store#getstate-getvalue-and-value

**Comment by bzums** [comment]
Ok I see thanks. Is it considered a bad practice to use this API or is it maybe a hint for a conceptual flaw since it seems a little bit strange to me to access the store in such a "direct" way?!

**Comment by MikeRyanDev** [comment]
`this.store.select(...).take(1)` is good and acceptable, but rather than triggering the http call in the subscribe callback it would be better to merge map into the request and then subscribe:

``` ts
this.store.select(...)
  .take(1)
  .mergeMap(someValue => this.http.get(...))
  .subscribe(...)
```

**Comment by dpxxdp** [comment]
@littleStudent 

Is there a place where this is explained?  That link is now broken and this describes my use case exactly.

Thanks!

**Comment by tobiasmuecksch** [comment]
@littleStudent 

Dpxxd is right. The link got removed.

**Comment by alaycock** [comment]
@dpxxdp and @tobiasmuecksch 
Here's the link, for future reference.
https://github.com/ngrx/store/blob/6a588ad755cc6511368a084b1bac94b260d24ed1/README.md#getstate-getvalue-and-value

Maybe I'm doing something wrong or architecting my components poorly, but this is the only solution I can find.

**Comment by littleStudent** [comment]
thx @dpxxdp for the link update.

In my current projects I use this approach not very often. It happens rarely that I need access to a single state of the store. Nearly all the time I want the updates to this part of the store anyways. 
For a usecase like @bzums describes I would recommend using [effects](https://github.com/ngrx/effects).
