### ISSUE TITLE
Cannot find source file

### ISSUE THREAD

**Issue by apreg** [ngrx/store#149]
Hi,
I get these warnings in console:

client:40 ./~/@ngrx/core/compose.js
Cannot find source file '../../lib/compose.ts': Error: Cannot resolve 'file' or 'directory' ../../lib/compose.ts in ....\node_modules\@ngrx\core
client:40 ./~/@ngrx/core/SyncSubject.js
Cannot find source file '../../lib/SyncSubject.ts': Error: Cannot resolve 'file' or 'directory' ../../lib/SyncSubject.ts in ....\node_modules\@ngrx\core
client:40 ./~/@ngrx/core/operator/select.js
Cannot find source file '../../../lib/operator/select.ts': Error: Cannot resolve 'file' or 'directory' ../../../lib/operator/select.ts in ....\node_modules\@ngrx\core\operator

I'm using webpack config of [AngularClass' webpack-starter](https://github.com/AngularClass/angular2-webpack-starter)

**Comment by damsorian** [comment]
I have a similar issue:

`Error:(4, 22) TS2415: Class 'SyncSubject<T>' incorrectly extends base class 'Subject<T>'.
 Types of property '_subscribe' are incompatible.
 Type '(subscriber: Subscriber<T>) => AnonymousSubscription | Function | void' is not assignable to type '(subscriber: Subscriber<T>) => Subscription'.
 Type 'AnonymousSubscription | Function | void' is not assignable to type 'Subscription'.
 Type 'AnonymousSubscription' is not assignable to type 'Subscription'.
 Property 'isUnsubscribed' is missing in type 'AnonymousSubscription'.`

**Comment by tjoskar** [comment]
@apreg, I had the same problem until I exclude the path `node_modules/@ngrx` from the `source-map-loader`. eg.

``` javascript
// webpack.config.js
...
    preLoaders: [{
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
            path.resolve(__dirname, 'node_modules/@ngrx'),
            path.resolve(__dirname, 'node_modules/rxjs'),
            path.resolve(__dirname, 'node_modules/@angular')
        ]
    }],
...
```

**Comment by tjoskar** [comment]
I now saw that webpack-starter has made a fix for it as well: https://github.com/AngularClass/angular2-webpack-starter/blob/a24dd05ea513025972c7dc2834453814ff2359e3/config/webpack.common.js#L124

**Comment by apreg** [comment]
Thx @tjoskar that solved it. Actually it is stated [here](https://github.com/ngrx/router/blob/master/docs/overview/webpack.md)
