### ISSUE TITLE
What is the best way for handle store / reducer?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#150]
Hi @robwormald and contributors :)

What is your recommendation for handle the state/store in the reducer (for create a new state)?
Is it the immutablejs the right way? Or just using object assign function? Or another llb?

**Comment by dballance** [comment]
Don't complicate it. 

Your slice of state is an array? 
Use array methods which return a new array. Concat, map, etc. 

What if the slice is an object? 
Object.assign! 

You certainly can use immutable.js if you want, and if it's a large team it may be beneficial. But defer complexity until its needed! :)
