### ISSUE TITLE
[Advice Needed] Should Components trigger actions or services?

### ISSUE THREAD

**Issue by gabzim** [ngrx/store#151]
In my code, should I have a `@Component` class talk to the store directly? Or should it call a service to do that? (In a larger app)

First scenario:

``` javascript
@Component(
 //...
)
class MyClass {
  constructor(private store: Store) {}

  createTodo() {
    this.store.dispatch(...action...);
  }
}
```

Second Scenario: 

``` javascript
@Component(
 //...
)
class MyClass {
  constructor(private todoService: TodoService) {}

  createTodo() {
    this.todoService.create(this.todo);
  }
}


@Injectable
class TodoService {
  //...
    create(todo) {
      this.store.dispatch(...action with todo...)
    }
  //...
}
```

**Comment by gabzim** [comment]
Just trying to figure out the best way to arrange the code, the advantage of the components talking to the store directly is that it's more obvious where actions that change the state are triggered. Then the reducer can call the service. The avantage of having the service do it is that it feels like all that side of the app is more encapsulated and transparent to components plus services can store fancier business logic, but is this worth it?

**Comment by littleStudent** [comment]
I think both ways are totally fine. I personally prefer to keep the actions at component level, if i don't have any special reason not to do it.
Did you see how the official example app implements this? [example app](https://github.com/ngrx/example-app/blob/master/src/actions/book.ts)
They use a service class that handles how the actions you dispatch should look like exactly, so you do not need to compose them in your components. But the dispatching of the action does happen in the component itself.

**Comment by philipooo** [comment]
In my case I put the dispatching into a service to hide business logic from the component.

**Comment by alanjhonnes** [comment]
I try to wrap all the store interaction and action dispatching in services. That way you can reuse it across multiple components, test it more easily and don't have to deal with selecting the state from the store everytime.

**Comment by viniciusoyama** [comment]
I think it's fine to dispatch from a component as @littleStudent said.

But I also think that is important to abstract the action creation in another class (the action creator/action factory...). In the example:

https://github.com/ngrx/example-app/blob/master/src/actions/book.ts

Each method is creating a new action object (with 'type' and 'payload' attributes).
