### ISSUE TITLE
ngrx questions

### ISSUE THREAD

**Issue by noammazuz** [ngrx/store#153]
Dear Devs,
We wish to further implement NGRX2 on out platform (which serves 300+ sites, fully skinned and customizable) we have a few questions regarding the following topics
1.  Page: your documentation describes “Smart, or Container components should be your root level, routable components.“. suppose we have inside the route we have a component that should be used in a few routes/pages. Meaning we need to implement input and output routes in each page. 
   Is it not wiser to build a single entity the can implement these common routes. For example, we have a chat dumb component which has many inputs and outputs handled by the container and we wish to use it in may pages/routes in our application, what’s best way to tackle it.
2.  Folder structure within the application. 
   Currently we have arranged our folder to represent the modules structure. For example, the chat module that contains reducers, actions, each in its own folder per specific folder. In your examples you have broken down the folders to each class type (reducers folder/ actions folder…) for the entire application. What’s the best practice to combine those approaches.
3.  Effects: when should we use the effects, for example A-sync  flows. Could someone summarize it as a moto sentence: “we should use effects in the following  scenario… ”
4.  What is the main advantages in using nrgx/router with guards Vs using angular Router ?

**Comment by MikeRyanDev** [comment]
1. A component being smart or dumb is merely an implementation detail of that component. A component consuming a smart or dumb component should not have to know this implementation detail. In other words, yes your smart components can be comprised of multiple dumb components and vice versa.
2. Organizing large applications with the ngrx platform is still a work in progress. I would try to find big app examples for React/Redux to learn from.
3. "You should use effects to wrap all side effects in your application"
4. ngrx/router's advantages have been re-implemented in the new @angular/router. I'd recommend building new apps on top of that router instead.
