### ISSUE TITLE
Lazy-loaded state

### ISSUE THREAD

**Issue by jimitndiaye** [ngrx/store#154]
How would I go about adding reducers/state after application start-up for lazy-loaded routes?
Say I've got a root reducer resulting in Store<AppState> and I later lazy-load the Todos route which manages its own state. Is my best option to have a separate store for Todos or is it possible to modify the root reducer somehow to include the Todos state?

**Comment by robwormald** [comment]
Store has a .replaceReducer() method that allows you to replace the root reducer, so you could (re) combine your existing reducers with the new one and replace the root.

**Comment by philipooo** [comment]
In one of my projects I have created a store service which takes care of adding new reducers to an existing set of reducers. Each other service can now add its reducer by itself.

Let me know if it helps, or if I can make something better:
https://gist.github.com/philipooo/d4acbcf314b69df0695eb05f55c03876

**Comment by jimitndiaye** [comment]
Thanks to you both. I'll look into replaceReducer.

Does a similar method exist for effects?

**Comment by frederikschubert** [comment]
I will post a guide on dynamic effects and reducers soon on the ngrx.github.io repo.

**Comment by MikeRyanDev** [comment]
@jimitndiaye See [here](https://github.com/ngrx/effects#starting-multiple-effects) for an example of dynamically starting effects

**Comment by Dunos** [comment]
@MikeRyan52 I think your link to the example is not working anymore. Maybe you refer to [this](https://github.com/ngrx/ngrx.github.io/tree/master/effects#starting-multiple-effects)?
