### ISSUE TITLE
Undefined State getting logged in Console

### ISSUE THREAD

**Issue by zeeshanjan82** [ngrx/store#155]
I am not able to know how is the undefined state getting logged inside the chrome console. I have tried to debug but the action despatch is only getting called once but still I can see the undefined state getting logged. Is there any way I could debug this issue and come to know how can I stop this undefined state.

I am despatching the action like this:

``` js
    this.store.dispatch(this.loginActions.init());
```

I have the effect defined as this:

``` js
  @Effect() init$ = this.updates$
    .whenAction(LoginActions.INIT)
    .do(() =>{
      this.loginService.init();
    });

```

I have the reducer defined as this:

``` js
export default function(state = initialState, action: Action): LoginState {
    switch (action.type) {
      case LoginActions.CUSTOM_LOGIN_SUCCESS: {
        return {user: action.payload};
      }
      case LoginActions.FACEBOOK_LOGIN_SUCCESS: {
        return {user: action.payload};
      }
      case LoginActions.GOOGLE_LOGIN_SUCCESS: {
        return {user: action.payload};
      }
      case LoginActions.LOGOUT: {
        return initialState;
      }
      default: {
        return state;
      }
  }

```

![error](https://cloud.githubusercontent.com/assets/8342604/16241585/ebee9d7a-380b-11e6-9427-19a5a836a5a8.png)

**Comment by littleStudent** [comment]
If you dont return an action from your effect, you should "finish" it with `.filter(() => false);` Otherwise it dispatches the undefined to the store

``` javascript
@Effect() init$ = this.updates$
    .whenAction(LoginActions.INIT)
    .do(() =>{
      this.loginService.init();
    })
    .filter(() => false);
```
