### ISSUE TITLE
Problems: 1) angular CLI spec file, 2) constructor store syntax

### ISSUE THREAD

**Issue by davidtlee** [ngrx/store#156]
I have two questions. First, I'm getting this error on trying to set up ngrx/store:

```
src/app/project/task-list/task-list.component.spec.ts (17, 21): Supplied parameters do not match any signature of call target.
```

When I open up the spec file, I see that the line says:

```
let component = new TaskListComponent();
```

So it seems to be complaining because my constructor has the `store: Store<AppState>` object, but the spec doesn't have that parameter passed in. How would I fix the spec test? Is there any way for me to keep it or do I just have to delete the spec file to fix this bug?

Second question is: do I have to have type checking on Store? In all the ngrx/store examples I see, the constructor is just declared as `store: Store`, but the compiler is forcing me to specify the type of store `store: Store<AppState>`. (I had a bunch of problems related to type issues, but I'll start with this simple one cause I feel there might be some really basic things I'm just not understanding...).

**Comment by MikeRyanDev** [comment]
Generally, you don't _ever_ want to use the `new` operator when testing components. I recommend checking out [Julie Ralph's ng2-test-seed](https://github.com/juliemr/ng2-test-seed) for high quality, up-to-date examples of testing components.

If you are seeing official examples of `store: Store` in constructors, can you point them out or send a PR to fix them? If you are using TypeScript, the `Store<T>` class is indeed generic and requires a type parameter. If you don't want to use an explicit type you can just use `Store<any>`

**Comment by davidtlee** [comment]
Thanks @MikeRyan52!
- The `let component = new TaskListComponent();` line was auto-generated by Angular CLI.
- The examples of `store: Store` were found at https://gist.github.com/btroncone/a6e4347326749f938510

I ended up fixing the error by just deleting the spec file, but I'll check out Julie Ralph's link when I get to implementing specs :)
