### ISSUE TITLE
Pages are smart?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#159]
In the @ngrx/example-app, the pages are the smart.
if I want to use same logic code which in the page, for a different page, should I copy it? it's not about consume the smart with there logic inside and place the smart on several pages?

**Comment by abdulhaq-e** [comment]
If you need to repeat logic inside a smart component, put this logic in a service and inject it into these components.

**Comment by MikeRyanDev** [comment]
Pages are indeed smart components in [@ngrx/example-app](https://github.com/ngrx/example-app), but they don't have to be the _only_ smart components. Either create a shared service as @abdulhaq-e has recommended or create smart components that aren't pages.
