### ISSUE TITLE
(OAuthException - #100) Invalid verification code format. at Facebook

### ISSUE THREAD

**Issue by dheerajkhokhar** [ngrx/store#160]
Hi, I am using Facebook.dll version no. 6.0.10.0 to implement login with facebook in my website.
But some time it generate a error:- Facebook.FacebookOAuthException: (OAuthException - #100) Invalid verification code format. 
I return a this url-  http://sitename.com/controller/returnmethodname?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied 
Anybody have any idea how can i solve this error?

**Comment by 5c0r** [comment]
This is somehow not a problem from ngrx/store itself.

**Comment by robwormald** [comment]
@dheerajkhokhar i think you're in the wrong place 😄
