### ISSUE TITLE
Child component subscription slice not showing current value.  Not sure if this a store issue or angular2 issue.

### ISSUE THREAD

**Issue by wiredprogrammer** [ngrx/store#162]
Hi, 
I'm still in the middle of learning angular2, observables and ngrx/store so forgive me if this is something I've been doing wrong.  I've been trying to implement ngrx/store into a new project I'm working on.  I moved the load of a few common structures to the ngOnInit of the main app component and then made reference in a child router component to the slice through a service using an async pipe to render the array in the view.   

When I do this I don't appear to be getting the current state back in the child component.  I've noticed if I do something to update the state it emits all the current values for the slices and the view updates with the values loaded via dispatch in the root component.  

Anyways I've set up a plunker that I think should show something similar to what I've experience in my project.  Since the angular router is in alpha and angular itself is in 3rd RC then one of those could be causing this or it could be my own ignorance of something I should be doing.  Any help is appreciated.
http://plnkr.co/edit/kk79sgOqPZKfrRyry7Bk?p=preview

Thanks!

**Comment by r-park** [comment]
In `user-list.reducer.ts` add the spread operator to `action.payload` (because it's an array)

BEFORE

``` javascript
case UserListActions.ADD:
  return [...state, action.payload];
```

AFTER

``` javascript
case UserListActions.ADD:
  return [...state, ...action.payload];
```

**Comment by wiredprogrammer** [comment]
Damn. If that was a snake it would've bit me.  I'm still getting the error in my project where I'm doing mostly the load type action but till I can replicate it in a plunk I'm fairly sure its gotta be something I'm doing wrong.  Sorry for wasting your time but thanks for the help anyways!
