### ISSUE TITLE
store let not do subscribe!

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#163]
Hi,

I have two functions:

in reducer:

```
export const getToken = () =>
    (state$: Observable<LoginState>) => {
        return state$.select(s => s.token);
    }

```

in the reducer-index:

```
export function getLoginState() {
    return (state$: Observable<AppState>) => state$
        .select(s => s.login);
}
```

```
export function getToken() {
    return compose(fromLogin.getToken(), getLoginState());
}

```

now, i dispatched action (on click), the state has changed. BUT subscribe not happens! 
also 
{{ token$ | async | json }}
it's show me the init value..

```
this.token$ = store.let(getToken())
 .subscribe(r => {
   console.log('changed?', r); 
 });

```

Why?

**Comment by littleStudent** [comment]
can you add your reducer code?

**Comment by MikeRyanDev** [comment]
@wizardnet972 We won't be able to help you without a clearer code sample. Feel free to re-open this issue or create a new one if you still need help.
