### ISSUE TITLE
Intent to support http://jsonapi.org/ spec?

### ISSUE THREAD

**Issue by adrm** [ngrx/store#164]
I would like to know if there is any project to add support for http://jsonapi.org/ spec in @ngrx/store core or as an addon. I will have to make @ngrx/store handle this spec anyway so if there is some interest, I can help with that so everyone benefits.

Any ongoing effort to support http://jsonapi.org/ spec? Thanks.

**Comment by fxck** [comment]
What is there to support exactly? Shape of the store is up to you really, but you'll find yourself having hard time trying to work with nested data structures, so there's one kinda popular solution for that - https://github.com/paularmstrong/normalizr

**Comment by adrm** [comment]
Ideally, I would like to avoid the boilerplate to add just new data to the store when making a query, or updating the store if data is changed, but I have to reckon that normalizr solves my main issue.

**Comment by MikeRyanDev** [comment]
As @fxck mentioned, [normalizr](https://github.com/paularmstrong/normalizr) is _probably_ what you are looking for.

**Comment by abdulhaq-e** [comment]
I have my own solution, it's a mess right now but I will release it soon. `ngrx-json-api`
