### ISSUE TITLE
a Newbie question regarding modeling of data between components.... 

### ISSUE THREAD

**Issue by oferw** [ngrx/store#170]
Hi dear devs.
am a new angular developer, having converted from AS development, The framework is beautiful, if you don't mind me saying so... :-)

Been writing an angular 2 app and am trying to understand the best practice to share data between components...
I have developed a chat component which internally calls a web service that (using it's response) creates a Customer data object, and uses it to chat to other players. next to it, and independent of it, there's the game Component, which too has a web service and  in turn creates a game details data object... I need to access the Game data from the chat for certain features and the customer data from the game components.
can someone recommend a good practice to share both object from both components ? 
will try and do a plunker if the question is not too clear....

**Comment by fxck** [comment]
Yeah, uhm, try ngrx/store.
