### ISSUE TITLE
countdown timer

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#172]
I want to implement "countdown timer". 

So I have two ways to do that, but what is the recommended way?

one way is to use timer as Observable and subscribe it directly to UI (with async pipe).
so each second the Observable is change and bind it to UI.

the other way is, each second, dispatch an action and reducer return the new state with decremented result.
so each second an action is dispatch and change the state and state change the UI.

What is the best way (performance and maintenance) to achieve that?

Note that, the initial timer start value is in the state. but the count down value should be in the state also? or just get it from Observable directly?

**Comment by wizardnet972** [comment]
in one sentence: Should I update my state every time UI changed? (for, api-service, so on..)

**Comment by roelleor** [comment]
you tend to store only the minimal information required to reproduce the state of the ui. So for example, one would dispatch an action on timer start and timer pause with a timestamp as payload. From there you can calculate the state of the ui-timer.
