### ISSUE TITLE
should I use combineLatest or subject?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#173]
Hi,

What is the best way to do combine props from several states  inside a function?

like this: 

```
myFunction() {

    Observable.combineLatest(
        this.store.select(s => s.login),
        this.store.select(s => s.chat),
        (login, chat) => {
            return {
                token: login.token,
                chatId: chat.id
            };
        })
        .subscribe(r => this.store.dispatch(this.MyActions.newAction(r)))
        .unsubscribe();

}

```

OR like this:

```

myFunction() {

   obser$: Subject<any> = new Subject<any>();

   obser$.withLatestFrom(
     this.store.select(s => s.login),
     this.store.select(s => s.chat),
     (x, login, chat) => {
            return {
                token: login.token,
                chatId: chat.id
            };
        })
        .subscribe(r => this.store.dispatch(this.MyActions.newAction(r)))
    );

    obser$.next('value for x');

}

```

**Comment by wizardnet972** [comment]
Or any other way?
I would like to help here :)

**Comment by kamilbiela** [comment]
http://reactivex.io/rxjs/manual/overview.html#choose-an-operator

**Comment by fxck** [comment]
``` typescript
public onUpdate$: Subject<any> = new Subject<any>();
private _updateAction$ = this.onUpdate
    // or withLatestFrom, depending on if you want the action to trigger only if the initial stream emits, or any of them
    .combineLatest(
       // maybe you can do `s.login.token`, I'm not really using `select`, so don't know
        this.store.select(s => s.login).map(login => login.token),
        this.store.select(s => s.chat).map(chat => chat.id),
        // value was not really used in your code?
        (value, token, chatId) => ({ type: 'UPDATE_REQUEST', payload: { token, chatId } })
    );


constructor(private _store: Store<IYourState>) {
    Observable
        .merge(
            this._updateAction$ 
        )
        .subscribe(res => this._store.next(res);
}
```

and then  

``` typescript
  this.onUpdate$.next('whatever');
```

what you might want to do from the template

```
<form (ngSubmit)="onUpdate$.next($event)">
...
</form>
```

When you need more actions, you just add subject, modify it however you want and add it to that `merge()`.

You also want to unsubscribe when the component gets destroyed, you can do that by doing something like:

``` typescript
private _onDestroy$ =  Subject<any> = new Subject<any>();
ngOnDestroy() {
    this._onDestroy$.complete();
}
```

and then adding `.takeUntil(this._onDestroy)` after that `.merge()`.

**Comment by BaruchFisherman** [comment]
Fxck thanks for your answer, but i have some question:

In your example you use **combineLatest** operator, and the question is - why?
It is not better in this case use **withLatestFrom** instead? 
Like this:

private _updateAction$ = this.onUpdate
    .**withLatestFrom**(
       // maybe you can do `s.login.token`, I'm not really using `select`, so don't know
        this.store.select(s => s.login).map(login => login.token),
        this.store.select(s => s.chat).map(chat => chat.id),
        // value was not really used in your code?
        (value, token, chatId) => ({ token, chatId })
    );
