### ISSUE TITLE
Store select newbie question

### ISSUE THREAD

**Issue by oferw** [ngrx/store#175]
Hi,

I want to send request to my api-service. 
To do that i need two properties from different states. for example i have "person" and "order" states.

makeOrder() {

// need here to get order.id
// need here to get person.id

// let orderId = store.select(s => s.order.id);
// ^ BUT this is an observable which i need to subscribe to... 

sendToHttpRequest({ orderId: order.id, personId: person.id });

}

How to get them both from the store? Is there any way to retrieve objects immediately ?

**Comment by bzums** [comment]
Yes, https://github.com/ngrx/store#migrating-from-store-v1x

**Comment by hongbo-miao** [comment]
``` ts
Observable
  .combineLatest(
    this._store.select(state => state.order && state.order.id),
    this._store.select(state => state.person && state.person.id),
    (orderId, personId) => ({ orderId, personId })
  )
  .subscribe(({ orderId, personId }) => {
    sendToHttpRequest({ orderId, personId });
  });
```

**Comment by wizardnet972** [comment]
@Hongbo-Miao 

Why not to use withLatestFrom?

```

let ob$: Subject<any> = new Subject<any>();

ob.withLatestFrom(
                 this._store.select(state => state.order && state.order.id),
    this._store.select(state => state.person && state.person.id),
    (orderId, personId) => ({ orderId, personId })
  )
  .subscribe(({ orderId, personId }) => {
    sendToHttpRequest({ orderId, personId });
  });

```

Whats the is different?

**Comment by r-park** [comment]
@Hongbo-Miao if I'm not mistaken, `combineLatest` will result in the observable emitting twice: once for `order.id` and once for `person.id`.

@wizardnet972 in your example:
- the observable will not emit until you call `ob$.next()`
- the `withLatestFrom` selector needs to accept an additional param for the value emitted by `ob$`

``` js
(valueFromOb, orderId, personId) => ({orderId, personId})
```

Here's another possible solution using `withLatestFrom`:

``` js
const orderId$ = store
  .select(state => state.order.id)
  .filter(id => !!id);

const personId$ = store
  .select(state => state.person.id)
  .filter(id => !!id);

const orderRequest$ = orderId$
  .withLatestFrom(personId$, (orderId, personId) => ({orderId, personId}))
  .switchMap(ids => sendToHttpRequest(ids)
    .map(result => ({type: 'SUCCESS', payload: result}))
    .catch(error => Observable.of({type: 'ERROR', payload: error}))
  );

orderRequest$.subscribe(store.dispatch);
```

**Comment by hongbo-miao** [comment]
@wizardnet972 yeah @r-park is right. combineLatest will emit whenever `orderId` or `personId` changes. Need choose correct operator based on the usage.

**Comment by tuongaz** [comment]
you can use .zip
