### ISSUE TITLE
Input elements loses focus after dispatch

### ISSUE THREAD

**Issue by oliveiracdz** [ngrx/store#176]
Hi!

As an immutable object, when the state is changed, we create a new object and the Angular renders the html again.
If the action was dispatched by an input element, the focus is lost. I've forked the sample plunk to reproduce the behavior: [http://plnkr.co/yb53ij](http://plnkr.co/yb53ij)
PS: in the real app, I've used the ".debounceTime()" from the forms API, but i think this is not nice to final user.

There is a way to avoid this or I'm missing something?

Thank you!

**Comment by oliveiracdz** [comment]
To solve this, we need to use the [trackBy](https://github.com/angular/angular/issues/4402#issuecomment-179342181) function of *ngFor directive. So we can tell to Angular to not render the DOM again. This can be a performance trap for uninformed developers like me! =P

```
@Component({
  selector: 'todo-list',
  template: `
    <div>
      <todo-list-item 
        *ngFor="#todo of todos; trackBy:custom"
        ...
      ></todo-list-item>
    </div>
  `,
  directives: [TodoListItem]
})
export class TodoList {
  ...

  custom(index,item){
    return index;
  }
}
```

Here is the working plunker demo: http://plnkr.co/1ffRPD6F1vHw0EmHh5er

**Comment by sky-coding** [comment]
This seems like a massive issue, and I can't believe this was the first place I found an answer to this problem. This can't be the only solution to this, right? Anyone using ngrx/store with arrays of _editable_ items will have run into this problem when trying to set up "two-way" data binding to an immutable object within an array. 

Am I crazy? All the store/redux examples show add/delete but this is a common use case and I find it hard to believe that it isn't heavily documented.

**Comment by awerlang** [comment]
I think you'd like to discuss this in here https://github.com/angular/angular/issues/11727

**Comment by DaAitch** [comment]
@sky-coding you can find your answer in @oliveiracdz 's post. When we use ngrx we actually don't want to track focus, selection or cursor information, thus we need to tell angular, that it should try to match DOM elements from last to current state to save that 'soft state'. Another cool feature is, that some themes support animation, like 'slowly appear' etc. which would only work with `trackBy` by the way.
