### ISSUE TITLE
can reducer return Observable to handle async operatons?

### ISSUE THREAD

**Issue by yuyang041060120** [ngrx/store#177]
``` javascript
export const counterReducer: ActionReducer<number> = (state: number = 0, action: Action) => {
    switch (action.type) {
        case INCREMENT:
            return Observable.create(observer => {
                observer.next(state + 1);
            });
        case DECREMENT:
            return state - 1;
        case RESET:
            return 0;
        default:
            return state;
    }
};
```

**Comment by fxck** [comment]
No. Use effects.

**Comment by MikeRyanDev** [comment]
To expand on @fxck's answer, reducers should always be pure, synchronous functions. You will always want to handle async operations outside of reducers.

**Comment by evanjmg** [comment]
Yes, reducers are pure functions, but the middleware doesn't have to be. Is Effects non-blocking? If so it's not very useful as it's never in sync with the store. It'd be better if it was a promisified blocking middleware like those listed in the redux docs - > http://redux.js.org/docs/advanced/AsyncFlow.html
