### ISSUE TITLE
Batching actions in ngrx

### ISSUE THREAD

**Issue by wiredprogrammer** [ngrx/store#178]
So I was looking to see if there was a way to do batch of actions in redux when I came upon this.
https://github.com/reactjs/redux/issues/911#issuecomment-149361073
where  Dan Abrimov suggested something like this as a "redux" way to batch actions.

``` javascript
export const BATCH = 'BATCHING_REDUCER.BATCH';

export function batchActions(actions) {
    return {type: BATCH, payload: actions}
}

export function enableBatching(reduce) {
    return function batchingReducer(state, action) {
        switch (action.type) {
            case BATCH:
                return action.payload.reduce(batchingReducer, state);
            default:
                return reduce(state, action);
        }
    }
}
```

https://github.com/tshelburne/redux-batched-actions/blob/master/src/index.js

Is there a way to do this in ngrx?  
or maybe should a version of this be made available as part of the store?

Thought I'd broach this here first so forgive me if this is more suited for stackoverflow as a usage question.

**Comment by SebastianStehle** [comment]
To be honest i dont understand the code, but you should be able to do something like:

```
export function enableBatching<T>(reducer: ActionReducer<T>){
    const batchReducer: ActionReducer<T> = (state: T, action: Action) => {
        switch (action.type) {
            case BATCH_ACTION:
                let newState = state;
                for (let batchedAction of action.payload.actions) 
                    newState = reducer(newState, batchedAction);
                }
                return newState;
            default:
                return reducer(state);
        }
    };

    return batchReducer;
}
```

**Comment by MikeRyanDev** [comment]
The pattern suggested by Dan Abramov is the pattern I would recommend as well. Should work just fine with ngrx/store.
