### ISSUE TITLE
(how to) Force animation replay

### ISSUE THREAD

**Issue by gil-msbitsoftware** [ngrx/store#179]
Hi
I’m trying to re-activate the same animation for a DOM element, each time an input gets updated.
The animation is defined as css keyframes that is assigned to a css class and the trigger I’m using now is by removing and then re-assigning that css class, with a slight of delay in order to enable the browser to process and render that change before a new one is received.

This seems to me as cumbersome at best, and more so as error prone.
To my understanding, it’s also not exactly what angular 2 animation is about, as I don’t really have different states and transitions between them, but rather just an animation which I wish to re-activate over and over. 
I ran into this article - http://blog.assaf.co/native-slide-toggle-for-angular-2-and-animate/, which seem to support what I need, as it exposes ‘onComplete’ etc., but turns out to be obsolete as per the latest Angular RC.

Am I missing something? Is there a way to elegantly do so without writing my own “animation” API, so that it is not so strictly dependent on hard-coded timed values?
I’d greatly appreciate your input on that.

Here’s my current (example) implementation on Plunkr:
https://plnkr.co/XEOQeKdFsKLA0G7WthJO?p=preview

**Comment by MikeRyanDev** [comment]
There seems to be an open PR angular/angular#10360 that will give you the onComplete callback you are looking for.
