### ISSUE TITLE
Consuming the library via Github

### ISSUE THREAD

**Issue by frederikschubert** [ngrx/store#18]
Hi, first of all, thanks for your great work!
I want to play around with your project but unfortunately I have to use our company's private Nexus npm registry that does not support npm scoped packages. The only second source I can use would be Github but I did not manage to install your project from here using JSPM. 
Would it be possible for you to host your project here in a way that makes it possible to consume via JSPM?

**Comment by robwormald** [comment]
I won't do it on GitHub, mostly because managing checked in dist files is sort of a gigantic PITA.

If you're using JSPM, great! You can do `jspm install npm:@ngrx/store` - which seems to work fine for me. If you can confirm that works I'll see about adding it to the registry so you can drop the `npm` prefix. Does that work for you? Or is your JSPM stuff forced through your private npm as well?

**Comment by frederikschubert** [comment]
Yes jspm is also being forced to go through the private registry. :/ I thought it might be possible to add a postinstall script to the package.json that creates the dist when installing your library from GitHub.

**Comment by robwormald** [comment]
Ah, bummer. If you're just wanting to have a play around with it, its also hosted via npmcdn: `https://npmcdn.com/@ngrx/store`, which you could add to your system config:

```
System.config({
  map: { '@ngrx/store' : 'https://npmcdn.com/@ngrx/store' }
})
```

Let me think about what else I can do - the issue with adding a postinstall script is that it'll require anybody who uses the lib to then have typescript etc installed, which I don't want to require.

**Comment by frederikschubert** [comment]
When I try to install the library via this command

``` bash
jspm install @ngrx/store=github:ngrx/store -o "{ registry: 'npm' }"
```

the dist is not created.

**Comment by frederikschubert** [comment]
Thank you :) I will use your suggested solution till there is some better way!

**Comment by robwormald** [comment]
I think I could probably upload the tagged build to github in a zip/tar under the release, so i'll have a looksee about doing that this weekend.

**Comment by frederikschubert** [comment]
I now have a working workaround. I added a _postinstall_ script to my project where I consume your library and perform an `npm install` in the _node_modules/@ngrx/store_ directory.
I can live with this and you don't have to change anything so I will close this issue for now.

**Comment by philipbulley** [comment]
@robwormald is this still a valid way to quickly play without npm installation?

```
System.config({
  map: { '@ngrx/store' : 'https://npmcdn.com/@ngrx/store' }
})
```

I don't know the SystemJS api very well, but I'm seeing the following network requests

```
GET https://npmcdn.com/@ngrx/utils 404
GET https://npmcdn.com/@ngrx/dispatcher 404
GET https://npmcdn.com/@ngrx/ng2 404
GET https://npmcdn.com/@ngrx/store-backend 404
```

**Comment by laurelnaiad** [comment]
@milkisevil I got this from @brandonroberts, who swears @robwormald is the real king of plnkrs : http://plnkr.co/edit/Na0Mdc2BqWxyMoMin4zZ?p=info

You might find it handy either as a reference or to play with.

**Comment by philipbulley** [comment]
Thanks for that @laurelnaiad — I think that plnkr is using an older version of `store` (even though it's still referenced via the README).

It'd still be very useful to know why the `System.config` setting is failing? Is it a problem with my use of SystemJS or with the `require` paths within https://npmcdn.com/@ngrx/store?

**Comment by brandonroberts** [comment]
@milkisevil here is a plunker using npmcdn with SystemJS mapping: http://plnkr.co/edit/R5qxOj?p=preview

**Comment by philipbulley** [comment]
Thanks @brandonroberts! I noticed that the dependencies that plunk is loading don't have the `.js` ext. Is there a way to get SystemJS to load using the `.js`? I tried using `defaultExtension` but seems to make no difference: http://plnkr.co/edit/PLFbci?p=preview

Trying to figure this out as I'm actually using a private server that doesn't proxy 'no extension' to `.js` as npmcdn seems to do [here](https://npmcdn.com/@ngrx/store@1.3.3/dist/store). I'm ending up with 404s when an extension isn't used.

**Comment by brandonroberts** [comment]
@milkisevil I didn't see in my network tab where it was making the requests without the `.js`. Is there a reason you can't use the map in the plunker example on your private server?

**Comment by philipbulley** [comment]
@brandonroberts this is what I'm seeing: http://imgur.com/xnp8fbg — is your network tab really showing `store.js`, `utils.js`, `dispatcher.js`, etc?

I can't use the same `map:{}` in the plunker as that relies on custom server-side npmcdn.com behaviour: their server maps https://npmcdn.com/@ngrx/store@1.3.3/dist/store (notice no `.js`) to pull in body content from https://npmcdn.com/@ngrx/store@1.3.3/dist/store.js (with `.js`).

Assuming you have a local [lite-server](https://github.com/johnpapa/lite-server) running: `http://localhost:3000/node_modules/@ngrx/store/dist/store` will give you a 404.

Ultimately, I haven't been able to find a way to use @ngrx/store via SystemJS since store was split across multiple files ([v1.3.1](https://github.com/ngrx/store/releases/tag/v1.3.1), I believe).

**Comment by philipbulley** [comment]
Not to worry, going to use webpack instead.

**Comment by robwormald** [comment]
here's a sample system config for future reference:

``` js
System.config({
  //use typescript for compilation
  transpiler: 'typescript',
  //typescript compiler options
  typescriptOptions: {
    emitDecoratorMetadata: true
  },
  //map tells the System loader where to look for things
  map: {
    app: "./src",
    '@ngrx': 'https://npmcdn.com/@ngrx'
  },
  //packages defines our app package
  packages: {
    app: {
      main: './main.ts',
      defaultExtension: 'ts'
    },
    '@ngrx/store': {
      main: 'dist/index.js',
      defaultExtension: 'js'
    },
    '@ngrx/devtools': {
      main: 'dist/index.js',
      defaultExtension: 'js'
    }
  }
});
```
