### ISSUE TITLE
Update to RC 5

### ISSUE THREAD

**Issue by psyCodelist** [ngrx/store#182]
Could you please Update the read.me file to be compatible with RC 5?

Many thanks.

**Comment by zaneadix** [comment]
I would appreciate this as well. I'm running into issues receiving an undefined store on injection. I've set up reducers and provided them to the 'provideStore' function then fed that into the providers in my AppModule(NgModule) but the Store is never properly injected into any component.

**Comment by wizardnet972** [comment]
as @zaneadix say +1

**Comment by robwormald** [comment]
support for RC5 released as 2.1.1
