### ISSUE TITLE
 Type 'Observable<{}>' is not assignable to type 'Observable<number>'.

### ISSUE THREAD

**Issue by harveryang** [ngrx/store#183]
I tried to use the sample code from code page with rc.5 and receive an error that "_Type 'Observable<{}>' is not assignable to type 'Observable<number>'._"

Here is my dependencies:
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1", 
    "@ngrx/store": "2.0.1",
    "@ngrx/core": "^1.0.0",

Is this a bug in ngrx or angular rc.5?

**Comment by awerlang** [comment]
It's not a bug, it's only lack of typing information.

You can use the type safe version of `select()`:

```
this.counter = store.select(s => s.counter);
```

To solve other warnings like this one, I suggest you to learn TypeScript.

**Comment by cozzbie** [comment]
Not particularly sure how learning TS would've exposed the solution this issue. I battled with it till I landed here. Guess I still have some ways to go about TS.

**Comment by clembu** [comment]
@cozzbie TypeScript supersets Javascript to add relatively strong type constraints. In the end it's just JavaScript, but with types. So a generic class (that doesn't exist in vanilla JS) takes a type parameter and you cannot assign a value that is of the wrong type when you specify the parameter, thus `new Observable<number>()` is actually saying to the typescript compiler 
> you: Hey can I have an `Observable<T>` please?
> compiler: Sure, what's `T`?
> you: oh, uhm, `number`.

then everytime `T` is mentionned in the class definition, for that particular instance, it resolves to `number`.
So when you give it something else, it's not happy.

This is all TypeScript and nothing Ngrx.
