### ISSUE TITLE
@ngrx/store is reset on rc5

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#184]
Hi, There is a problem with ngrx and rc5 router this scenario:

I'm on login page. dispatch a login action. (the response is saved to store via reducer)
when the token on the state is change (subscribe) I navigate to another page.
I click on button to navigate back to login page, 
I see that the store injection is back to initial state.

any ideas why?

**Comment by wizardnet972** [comment]
also 
action.type @ngrx/store/init

called twice to reducer.. :(

**Comment by wizardnet972** [comment]
also, in startup application, the action: 
@ngrx/store/init
called twice to same reducer.
at init :(

**Comment by robwormald** [comment]
need a reproduction of this to do any sort of investigation...

**Comment by wizardnet972** [comment]
fixed in 2.1.2
thanks @robwormald :)
