### ISSUE TITLE
@angular/core/index has no exported member 'ModuleWithProviders'

### ISSUE THREAD

**Issue by ghost** [ngrx/store#188]
_/__/node_modules/@ngrx/store/ng2.d.ts(5,23): error TS2305: Module '"_/**/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.

I am using Angular2 RC4 at this time

**Comment by fxck** [comment]
You need rc.5 for the latest version of store. Use `2.0.1` on rc.4.

**Comment by ghost** [comment]
Thanks
