### ISSUE TITLE
store.select return store instead subject

### ISSUE THREAD

**Issue by emilianosantucci** [ngrx/store#194]
Starting from @ngrx/store 2.1.0, method `store.select(...)` return `Store` object instead `Subject` as expected in 2.0.0.

Can anyone help me if it's right behavior?

I can't use state :(

**Comment by jchaney01** [comment]
Same here on RC5

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ApplicationRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { StoreModule} from '@ngrx/store';
import { counter } from './reducers/resume';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    StoreModule.provideStore({ counter }, { counter: {'one':'three'} })
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {

}
```

---

```
import { Component } from '@angular/core';
import {ViewEncapsulation} from '@angular/core';
import { Store} from '@ngrx/store';
import {Observable} from "rxjs";

interface AppState {
  counter: {};
}

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  encapsulation: ViewEncapsulation.None,
  styleUrls: ['app.component.scss']
})

export class AppComponent {
  private foobar:Observable<{}>;
  constructor(private store: Store<AppState>) {
    console.log('store, no instance', store.select('counter'));
    this.foobar = store.select('counter');
  }
}
```

**Comment by seb-bizeul** [comment]
Same here on RC5 too :(

**Comment by MikeRyanDev** [comment]
Not sure I'm fully understanding what is breaking. As of v2.1.0, Store was fixed such that _all_ operators will return a new `Store` instead of just a `Subject` or an `Observable`, but this shouldn't be breaking anything. `Store` is still an observable.

**Comment by jchaney01** [comment]
Thx Mike!  Confirmed this is not a bug but a misunderstanding. Using the async pipe as in the readme or .subscribe() to get the value works as intended

```
store.select('counter').subscribe((v)=>{
  console.log(v);
});
```

**Comment by emilianosantucci** [comment]
Thx @MikeRyan52,
after some troubleshooting I've found the issue.
It was linked to migration on `@ngrx/effects:2.x` with different approach on using actual state (StoreUpdate -> Actions).

I'm confirm it is not a bug.

**Comment by cozzbie** [comment]
The general README still hasn't been updated for this issue.
