### ISSUE TITLE
Need to call unsubscribe?

### ISSUE THREAD

**Issue by brianchance** [ngrx/store#196]
Not an issue, just a question.

Since the store is long running, is it best practice to unsubscribe to any subscriptions created during a components load? 

I have an instance where I call a component method in the subscribe callback that blows and it fires even after navigating to another page. Unsubscribing fixed the issue, made me wonder about all the other subscriptions.

**Comment by awerlang** [comment]
If you call `subscribe()` yourself, and this observable doesn't auto-complete(a finite observable would automatically complete), then you should call `unsubscribe()`.

**Comment by brianchance** [comment]
So, since the store observable does not auto-complete, then yes we need to unsubscribe?

**Comment by fxck** [comment]
Yes, you need to unsubscribe, unless you are using the async pipe. You can use `takeUntil` along with observable `ngOnDestroy` to make it easier for yourself.

https://gitter.im/ngrx/store?at=57ac65b116b0696856ac77be + https://gitter.im/ngrx/store?at=57ac67c4ae838f6f5696fcbc

**Comment by brianchance** [comment]
@fxck - very interesting using `takeuntil`, will give it a try.
