### ISSUE TITLE
Map and filter functions don't return a subscriber in 2.1

### ISSUE THREAD

**Issue by keithernet** [ngrx/store#198]
I apologize if I missed this change, but it appears that this changed between 2.0 and 2.1 and I didn't see it mentioned. I have the following in an angular component:

``` typescript
this.sub =  this.store.filter(a => this.mine(a))
                       .map(d => this.onLoaded(d));
```

In my onDestroy function I call this.sub.unsubscribe().

In 2.0 this worked, in 2.1 instead of this.sub being a subscriber it is the Store. What is the appropriate way to unsubscribe now?

**Comment by awerlang** [comment]
Where's the call to `subscribe()`?

**Comment by keithernet** [comment]
Sorry, I meant to correct the title, I was referring to filter and map.

Subscribe still returns a subscriber, but previously map and filter did, also.

**Comment by awerlang** [comment]
Why would you do that? I guess you're trying to do some imperative stuff, you're better off with:

``` js
this.sub = this.store.filter(a => this.mine(a))
                     .subscribe(d => this.onLoaded(d));
```

Operators like map, filter shouldn't have side effects. There are operators like `.do()` where you can do it, but even so you'd need an subscription for it to work.

As you said it was working in 2.0, it means you were unsubscribing the source subject, which is weird.

**Comment by keithernet** [comment]
It doesn't have a side effect. I use this.sub in an async pipe in the template. Which, of course, made me realize that I didn't need to unsubscribe it manually at all because the async pipe will handle it.

**Comment by awerlang** [comment]
Correct about async pipe.

Just to make it clear, it doesn't matter. Naming it `sub` it's a misnomer, because observable operators return an `Observable` not a `Subscription`.

**Comment by keithernet** [comment]
Right, makes sense. 

Thanks!
