### ISSUE TITLE
Peer @ngrx/store@1.5.0 wants @angular/core@^2.0.0-rc.0

### ISSUE THREAD

**Issue by cloudscape-germany** [ngrx/store#199]
`npm ERR! peerinvalid Peer @ngrx/store@1.5.0 wants @angular/core@^2.0.0-rc.0`

Any plans to update to Angular2 RC4 or even RC5 any time soon?

**Comment by littleStudent** [comment]
@ngrx/store@2.1.2 is fully compatible with angular rc5.

**Comment by cloudscape-germany** [comment]
That's splendit. Which one for RC4?

**Comment by MikeRyanDev** [comment]
@nottinhill `~@ngrx/store@2.0.0`
