### ISSUE TITLE
getting warning on console.

### ISSUE THREAD

**Issue by smkamranqadri** [ngrx/store#203]
please review below warning which are showing in console, i am using webpack.

./~/@ngrx/store/index.js
Cannot find source file '../src/index.ts': Error: Cannot resolve 'file' or 'directory' ../src/index.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
./~/@ngrx/store/ng2.js
Cannot find source file '../src/ng2.ts': Error: Cannot resolve 'file' or 'directory' ../src/ng2.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
webpack-dev-server.js:1 ./~/@ngrx/store/reducer.js
Cannot find source file '../src/reducer.ts': Error: Cannot resolve 'file' or 'directory' ../src/reducer.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
webpack-dev-server.js:1 ./~/@ngrx/store/state.js
Cannot find source file '../src/state.ts': Error: Cannot resolve 'file' or 'directory' ../src/state.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
webpack-dev-server.js:1 ./~/@ngrx/store/store.js
Cannot find source file '../src/store.ts': Error: Cannot resolve 'file' or 'directory' ../src/store.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
webpack-dev-server.js:1 ./~/@ngrx/store/utils.js
Cannot find source file '../src/utils.ts': Error: Cannot resolve 'file' or 'directory' ../src/utils.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
webpack-dev-server.js:1 ./~/@ngrx/store/dispatcher.js
Cannot find source file '../src/dispatcher.ts': Error: Cannot resolve 'file' or 'directory' ../src/dispatcher.ts in /Volumes/data/onseen-admin-client/node_modules/@ngrx/store
webpack-dev-server.js:1 ./~/rxjs/rx.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
webpack-dev-server.js:1 ./~/rxjs/Rx.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

**Comment by brandonroberts** [comment]
Closing as sourcemaps have been fixed
