### ISSUE TITLE
Update dependencies to allow newer rxjs

### ISSUE THREAD

**Issue by TiS** [ngrx/store#204]
Angular RC6 is dependent of `"rxjs": "^5.0.0-beta.11"`. It would be nice to update package.json of ngrx store to allow this version (and test it with it of course). Right now node throws 'UNMEET PEER DEPENDENCY' warning.

**Comment by laurelnaiad** [comment]
rxjs has been floating since 2.1.2
https://github.com/ngrx/store/commit/e14042c6d071d9f6c03f799d628535f75b027ab3

**Comment by satlom** [comment]
+1
rxjs is locked in  package.json to "rxjs": "5.0.0-beta.6" 
Please update as TiS suggested.

**Comment by MikeRyanDev** [comment]
There is already a semver range for rxjs in the current published version.
