### ISSUE TITLE
Problem updating state

### ISSUE THREAD

**Issue by gperdomor** [ngrx/store#206]
I need change the values <code>audio</code> and <code>video</code> properties of local portion of my state.

My state is:

<pre><code>state: {
    peers: []
    local: {
        audio: true,
        video: true
    }
}</code></pre>

The component constructor is 

<pre><code>constructor(private store: Store<AppState>,
              private rtc: WebRTCService,
              private localActions: LocalActions,) {

    this.audio = store.select('local', 'audio');
    this.video = store.select('local', 'video');
}
</code></pre>

and i also have a button `<a (click)="toggleAudio()">Toggle Audio</a>`

The toggle function is:

<pre><code>toggleAudio(enable) {
    if (this.audio) {
        this.rtc.mute();
    } else {
        this.rtc.unmute();
    }
    this.store.dispatch(this.localActions.toggleAudio(!this.audio));
}</code></pre>

When i press the button, the first time, the action is dispatched with false as payload and my new status is correct, but, when i press again, the action is dispatched again with false and the state is the same than before.

**Comment by gperdomor** [comment]
As workaround, i put a second button and use a new parameter in `toogleAudio` function

`<a (click)="toggleAudio(true)" *ngIf="(audio|async)">Toggle Audio</a>`
`<a (click)="toggleAudio(false)" *ngIf="!(audio|async)">Toggle Audio</a>`

<pre><code>toggleAudio(enable) {
    if (enable) {
        this.rtc.mute();
    } else {
        this.rtc.unmute();
    }
    this.store.dispatch(this.localActions.toggleAudio(!enable));
}</code></pre>

But... Why the first code fails?

**Comment by awerlang** [comment]
``` ts
toggleAudio(enable) {
    if (this.audio) {
        this.rtc.mute();
    } else {
        this.rtc.unmute();
    }
    this.store.dispatch(this.localActions.toggleAudio(!this.audio));
}
```

`this.audio` refers to an `Observable` instance, so you can't verify its value this way. When you use the `async` pipe you're unwrapping its value, so `ngIf` receives a value. If you remove the pipe, it will receive an `Observable` too.

This is a possible solution:

``` ts
toggleAudio() {
    this.audio.first().subscribe(enabled => enabled ? this.rtc.mute() : this.rtc.unmute());
    this.store.dispatch(this.localActions.toggleAudio(!this.audio));
}
```

Because I used `first` the subscription will complete and unsubscribe itself.

**Comment by gperdomor** [comment]
@awerlang thanks!...

You're correct, but i need to include the dispatch in the subscribe:

<pre><code>this.audio.first().subscribe(enabled => {
    enabled ? this.rtc.mute() : this.rtc.unmute();
    this.store.dispatch(this.localActions.toggleAudio(!enabled));
});</code></pre>
