### ISSUE TITLE
Is it anyway to setState for the root state

### ISSUE THREAD

**Issue by elaijuh** [ngrx/store#209]
I am working on `angular2-hmr` to get it along with `ngrx/store`, where there is a need to reset the whole root state. I am not sure if reducer can do that, but is it good to have an API for this?

**Comment by MikeRyanDev** [comment]
No, there's no API in @ngrx/store to set the state. 

My recommendation is to create a meta reducer that listens for a `SET_STATE` action (or whatever you want to call it) and use it to compose your root reducer:

``` ts
import { compose } from '@ngrx/core/compose';
import { ActionReducer, combineReducers } from '@ngrx/store';


function stateSetter(reducer: ActionReducer<any>): ActionReducer<any> {
  return function (state, action ) {
    if (action.type === 'SET_STATE') {
      return action.payload;
    }

    return reducer(state, action);
  }
}

const rootReducer = compose(stateSetter, combineReducers)({
  auth: authReducer,
  blog: blogReducer
});
```

Then in your HMR callback dispatch a `SET_STATE` action with the reloaded state:

``` ts
import { Store } from '@ngrx/store';


@NgModule({ ... })
class MainModule {
  constructor(private store: Store<any>) { }

  hmrOnInit(store) {
    if (!store || !store.state) return;

    this.store.dispatch({
      type: 'SET_STATE',
      payload: store.state
    });
  }
}
```

**Comment by elaijuh** [comment]
This is what I originally think about, thanks.

**Comment by coderlex** [comment]
Is this method still supported? I've just updated ngrx packages up to 4.0.2, and it seems like the root reducer I'm passing to `StoreModule.forRoot` isn't called now.
