### ISSUE TITLE
UMD Bundle (please)

### ISSUE THREAD

**Issue by kylecordes** [ngrx/store#210]
This is a feature request: it would be convenient for online example use if ngrx/store would ship a bundle of some kind. Although the project is composed of a modest number of files anyway, it is still easier to explain if it can be loaded from a single bundle directly from (for example) SystemJS or even a script tag.

Following along with where the Angular project itself has landed, I believe it makes the most sense to ship a UMD bundle.

The should require only a modest change to the package/build process, but I thought it wise to discuss in a feature request to see if it is desired by the ngrx team, before tinkering with an actual PR.

**Comment by MikeRyanDev** [comment]
We have revamped the build process in ngrx/db to emit ES2015 modules and include a UMD bundle. Plan is to make this consistent across all ngrx projects.

**Comment by kylecordes** [comment]
Excellent, I will keep an eye on that project also.
