### ISSUE TITLE
Question: Example in Readme.md

### ISSUE THREAD

**Issue by michael34** [ngrx/store#215]
Why is state of type number?
`export const counterReducer: ActionReducer<number> = (state: number = 0, action: Action) => {`
shouldn't it be:
`export const counterReducer: ActionReducer<AppState> = (state: AppState, action: Action) => {`

Is there something I'm missing?

**Comment by littleStudent** [comment]
your reducer represents a slice of your `AppState`. not the whole AppState.
So in this case the `counterReducer` is of type `number` because thats what it represents.

the AppState would be:

```
{
    counter: number
}
```

**Comment by michael34** [comment]
Thanks. I have another issue in my code then. Will look into it in two weeks. Of to school now.

**Comment by littleStudent** [comment]
I recommend using [gitter](https://gitter.im/ngrx/store) for such questions. you will get a fast answer and its easier to discuss things

**Comment by michael34** [comment]
@littleStudent I looked for the gitter-link, actually. Apparently I was blind... Thanks for the suggestion though.
