### ISSUE TITLE
Problem updating state

### ISSUE THREAD

**Issue by gperdomor** [ngrx/store#216]
Last week, i came here with a problem described in #206

thanks to @awerlang the problem was solved...

But, today, i updated the version of angular to RC7, which update the rxjs from 5 beta 11 to beta 12, and now i have a new problem -> <code>this.audio.first is not a function</code>

<pre><code>toggleAudio() {
    this.audio.first().subscribe(enabled => {
        // do something
        this.store.dispatch(this.localActions.toggleAudio(!enabled));
    });
}</code></pre>

but this works:

<pre><code>
var source = Observable.range(0, 10).first().subscribe(
    function (x) {
        console.log('Next: %s', x);
    },
    function (err) {
        console.log('Error: %s', err);
    },
    function () {
        console.log('Completed');
    }
);
</code></pre>

In fact, adding this line <code>var source = Observable.range(0, 10).first()</code> on top of <code>toggleAudio</code> function, makes that function, work as excepted.

**Comment by r-park** [comment]
Did you try:

``` js
import 'rxjs/add/operator/first';
```

**Comment by gperdomor** [comment]
@r-park nice! it works... Why this is needed now?.

**Comment by robwormald** [comment]
this probably happened because we removed the automatic adding of things in angular core. You should always explicitly import the things you need.
