### ISSUE TITLE
$ngrx/core/operator/select reference error

### ISSUE THREAD

**Issue by mikeeus** [ngrx/store#219]
I'm using Angular2 final and I came by this error today. 

ERROR in ./~/@ngrx/store/src/store.ts
Module not found: Error: Can't resolve '@ngrx/core/operator/select' in '/home/mikias/workspaces/ethiotrade/ang-client/node_modules/@ngrx/store/src'
 @ ./~/@ngrx/store/src/store.ts 6:0-52
 @ ./~/@ngrx/store/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] /home/mikias/workspaces/ethiotrade/ang-client/node_modules/@ngrx/store/src/store.ts:1:40 
Cannot find module '@ngrx/core/operator/select'.

I googled around and didn't find any previous solutions, but while poking around I noticed that the @ngrx/store/src/store.ts file has:
 `import { select, SelectSignature } from '@ngrx/core/operator/select';`.
But in the @ngrx/core package the file path is `@ngrx/core/src/operator/select`. 

I made the change and I no longer get the error. So I forked the repo and ran the tests, all pass. I made the change to the path and ran the tests again, and they still pass. So clearly it's not being caught.

I'm guessing this is a simple typo so I've made a pull request correcting this. Hope this helps.

**Comment by kylecordes** [comment]
The select stuff is now exported from core at the top - see comment from @MikeRyan52 in Gitter. Change to make ngrx/store use that is here: https://github.com/ngrx/store/pull/218

**Comment by MikeRyanDev** [comment]
Fixed in v2.2.1
