### ISSUE TITLE
Use "string based enums" trick?

### ISSUE THREAD

**Issue by vivainio** [ngrx/store#22]
Some code in the examples could be streamlined by using this trick instead of `const FOO="FOO";`:

https://basarat.gitbooks.io/typescript/content/docs/tips/stringEnums.html

**Comment by frederikschubert** [comment]
An even easier solution would be to import the actions as a module:

``` typescript
import * as actions from "./actions";

if(action === actions.LOAD_USER) {
    ...
}
```

**Comment by vivainio** [comment]
@frederikschubert that would be lots of typing to export all the strings from the module

**Comment by robwormald** [comment]
i'm not a huge fan of this, personally, as it depends on a runtime dependency and obfuscates what's really happening. 

check out https://basarat.gitbooks.io/typescript/content/docs/types/stringLiteralType.html for a new feature in TS 1.8 that's a bit more elm-like.

**Comment by robwormald** [comment]
(that's not to say, don't do it in your own stuff, but i'm generally against "tricks" especially in demos and readmes - its one more thing to grok for somebody who's new to the whole concept)

**Comment by vivainio** [comment]
@robwormald totally agree that TS 1.8 string literal types are the way to go for this. Closing.
