### ISSUE TITLE
Breaks the latest Quickstart (Angular 2.0)

### ISSUE THREAD

**Issue by pietro909** [ngrx/store#221]
Hello,
I'm trying to use `ngrx/store` with the final Angular 2.0 release, but it generates a weird error, probably related to dependencies:

```
zone.js:1263 GET http://localhost:3000/traceur 404 (Not Found)
(index):18 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/traceur(…)
```

Removing the `catch()` function from the SystemJS bootstrap I get a more useful error:

```
Error loading http://localhost:3000/node_modules/@ngrx/store/index.js as "@ngrx/store" from http://localhost:3000/dist/app.module.js ;
```
## Example

I set up a minimal example forking [Angular 2 Quickstart](https://github.com/angular/quickstart) and adding just one reducer and the `ngrx` import in the ngModule file:
- [my current branch](https://github.com/pietro909/quickstart/tree/broken-ngrx)
- [the diff with Quickstart](https://github.com/angular/quickstart/compare/master...pietro909:broken-ngrx?expand=1)
## System information
- node: v4.5.0
- npm: v2.15.9
- Chrome: 52.0.2743.116
- OS/X Yosemite 10.10.5

Thank you for helping,
Pietro

**Comment by pietro909** [comment]
Sorry, it turns out that it was my mistake in `system.config.js`. Rather than mapping the `ngrx` modules to the new `bundles/*.umd.js` standard, I was still using `index.js`.

This correction fixed my issue:

```
System.config({
    // ...
    packages: {
           // ...
            '@ngrx/core':                   { main: 'bundles/core.umd.js', defaultExtension: 'js' },
            '@ngrx/store':                  { main: 'bundles/store.umd.js', defaultExtension: 'js' }
```

Can I point out that the error handling of SystemJS is everything but meaningful?

**Comment by adrian-moisa** [comment]
Had the same issue. Your fix worked. Thank you!
