### ISSUE TITLE
Docs confusion on initial state

### ISSUE THREAD

**Issue by simonh1000** [ngrx/store#222]
The readme seems to set the initial state in 2 different way 

```
export const counterReducer: ActionReducer<number> = (state: number = 0, action: Action) => {
```

which is familiar from redux, and 

```
StoreModule.provideStore({ counter: counterReducer }, { counter: 0 })
```

If I have understood correctly, this is not as DRY as it could be. (I understand that the first line does in theory permit passing `undefined` to the reducer, but this does not feel like good coding either.

**Comment by MikeRyanDev** [comment]
The first way is recommended in most situations. The second API exists for rehydrating state.
