### ISSUE TITLE
Enhancement: change color of console output

### ISSUE THREAD

**Issue by alexciesielski** [ngrx/store#224]
This is just a minor annoyance actually, but when using the dark theme in Chrome DevTools, the title of the console output is barely readable, because of black text (see screenshot).

Would be nice  to have it change color depending on the theme, or just have a setting somewhere to change it myself.

![screen](https://cloud.githubusercontent.com/assets/17651898/18636938/f9c5a784-7e8a-11e6-96a3-5660e40cff76.png)

**Comment by fxck** [comment]
https://github.com/btroncone/ngrx-store-logger particularly https://github.com/btroncone/ngrx-store-logger#options

**Comment by alexciesielski** [comment]
Thanks. I wonder what kind of string to pass tho, I've tried both hexa (#fff) and 'white' but the title stays black. Any suggestions?

**Comment by ciesielskico** [comment]
I've tried passing functions and strings but the colors stays the same.

```
let options = {
    colors: {
        title: () => '#fff'
    }
}
export default compose(storeFreeze, storeLogger({ options }), combineReducers)({
    auth: authReducer,
    config: configReducer,
    customer: customerReducer,
    customerSearch: searchCustomerReducer
});
```

**Comment by alexciesielski** [comment]
After some trial and error I found it, the object you have to pass looks like this
`storeLogger({ colors: '#ffffff' })`
