### ISSUE TITLE
Question / Enhancement: Self-executing Actions?

### ISSUE THREAD

**Issue by brian428** [ngrx/store#225]
I'm new to ngrx, and am learning about it and trying different approaches out in a test project. One idea that came to me immediately is the idea of "self-executing" actions. This seems to make sense to me, because it does away with the need for big switch/case statements in reducers and wraps up all the related pieces (action types, action itself, and action logic) in one place.

Something along this line:

``` javascript
export interface IExecutableAction extends Action {
  execute( state: any ): any
}

export const NameActionTypes = {
  ADD_NAME_LIST: 'ADD_NAME_LIST'
};

export class AddNameListAction implements IExecutableAction {
  type = NameActionTypes.ADD_NAME_LIST;
  constructor( public payload: string[] ) {}

  execute( state: string[] ): string[] {
    // Run logic that would normally be in reducer switch/case.
    return this.payload;
  }
}

// Reducer now just invokes execute(). No need for big switch/case statements...
export const reducer = ( state: string[] = [], action: IExecutableAction ) => {
  return action.execute( state );   
};
```

Now while this _seems_ viable to me, I can't really find anyone else who's advocating this idea. This concerns me, since it's totally possible that there's some giant flaw in this approach that I'm not seeing because I'm a noob.

So first, _is_ there a giant flaw in this approach that I'm not seeing? And if not, is this something the ngrx team might want to incorporate or include in any docs as a possible design approach?

**Comment by kylecordes** [comment]
I have seen the same sort of idea discussed in other contexts (ngrx predecessors like Redux etc.) and the typical objection is that actions are ideally "just data", rather than being a bundle of data and functionality. By being just data they can be trivially persisted, listed, displayed and manipulated in arbitrary ways. Bundling an action's data tightly at the language level (in a class) with some code that takes a dependency on the shape of the whole state potentially, makes this tougher. It means that the logic performed by a system to execute an action "leaks" around an entire system to every other part of the system that takes a dependency on the action.

However, there is probably some more concise solution available to the action dispatch problem, rather than lots and lots of huge switch statements.  Our switch statements have been building up in an unwieldy way, over here we are definitely "in the market" for something to help here. Over in some other languages with more different method dispatch mechanisms (Clojure/CLJS, many others), it's pretty easy to let the language take care of the sort of thing without bundling the actions data into a class with reducer code. I wonder what sort of variation could be implemented within the typescript semantic vocabulary for this.

**Comment by brian428** [comment]
Thanks for the quick response! However, I'm not sure what you mean about the action logic "leaking" around the entire system? I'm just doing this, which seems pretty much indistinguishable from any other form of action dispatching:

`this.store.dispatch( new AddNameListAction( payload ) )`

The reducer is the only thing that "knows" that the action is doing the work. Am I missing something?

**Comment by brian428** [comment]
On a side note, I share your concern about the reducer switch/case getting unwieldy. We're about to start re-building a prototyped app that is fairly complex, and I can already picture the "normal" reducers getting out of hand pretty quickly. My first thought was extracting the action logic into separate functions (that can be imported for a shared location if needed), and that's when the idea of executable actions came to me.

**Comment by brian428** [comment]
Just to add to this (for Kyle, or anyone else who's interested), two potential pitfalls of this seem to be:
- Without some additional logic, all reducers would try to execute the passed Action. So you either still need the basic switch/case, or some other logic to let the reducer determine whether to execute the Action.
- Along the same line as above, without some sort of decision-making logic, it's difficult to have more than one reducer handle an Action.

So now some of the problems are coming to the surface. It looks like the basic switch/case logic needs to be there, even if all the case does is invoke `action.execute()`.

**Comment by awerlang** [comment]
``` ts
export interface IExecutableAction extends Action {
  executeReducerA( state: any ): any { return state; }
  executeReducerB( state: any ): any { return state; }
}

export const NameActionTypes = {
  ADD_NAME_LIST: 'ADD_NAME_LIST'
};

export class AddNameListAction implements IExecutableAction {
  type = NameActionTypes.ADD_NAME_LIST;
  constructor( public payload: string[] ) {}

  executeReducerA( state: string[] ): string[] {
    // Run logic that would normally be in reducer switch/case.
    return this.payload;
  }

  executeReducerB( state: string[] ): string[] {
    // Run logic that would normally be in reducer switch/case.
    return state.concat(this.payload);
  }
}

// Reducer now just invokes execute(). No need for big switch/case statements...
export const reducerA = ( state: string[] = [], action: IExecutableAction ) => {
  return action.executeReducerA( state );   
};

export const reducerB = ( state: string[] = [], action: IExecutableAction ) => {
  return action.executeReducerB( state );   
};
```

This would be the OO-equivalent to redux.

**Comment by brian428** [comment]
Hmm...wouldn't that mean you'd need separate reducers for _every_ action?

Edit: Not only that, but without the swtich/case in the reducers to decide whether to execute the action, wouldn't every reducer always try to execute every action?

**Comment by awerlang** [comment]
> Hmm...wouldn't that mean you'd need separate reducers for every action?

No. Different executable actions would implement the same method (i.e. reducer), to implement an 1:N relationship between reducers and actions in redux.

> Edit: Not only that, but without the swtich/case in the reducers to decide whether to execute the action, wouldn't every reducer always try to execute every action?

It would. Actions wouldn't implement the majority of reducers. The default implementation returns the previous state as per redux.

**Comment by kylecordes** [comment]
@brian428  By "leak" I mean that this information is theoretically available to any code which imports the action types, which code would widely import from all around the system in the example snippet you suggested. In theory, theoretically available cause no harm as long as everyone writing all the code is the discipline not to use it. In practice, it's tough to maintain a disciplined structure of the system without help of some tooling. With the typical reducer design, the reducers are hidden over in a set of modules that implement the state of the system, and it's fairly easy to see that they are not being referred to from anywhere else. Once you combine the logic for those reducers into the actions, the delightfully rigorous dependency flow that we typically get with a ngrx/store or redux-flavored system starts to leak. Hope this makes sense, I don't think I'm explaining it very well.

**Comment by brian428** [comment]
I think I follow. But if you were to break the reducer logic into separate functions so they can be more easily composed (instead of having the logic all inline in the switch/case), wouldn't the potential for "leakage" that you mention be the same? 

Also, with decomposed functions or with executable Actions, neither of them can actually modify the state unless they're executed within the a reducer and affect the reducer's output. External code could invoke the functions or Actions, but that wouldn't have any effect at all, because the state is only affected by the return values of the reducers themselves. So while the functions/Actions _could_ be invoked from external code, I'm not sure why anyone would, because it wouldn't have any effect on anything. Right?

**Comment by rweng** [comment]
For what it's worth, I am doing s.th. similar, except that I left the separation of actions and logic in place:

```
export interface Handler<State> {
    canHandle: (action: Action) => boolean;
    handle: (action: Action, state: State) => State | Error;
}
```

``` ts
export const connectionsReducer = createReducer<Connection>([
    new AddHandler<Connection>([AddConnectionAction], Connection.Constraints),
    new UpdateHandler<Connection>([SetConnectionAction], Connection.Constraints),
    new SyncActionHandler(),
    new ConnectionNormalizationHandler()
]);
```

`createReducer` basically just call all Handlers that can handle the action in order, returns the state if no handler can handle the action and adds some error handling.
