### ISSUE TITLE
Illegal Invocation calling multiple dispatches

### ISSUE THREAD

**Issue by ribsies** [ngrx/store#229]
I keep getting a `TypeError : llegal invocation` error when I call dispatches next to each other like this.

```
this._store.dispatch(firebaseActions.setFirebaseAccountState(user));
this._store.dispatch(accountActions.setAccountState(account));
```

each one is manipulating a seperate slice of state. It doesn't matter which actions I dispatch, if 2 are next to each other it errors.

In the window logger I can see both actions are called but only the first changes it's data. By themselves, they both work fine.

I have no subscriptions to any piece of the store anywhere in my code, I am only setting up dispatches.

Both of these dispatches do the same thing to the store.

Here is my account reducer, I am not doing anything fancy. The other reducer in this example is exactly the same.

```
const initialAccountState : Account = null;

export const accountStateReducer = (state : Account = initialAccountState, action : Action) : Account => {
    switch (action.type) {
        case AccountActions.SET_ACCOUNT:
            return Object.assign({}, state, action.payload);
        default:
            return state;
    }
};
```

Any ideas what the problem is?

EDIT: I discovered if I switch the order of these 2 dispatches, they both work fine with no error. What are the rules for order of dispatches?

EDIT 2: I then discovered it was ngrx-store-freeze that was causing the error. Removing that fixes it.

**Comment by awerlang** [comment]
Could it be the initial state as `null` the cause?

**Comment by ribsies** [comment]
I tested that and even with an actual value it still errors out when using `ngrx-store-freeze`

**Comment by awerlang** [comment]
_Entering guessing mode..._

Do you have a `.do(console.log)` anywhere perhaps?

**Comment by MikeRyanDev** [comment]
Seems like this has been resolved. Please reopen and leave a comment if it is not.
