### ISSUE TITLE
memoizing / caching / distinctUntilChanged

### ISSUE THREAD

**Issue by fxck** [ngrx/store#231]
There's one thing that's been bugging me. I have one `entities` reducer, which catches all actions with `entities` in payload. I got the idea from Redux's real world example app. https://github.com/reactjs/redux/blob/master/examples/real-world/src/reducers/index.js#L9

The problem is that when I "project" an ID into an entity(in a selector), and any part of `entities` changes, it will trigger change detection, as the reference changed, even though it was a different part of entities, which can cause some flickering and stuff - https://gitter.im/angular/angular?at=57e9306076d85b087daa7147 

I should I abandon the idea of `entities` slice on the root? What about when you you need to combine entities even if they are on the difference slices? Typically when you have something like this

``` typescript
// article
{
  id: 1,
  name: 'foo',
  media: [ 1, 2, 3 ], //  normalized
  author: 1, //  normalized
}

```

and you are putting it back together in a selector? Should I instead of using `reduce` in an `article` selector use separate selector for media, something like `getMediaEntitiesFrom$([1,2,3])`?

What are you all doing to optimise selectors so they don't run hundred times with any change on the store?

**Comment by laurelnaiad** [comment]
You can use `.scan()` to preserve previously pushed object so that you can base the next version on the previous and not generate new references for subvalues which haven't changed.

**Comment by wizardnet972** [comment]
@fxck Selectors as you know can be optimise. I use selector to the property itself, or to an array, and I add distinctUntilChanged.

I explored the change detection and subscribe function, and the store when it's fire.
for now I can tell you that angular2 change detection **does not care** about reference property, only by the value.

more about that I'll share after I will finished [angular2-seed-ngrx](https://github.com/wizardnet972/angular2-seed-ngrx)

**Comment by laurelnaiad** [comment]
> > for now I can tell you that angular2 change detection does not care about reference property, only by the value.

I beg to differ.  How did you come to this conclusion?

**Comment by wizardnet972** [comment]
@laurelnaiad , 
I test it by write ngFor of some array in my html file.
then on button clicked I change the some array to new array (which mean different memory object) and I track the change on the DOM elements and subscribe functions.
In the next week I'll upload my article that explain about this stuff.. :)

I bring you a quote from [How does Angular 2 Change Detection Really Work ?](http://blog.angular-university.io/how-does-angular-2-change-detection-really-work/)

> **What about comparison by reference?**
> The fact of the matter is that Javascript objects are mutable, and Angular wants to give full support out of the box for those.
> _Imagine what it would be if the Angular 2 default change detection mechanism would be based on reference comparison of component inputs instead of the default mechanism?_ Even something as simple as a TODO application would be tricky to build: developers would have to be very careful to create a new Todo instead of simply updating properties.

**Comment by laurelnaiad** [comment]
Here is some of the code that deals specifically with diffing: https://github.com/angular/angular/tree/master/modules/%40angular/core/src/change_detection/differs .

**Comment by laurelnaiad** [comment]
I guess the reason I'm pushing back is that I have seen the difference between applying `.scan` (using it to preserve generated elements in a collections when the elements haven't changed) or not using it... such that the difference between 'this is a a new set of different objects' vs. 'this is new set mostly containing the same objects) is visible on the screen.... and I know it's not a byvalue comparison because I know that what's in the collection are object references.... so it just seems hard to believe what you're saying. 

The quote you cite seems off to me. It certainly doesn't seem to be describing an ngrx app. It seems to be extolling the benefits of not doing things reactively.

**Comment by marcusreese** [comment]
Thanks @laurelnaiad and @wizardnet972 for good points.
Building on those, can someone please post sample code? I assume it will replace:

```
    this.someArray = store.select('someArray');
```

**Comment by fxck** [comment]
https://github.com/ngrx/example-app/pull/75
