### ISSUE TITLE
Angular Ahead-of-Time compilation issue

### ISSUE THREAD

**Issue by metrophos** [ngrx/store#232]
Hy!

When I use the AOT compilation I can't use a function to prepare my reducers. With JIT it works fine.

If I write
`StoreModule.provideStore(prepareReducer(...));`

I get this error from ngc 

> Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

It would work if the provideStore function inside ng2.ts use useFactory instead of useValue on _INITIAL_REDUCER
`{ provide: _INITIAL_REDUCER, useFactory: _reducer }`

So I can do something like this:

```
export function prepareReducers() {
    return ...;
}

export const REDUCER = StoreModule.provideStore(prepareReducers);
```

Maybe there is a common way to solve my problem but I can't found a solution.

**Comment by brandonroberts** [comment]
The `provideStore` already supports using a function to return your reducer, so your example should work.

**Comment by alexciesielski** [comment]
`ngrx/core 1.2.0`
`ngrx/store 2.2.1`

Having the same issue, JIT works but `ng build --aot` fails with the following error

Error:
`Error encountered resolving symbol values statically. Calling function 'createReducer', function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in app.module.ts`

reducers/index.ts

```
const reducers = {
    app: fromApp.reducer,
    router: routerReducer,
    auth: fromAuth.reducer,
};
export function createReducer(asyncReducers = {}): ActionReducer<any> {
    if (environment.production) {
        return compose(
            combineReducers
        )(Object.assign(reducers, asyncReducers));
    } else {
        return compose(
            storeFreeze,
            storeLogger({ colors: { title: () => '#ffffff' } }),
            combineReducers
        )(Object.assign(reducers, asyncReducers));
    }
}

export const appReducer = createReducer();
```

app.module.ts

```
// ngrx/store
StoreModule.provideStore(appReducer),
```

**Comment by alexciesielski** [comment]
Fixed it by adding this:

```
export function appReducer(state, action) {
    let reducer = createReducer();
    return reducer(state, action);
}
```

and importing this in app.module.ts

```
// ngrx/store
StoreModule.provideStore(appReducer),
```

**Comment by metrophos** [comment]
Sorry for my late answer. 

The solution from @ciesielskico works with one reducer but I want to use multiple reducers with a prepare function.

My solution is:

```
import { StoreModule, combineReducers } from '@ngrx/store';

import { ReducerService } from './shared';
import { FIRST_REDUCER, SECOND_REDUCER } from './reducers';


export function appReducer(state, action) {
    return combineReducers(ReducerService.prepareReducers(
        {
            'first': FIRST_REDUCER,
            'second': SECOND_REDUCER,
        }
    ))(state, action);
}

export const REDUCER = StoreModule.provideStore(appReducer);
```

Now it works fine.
Thanks!
