### ISSUE TITLE
Problems using Observable .delay method

### ISSUE THREAD

**Issue by simonh1000** [ngrx/store#235]
In my parent controller I have 

```
this.selectedResto = this.store.select(state => state.selectedResto[0]).delay(500);
```

Changes to this part of my state are triggered by google maps clicks using ngZones. That plugs into this template

```
  <div *ngIf='selectedResto | async' class='selected-resto'>
    <app-resto [resto]='selectedResto | async' (action)='store.dispatch($event)'></app-resto>
  </div>
```

and through app-resto to 

```
<h4>
    <span *ngIf='cuisines[resto.cuisine]'>({{cuisines[resto.cuisine].name}})</span>
</h4>
```

I'm getting this error, about 500ms after the initial click triggering the state change

> error_handler.js:45 EXCEPTION: Error in ./RestoComponent class RestoComponent - inline template:3:7 caused by: Cannot read property 'cuisine' of null

Without the `delay` everything works fine, but with an instantaneous change of the content

**Comment by awerlang** [comment]
Change your component template to:

```
*ngIf='resto && cuisines[resto.cuisine]'
```

This happens because of the delay, component won't have `resto` already in-place.

**Comment by simonh1000** [comment]
That helps but I am getting it in every single use of resto, e.g. `{{resto.name}}` too. What can I do at the parent level to address this? What I don't understand is that if `.delay` simply delays an observable, why is Angular already trying to render?

**Comment by awerlang** [comment]
Angular doesn't delay rendering in any way. If data is synchronous, Angular will bind to the component property before first render. In any other case, Angular renders without a value.

Review the condition on the parent. What is the initial value of `selectedResto` after unwrapping with `async`?

```
  <div *ngIf='selectedResto | async' class='selected-resto'>
```

**Comment by simonh1000** [comment]
selectedResto starts as null, but I don't get the problem without the delay, which makes sense as the child is only rendered when the parent `*ngIf` is true. That ought also to be the case with the delay - selectedResto is null, a click takes place, and 500ms later selectedResto is not null. To my mind something extra is happening during the delay where selectedResto is becoming truthy but without any of its object fields being set

**Comment by cwmrowe** [comment]
@simonh1000 I'm not sure exactly what's causing this issue, but you could try using `startWith` to ensure that the value is `null` before the first true value is emitted.

```
this.selectedResto = this.store.select(state => state.selectedResto[0]).delay(500).startWith(null);
```

For my own sanity I just created this example to prove that it should work as you want.
https://jsbin.com/podixahayi/edit?html,js,console

**Comment by simonh1000** [comment]
OK, thanks, I think I am beginning to to find the real bug, which is because I need to be more careful in handling the different observer events when they are not synchronous, and am going to close for the time being
