### ISSUE TITLE
Failed to import usePreMiddleware, usePostMiddleware from '@ngrx/store'

### ISSUE THREAD

**Issue by dimaShin** [ngrx/store#238]
Hi guys.

In your  [Comprehensive Introduction to @ngrx/store](https://gist.github.com/btroncone/a6e4347326749f938510) examples you import usePreMiddleware, usePostMiddleware directly from @ngrx/store. But they are not there any more as for "@ngrx/store": "2.2.1".

**Comment by littleStudent** [comment]
as stated at the top `Update: Non-middleware examples have been updated to ngrx/store v2. More coming soon!`
the middleware examples are not updated till now. the concept got dropped for meta-reducers

https://github.com/ngrx/store#migrating-from-store-v1x

**Comment by dimaShin** [comment]
@littleStudent Thanx. Probably I should be more inspective. Creating middleware switched to meta-reducers, it's clear. But how can I implement such reducers with ng2 DI dependencies?

**Comment by michaeljota** [comment]
@dimaShin this is unrelated to your question, I'm doing the same introduction. Were you able to run it? I'm trying to run it but I'm having troubles. I'm writing in TypeScript and using lastes Angular and ngrx/Store. Did you wrote in plain JS?

**Comment by dimaShin** [comment]
@michaeljota I'm using typeScript too

**Comment by michaeljota** [comment]
Did you follow the example as is? It's missing types, like, everywhere, even if it is indeed using TS.

**Comment by michaeljota** [comment]
Can you join glitter for quick chat?

**Comment by brandonroberts** [comment]
Closing as outdated
