### ISSUE TITLE
How would I load multiple reducers in app.module?

### ISSUE THREAD

**Issue by cloudscape-germany** [ngrx/store#241]
How would I load multiple reducers in app.module?

```
   providers: [
        StoreModule.provideStore({authorization, goals, currentGoal, user, currentPurchase, settings, navInterrupts}),
        {
            ....
        },
```

Each has his own reducer, too. (named the same)

**Comment by KwintenP** [comment]
You can pass an object to the `provideStore`method that looks like this:

``` typescript
let rootReducer = {
    authorization: authorizationReducer,
    goals: goalsReducer, 
    currentGoal: currentGoalReducer,
   ...
}

StoreModule.provideStore(rootReducer);
```

Internally, NGRX/store will call the combineReducers method to create a meta-reducer which calls the reducers with the correct state slice.

**Comment by cloudscape-germany** [comment]
Thanks for this extraordinary fast reply, @KwintenP ! 

I am doing now:

```
    providers: [
        StoreModule.provideStore({authorization: authorization}),
```

but get: 

<img width="1177" alt="bildschirmfoto 2016-10-04 um 17 18 06" src="https://cloud.githubusercontent.com/assets/418352/19080337/0519da56-8a57-11e6-8509-618cca79cfe2.png">

**Comment by fxck** [comment]
What version of store are you using, isn't it outdated by any chance? 

```
{authorization: authorization}
```

is literally the same as 

```
{authorization}
```

in typescript, so that's probably not the problem.

**Comment by cloudscape-germany** [comment]
+1   

Using latest version. Problem was I put it into `providers` key in `ngModule` and not `imports`, this is working now:

```
imports: [
        StoreModule.provideStore(rootReducer)
],
```

**Comment by NJKruczek** [comment]
I moved my provideStore code to a separate file.

```
import {ModuleWithProviders}  from '@angular/core';
import {StoreModule} from '@ngrx/store';
import {authStateReducer} from "./states/auth-state/auth-state.reducer";
import {navStateReducer} from "./states/nav-state/nav-state.reducer";

const appReducers: any = {
    authState: authStateReducer,
    navState: navStateReducer
};

const appInitialState: any = {

};

export const StateStore: ModuleWithProviders = StoreModule.provideStore(appReducers, appInitialState);
```

Then imported StateStore in app.module.ts.

I got the idea from how Angular 2 has their routing set up. All the routing code is in its own file, then you export the end result and use that inside app.module.ts.

**Comment by cloudscape-germany** [comment]
@Ok, thanks for this. I tried above but getting same errors, but in `StateStore` now.

Could you explain what is inside initial state? 
And could you please show how you use this in app.module ? 
And could you show one of your Reducer Source file? 

Thanks a million in advance!

**Comment by mikkelrd** [comment]
Looks to me like initial state is just the initial shape of the entire state, i.e. `{}` or `[]`, etc. At least that is what worked for me (designating an initial state of `{}`). Spent all day today tracking this down. Would love to see it added to the README!

**Comment by mikkelrd** [comment]
Well, it almost worked. Does each child store need to use its own reducer function? I have multiple models that need to be in separate child stores so their ids don't overwrite each other, but they all have the same reducer functionality. Do I use the same function but different action types?

**Comment by mikkelrd** [comment]
Okay, in `app.module.ts`, I've got:

```
...
imports: [
  StoreModule.provideStore({
    Book: apiReducer,
    Author: apiReducer,
  }, {
    Book: {},
    Author: {},
  }),
...
]
...
```

and `apiReducer.ts` looks like this:

```
...
export const addOrUpdate = 'ADD_OR_UPDATE';
export const destroy = 'DESTROY';

export const apiReducer: ActionReducer<any> =
(state: {} = {}, action: Action) => {
  switch (action.type) {
    case addOrUpdate:
      return Object.assign({}, state, action.payload);

    case destroy:
      let newState = Object.assign({}, state);
      delete newState[action.payload.id];
      return newState;

    default:
      return state;
  }
};
```

And in a component, I do this:

```
  ...
  constructor (private store: Store<{}>) {
    this.store.dispatch({
      type: addOrUpdate,
      payload: {
        21: {
          id: 21,
          title: 'The Hobbit',
          author: 19,
        },
        34: {
          id: 34,
          title: 'The Fellowship of the Ring',
          author: 19,
        },
      }
    });

    this.store.select('Author').subscribe(authorStore => {
      console.log(authorStore);
    });
  }
  ...
```

I'm not surprised that `authorStore` is just the whole store--which contains the two book objects previously dispatched. I've search all the intros and examples and I cannot find any examples that show registering multiple reducer stores, much less how to dispatch to the correct store. @robwormald, @MikeRyan52, @btroncone: What am I missing?

**Comment by mikkelrd** [comment]
Got it! It's the action types that are used to match up stores/reducers, right? Sorry about the conversation with myself. I hope it benefits others, because like I said this is not readily apparent in the intro docs or examples. Although it's been kind of a pain to figure all the pieces out that I need, I think I'm going to love reactive redux with angular2. Thank you!

**Comment by MikeRyanDev** [comment]
Seems like this has been resolved. Please reopen and leave a comment if it is not.
