### ISSUE TITLE
Proper Animation Handling (void => *)

### ISSUE THREAD

**Issue by schnz** [ngrx/store#243]
First: Sorry for opening an issue about this. This is no bug report, but a question about animations. I can't think of a good place to ask it.

I am currently making some hands-on experiments with ngrx/store and wondered if it is possible to handle `void => *` animations properly.

Example Component:

``` typescript
@Component({
  selector: 'my-component',
  template: `
    <input #box type="checkbox" (change)="onChange(box.checked)"> Auto-Update
    <br>
    <table class="table table-hover">
      <tbody>
        <tr *ngFor="let entry of (entries$ | async)"
            [@flyInOut]="'in'">
          <td>{{ entry.date | date:'dd.MM @HH:mm' }}</td>
          <td>{{ entry.prop1 }}</td>
          <td>{{ entry.prop2 }}</td>
        </tr>
      </tbody>
    </table>
  `,
  animations: [
    trigger('flyInOut', [
      state('in', style({
        transform: 'translateX(0%)'
      })),

      transition('void => *', [
        style({ transform: 'translateX(-100%)' }),
        animate('3s 3s ease-in')
      ]),

      transition('* => void', [
        animate('3s ease-out', style({
          transform: 'translateX(100%)'
        }))
      ])
    ])
  ]
})
export class MyComponent implements OnInit {
  entries$: Observable<Entries>;

  constructor(private store: Store<any>) {}

  ngOnInit(): void {
    // Some @Effects() will take care of populating the store
    this.store.dispatch({ type: ENTRIES_LOAD });
    this.entries$ = this.store.select<State>('slice')
      .map(slice => slice.entries);
  }

  onChange(autoUpdate: boolean): void {
    // Again, some @Effects() ensure to auto update the store
    this.store.dispatch({ type: AUTO_UPDATE, payload: autoUpdate });
  }
}
```

In the example above, the component utilizes the store to display a table with several rows. The store is updated in regular intervals and new entries are added to it. I wish to visually highlight newly added entries by animating them via `void => *`.
Because reducers work on immutable objects, ngFor has problems to recognize "newly" inserted entries in the set of all entries.
This is an excerpt from the ngFor documentation page (https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html)

> Angular uses object identity to track insertions and deletions within the iterator and reproduce those changes in the DOM. This has important implications for animations and any stateful controls (such as <input> elements which accept user input) that are present. Inserted rows can be animated in, deleted rows can be animated out, and unchanged rows retain any unsaved state such as user input.

Because reducers act as idempotent functions, the object reference is effectively changing each time a  new state is calculated. As stated in the documentation this leads to a complete exchange of all the elements from the DOM (instead of only the affected ones).

I know that all the above is by design. Still, I would like to know if there is any way or workarround to deal with such a scenario

P.S.: I already tried to use the trackBy option as follows, but with no luck:
`<tr *ngFor="let entry of (playlist$ | async);trackBy:entry?.id" [@flyInOut]="'in'">`

**Comment by tomwanzek** [comment]
While it is beyond my scope to comment on the animation related aspect itself, your **ngFor** will likely need to use `trackBy: trackingFn` in conjunction with a unique identifier (e.g. a unique id within the items you are iterating over).

There are a couple of related issues (immutables v ngFor) in the angular repo (see [10182](https://github.com/angular/angular/issues/10182) and [11727](https://github.com/angular/angular/issues/11727))

I tripped over a similar issue yesterday and built from the comments in the referenced issues (albeit not animations-related).

So, maybe this helps.

**Comment by schnz** [comment]
Thanks alot @tomwanzek! I didn't expected such a fast answer.
You are indeed right about the tracking function. It works flawlessly when using `trackBy: trackingFn`. I tried `trackBy:entry?.id` before which didn't worked. I hope the inline definition of trackBy will become possible soon.

Also thanks for the related issues.

**Comment by tomwanzek** [comment]
No worries, the related issues are the ones where I found the answer. So credit goes to those named there. Glad it worked!

**Comment by berndartmueller** [comment]
@Coksnuss I'm also facing the same problem, can you post your code/plunkr where you made it work? Thanks! :)

**Comment by schnz** [comment]
@berndartmueller It is as simple as adding the trackBy instruction to ngFor and add the corrseponding method to the component:

Add trackBy: https://gist.github.com/Coksnuss/f97bbd79629bc542f80941dec0b97780#file-playlist-component-ts-L8
Add function: https://gist.github.com/Coksnuss/f97bbd79629bc542f80941dec0b97780#file-playlist-component-ts-L53

Works, but its just too verbose in my opinion
