### ISSUE TITLE
Question: Does this work with redux DevTools?

### ISSUE THREAD

**Issue by crh225** [ngrx/store#245]
https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?utm_source=chrome-app-launcher-info-dialog

**Comment by abdulhaq-e** [comment]
Absolutely. See the [example-app](https://github.com/ngrx/example-app/). The integration is done using [store-devtools](https://github.com/ngrx/store-devtools).
