### ISSUE TITLE
Property does not exist on type typeof app.module.

### ISSUE THREAD

**Issue by cloudscape-germany** [ngrx/store#247]
```
import { StoreModule } from "@ngrx/store";
import { currentPurchase } from "../shared/index";

@NgModule({
 imports: [
        IonicModule.forRoot(MyApp, {}),
        HttpModule,
        StoreModule.provideStore({currentPurchase})
    ]
..
```

I am getting `Property currentPurchase' does not exist on type typeof app.module.` The imported reducer looks like this:

```
import { ActionReducer, Action } from "@ngrx/store";
import { ActionType } from "./action-type";
import { PurchaseModel } from "../purchase/purchase.model";

export const currentPurchase: ActionReducer<PurchaseModel> = (state:PurchaseModel = new PurchaseModel(), action:Action) => {

    switch (action.type) {

        case ActionType.SET_PURCHASE:
            return (action.payload !== null) ? action.payload : new PurchaseModel();
        case ActionType.UPDATE_PURCHASE:
            return Object.assign({}, state, action.payload);
        default:
            return state;
    }
};
```

Also: 

<img width="459" alt="bildschirmfoto 2016-10-10 um 16 56 31" src="https://cloud.githubusercontent.com/assets/418352/19240399/8f19ba98-8f0a-11e6-9dc0-6fe73f6b1923.png">

Any help is appreciated.

**Comment by wizardnet972** [comment]
Property currentPurchase' does not exist on type typeof app.module

the reducer and module seems ok.
maybe the init of PurchaseModel is got an error? or you can give the full error from the console?

**Object.assign** should come from core-js. see if you have latest core-js package installed.

was helpful?

**Comment by joaogarin** [comment]
I get something similar to the first one using Angular with AOT mode.

**Comment by jeroennoten** [comment]
@nottinhill How did you solve this? I have the same problem.

**Comment by MarkPieszak** [comment]
What version of TS are you using? You just want to include es6 libs in your tsconfig, I believe that'll take care of it! @jeroennoten

**Comment by jeroennoten** [comment]
I found that replacing (following the example above) `{currentPurchase}` with `{currentPurchase: currentPurchase}` in combination with using a function declaration (`export function currentPurchase(...`) instead of a function expression assigned to a constant (`export const currentPurchase...`) does the job.

I don't see why my first solution with object shorthand and function expression does not work, though.

**Comment by jeroennoten** [comment]
BTW, I have `es2015` included in my tsconfig.

**Comment by MarkPieszak** [comment]
I typically have the below, does that help any? Close and reopen that file. What version of TS?

     "lib": [ "es6", "dom" ],

**Comment by jeroennoten** [comment]
Upgrading to the latest version of typescript solved it, thanks!

**Comment by cloudscape-germany** [comment]
My apologies fellow engineers, we moved so fast in the project, I forgot the solution. We already released. I this case I think we wrote root reducer and combined in seperate file and used that export in app.module. (being an AoT Ionic project)
