### ISSUE TITLE
Advice needed: How to handle errors in store dispatches and loading indicators

### ISSUE THREAD

**Issue by twmobius** [ngrx/store#248]
First off let me say thank you for a job well done. I am really new to the whole redux state management but it feels really fun using it :) 

I need however some advice on how to make better use of ngrx/store. (If I shouldn't use the github issues and I should ask somewhere else please point me to where)

My questions are:
- how should we handle errors that might occur when dispatching actions to the store, 
- and how can we toggle loading indicators to show and hide when we are waiting for the observable to get populated with the new state

Thanks again

**Comment by fxck** [comment]
Look into ngrx/effects.. basically you dispatch action `whatever_request`, use it to toggle `loading` on your slice of your `whatever` state(in a reducer for that slice), then you catch the same action in an effect, do your async thing, map the result to a `whatever_success` action, along with a payload from your async thing, and use it to toggle loading to false and fill in the data in a reducer.

As for errors, use catch operator in the above mentioned effect and map it to `whatever_error` action and use your reducer to set `errors` on your slice of the state(or create a special reducer to gather all errors occurred across your state).

**Comment by twmobius** [comment]
I get it now! Thank you very much!
