### ISSUE TITLE
Question on possible hot vs cold observable issue

### ISSUE THREAD

**Issue by sstorie** [ngrx/store#25]
Thanks so much for putting this code out there. I'm just starting to work with Angular 2, and have been using Redux in an angular 1 app for a few months now with good results. I've been working hard to understand how to leverage observables and this is helping things "click" in my brain :)

Now, my question is related to an issue I have when my app is first rendered. I have a simple meal planning app I'm building, and following the design of [your example app](https://github.com/ngrx/angular2-store-example) pretty closely (sans normalizr and immutable.js to keep things simple). So rather than users I have recipes, but same general structure is used. 

My issue right now is my root component kicks off the loading of recipes from an API:

```
@Component({
    selector: 'meal-planning-app',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <h3>Meal Planning</h3>
        <nav>
            <a [routerLink]="['Recipes']">Recipes</a>
        </nav>
        <router-outlet></router-outlet>
    `,
    providers: [RecipeService, FoodService, UomService, ROUTER_PROVIDERS],
    directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
        { path: '/recipes/...', name: 'Recipes', component: RecipesRouter }
])
export class AppComponent implements OnInit {

    constructor(
        private recipeService: RecipeService,
        private foodService: FoodService,
        private uomService: UomService
    ) {}

    ngOnInit() {
        this.recipeService.loadRecipes();
        this.foodService.loadFoods();
        this.uomService.loadUoms();
    }
}
```

The recipe router is pretty simple at the moment, and contains a single route for a recipe list container:

```
@Component({
    template: `
        <router-outlet></router-outlet>
    `,
    directives: [ROUTER_DIRECTIVES],
    providers: [RecipeService]
})
@RouteConfig([
        { path: '/', name: 'Recipes', component: RecipeListContainer, useAsDefault: true }
    ])
export class RecipesRouter { }
```

Finally here's the recipe list container class:

```
@Component({
    selector: "recipe-list-container",
    template: `
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--12-col">
                <recipe-list
                    [recipes] = "recipeService.recipes$ | async"
                    [loading] = "recipeService.loading$ | async"
                    [foods] = "foodService.foods$ | async"
                    (saveRecipe)="recipeService.saveRecipe($event)"
                    (deleteRecipe)="recipeService.deleteRecipe($event)"
                    (reloadRecipes) = "recipeService.reloadRecipes()">
                </recipe-list>
            </div>
        </div>
    `,
    directives: [RecipeList]
})
export class RecipeListContainer {
    constructor(
        private recipeService: RecipeService,
        private foodService: FoodService
    ) { }
}
```

Lastly, here's my recipe service class:

```
@Injectable()
export class RecipeService {
    // The public API for this service is a couple of observable 
    //  streams
    //
    recipes$: Observable<Recipe[]>;
    loading$: Observable<Boolean>;

    // This is creating a new observable stream for use within this
    //    class only.
    //
    private actions$ = new BehaviorSubject<Action>({ type: null, payload: null });

    constructor(
        private store: Store<MealPlanningState>,
        api: ApiService
    ) {
        // subscribe to changes in the state we care about
        //
        const store$ = this.store.select<MealPlanningState>("mealPlanningReducer");

        this.recipes$ = store$.map(data => data.recipes);
        this.loading$ = store$.map(data => data.recipesLoading);

        // This is creating a new observable stream from our starting
        //  (internal) actions stream. This is basically mapping the
        //  starting action into a couple because of the async api
        //  call required (ala, redux-promise)
        //
        let loadStream = this.actions$
            // Filter to only the internal action we care about
            //
            .filter(action => action.type === LOAD_RECIPES)
            //
            // Mmit the "pending" action as a side effect within this observable
            //
            .do(() => store.dispatch({ type: LOAD_RECIPES_PENDING }))
            //
            // Now take the original action and use mergeMap to get the 
            //  observable from our api representing the back-end processing
            //  and then map the results from that into a new action that
            //  contains the data returned from the API
            //
            .mergeMap(action => api.loadRecipes(),
                (action: Action, recipes: Recipe[]) => ({ type: LOAD_RECIPES_FULFILLED, payload: recipes })
            );

        let saveStream = this.actions$
            .filter(action => action.type === SAVE_RECIPE)
            .do(() => store.dispatch({ type: SAVE_RECIPE_PENDING }))
            .mergeMap(action => api.saveRecipe(action.payload as Recipe),
                (action: Action, recipe: Recipe) => ({ type: SAVE_RECIPE_FULFILLED, payload: recipe })
            );


        let deleteStream = this.actions$
            .filter(action => action.type === DELETE_RECIPE && !action.payload.deleting)
            .do(action => store.dispatch({ type: DELETE_RECIPE_PENDING, payload: action.payload }))
            .mergeMap(action => api.deleteRecipe(action.payload as number),
                (action) => ({ type: DELETE_RECIPE_FULFILLED, payload: action.payload })
            );


        // Now we need to combine all these internal observers into a single
        //  observable (using merge), and pass each action emitted to the 
        //  store (via its dispatch() method)
        //
        Observable
            .merge(loadStream, saveStream, deleteStream)
            .subscribe((action: Action) => store.dispatch(action));
    }

    loadRecipes(): void {
        // Emit an event on the internal action$ stream to load the recipes
        //
        this.actions$.next({ type: LOAD_RECIPES });
    }

    reloadRecipes(): void {
        this.store.dispatch({ type: LOAD_RECIPES_FULFILLED, payload: [] });
        this.loadRecipes();
    }

    saveRecipe(recipe: Recipe) {
        this.actions$.next({ type: SAVE_RECIPE, payload: recipe });
    }

    deleteRecipe(recipeId: number) {
        this.actions$.next({ type: DELETE_RECIPE, payload: recipeId });
    }
}
```

Now I can see that when my app launches the services do in fact load the state tree with this data, but if I load the browser at the route for the recipe list directly (e.g., myapp.com/mealplanning/recipes) the recipe list doesn't actually render them. I have to click on something in my app for it to render things, so at the moment I have a refresh button I added to click and get them to render. If I start at the top-level route for this app (e.g., myapp.com/mealplanning) and click to navigate to the recipe container route they are displayed correctly.

It's kind of like when the recipe container is created, and it subscribes to the recipe observable, it doesn't immediately get the latest value from the observable. Only when I cause an event that angular recognizes does it trigger the update and render the recipes.

I've been looking through the example code, but I can't see what might cause this to happen. I'm curious if there's anything you ran into while building this that would be helpful.

Thanks again.

**Comment by sstorie** [comment]
Arg, of course the moment I post this [the duck told me the answer](http://blog.codinghorror.com/rubber-duck-problem-solving/) :)

I was missing the `changeDetection: ChangeDetectionStrategy.OnPush` specification on my recipe list container component. When I update it to be this it works as expected:

```
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,  // THIS WAS MISSING!
    template: `
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--12-col">
                <recipe-list
                    [recipes] = "recipeService.recipes$ | async"
                    [loading] = "recipeService.loading$ | async"
                    [foods] = "foodService.foods$ | async"
                    (saveRecipe)="recipeService.saveRecipe($event)"
                    (deleteRecipe)="recipeService.deleteRecipe($event)"
                    (reloadRecipes) = "recipeService.reloadRecipes()">
                </recipe-list>
            </div>
        </div>
    `,
    directives: [RecipeList]
})
export class RecipeListContainer {
    constructor(
        private recipeService: RecipeService,
        private foodService: FoodService
    ) { }
}
```

**Comment by fxck** [comment]
Feel free to contribute to the example with whatever you come up with while trying to actually use it(folder structure, naming, anything).. none really had time to work on it for past couple of weeks.

**Comment by sstorie** [comment]
Will do. At the moment my gut tells me there's some opportunity to reduce the "boilerplate" code within the services to handle async api calls, but I need some more time with rxjs to understand what's possible. For redux there's [redux-promise-middleware](https://github.com/pburtchaell/redux-promise-middleware), which works kinda slick for automatically splitting an promise-based action into multiple actions for the reducer with optimistic updates. I'm wondering what it would take to use a similar pattern around observables that make an async call internally.

Thanks again for sharing the code...it's incredibly helpful!

**Comment by sstorie** [comment]
I spoke too soon, and I am still experiencing my original issue. I think it's related to the problems discussed here:

https://github.com/angular/angular/issues/5992

In my case the store is properly updating the state tree, but when my RecipeListContainer component is created it doesn't get the latest value from the recipeService.recipe$ observable. Only when I trigger some other store update does the current value flow through to my component.

I'll keep digging, but I can't tell if I'm doing something wrong or if I'm just misunderstanding how these Observables work when components are created/destroyed on the fly.

**Comment by sstorie** [comment]
Ok, I'm really not trying to spam anyone subscribed to this post, but I did finally figure out how to get this working. My problem was ultimately that I had the `OnPush` change detection strategy defined on my root component. I don't fully understand how that creates a problem, but when I removed that (but kept the `OnPush` strategy on all child components) my data updates as expected.
