### ISSUE TITLE
Replacing state

### ISSUE THREAD

**Issue by tjoskar** [ngrx/store#255]
Hi,

Is it possible to replace the state of a `Store`? When I look at the source code it looks like we can [replace the reducers but not the sate](https://github.com/ngrx/store/blob/6a526aef35cbb6340dc011201e56c7d790132281/spec/store.spec.ts#L148-L168)? Is that correct? 

It would be nice to replace the whole state for debugging purpose. Use case; when a user encounter an error he/she can submit the whole state which I then can load in my develop environment to reproduce the error.

**Comment by fxck** [comment]
You can pass the initial state as the second param of the `provideStore` function.

https://github.com/ngrx/store/blob/master/src/ng2.ts#L44

**Comment by tjoskar** [comment]
@fxck, sure but then you have to "reboot" the application, right? I want to replace the state on the fly. Like:

``` javascript
const myNewState = {
  ...
};
store.replaceState(myNewState)
```

**Comment by fxck** [comment]
If it's for debugging purposes, why does it matter?

If you want to do it on the fly, you can use redux dev tools, which I think support pasting in an object, or create your own meta reducer, similar to how [this](http://stackoverflow.com/a/39323601/301596) works.

**Comment by tjoskar** [comment]
> If it's for debugging purposes, why does it matter?

If I use the initial state param, I need to have some debug logic in the bootstrap, which feels poorly.

``` javascript
if (debug && someDebugStateExist()) {
  StoreModule.provideStore(myReducers, getDebugStateFromLocalstorage());
} else {
  StoreModule.provideStore(myReducers, normalInitState);
}
```

And it would be nice to include an array of state and have the ability to jump between them:

``` javascript
debugStates = [ ... ];

onNextStateButtonClick() {
  store.replaceState(debugStates[nextStateIndex]);
}
```

> If you want to do it on the fly, you can use redux dev tools, which I think support pasting in an object ...

I have tried to use `redux dev tools` with [Redux DevTools](https://github.com/zalmoxisus/redux-devtools-extension) but replacing a state does not seem to work (I have created an issue on the matter, https://github.com/ngrx/store-devtools/issues/31).

> ... or create your own meta reducer, similar to how this works.

Thanks! I will take a look at it.

– Just to clarify, I wanted to know if there is a way to replace the state on the fly (like we can replace reducers on the fly) and if not; is it something we want to have?

**Comment by tjoskar** [comment]
@fxck, the "meta reducer" solved my problem. Thanks.
