### ISSUE TITLE
Ngrx store with Reactive Forms

### ISSUE THREAD

**Issue by jculverwell** [ngrx/store#257]
I am trying to get my head around how to best setup reactive forms with NgRX store.  I have created a service (NoteLinkingSettingsService) which simply exposes an Observable called noteLinkingSettings$ which calls the store.select method as below:

```
this.noteLinkingSettings$ = store.select<INoteLinkingSettings>( state =>  state.notelinkingsettings);
```

My question is how do I best initialize a Reactive form with the values from my service.  My first attempt is below.  I was thinking of subscribing to the first event in the noteLinkingSettings$ observable build the reactive from there.

Then I was looking to subscribe to any valueChanges and pass these back to service where I would update them in the db.

The problem I am facing is  this.notelinkingForm is undefined at the point the code reaches 

```
this.notelinkingForm.valuesChanges$
```

Would welcome any recommendations with the best way to setup a reactive form which gets it's values from ngRX store.

```
export class NotelinkingsettingsComponent implements OnInit {
 notelinkingForm: FormGroup;

  constructor(private formBuilder: FormBuilder, private notelinkingsettings: NoteLinkingSettingsService) { }

  ngOnInit() {

    this.notelinkingsettings.noteLinkingSettings$.first().subscribe(settings => {
       this.notelinkingForm = this.formBuilder.group({
        Enabled: [settings.Enabled, Validators.required],
        LinkToPreceeding: [settings.LinkToPreceeding.toString(), Validators.required],
        LinkingTolerance: [settings.LinkingTolerance, Validators.required]
     })

      this.notelinkingForm.valuesChanges$.subscribe(({value})=> {
          this.notelinkingsettings.updateNoteLinkingSettings(this.notelinkingForm.value);
      });
});
```

**Comment by fxck** [comment]
You might want to utilise the concept of smart and dumb components, where smart component injects services, gets data from the store etc and dumb just receives sync data and uses setter to fill in the form.

So in semi-pseudo code it might looks like this 

``` typescript
@Component({
  template: `<dumb-component [form]="form" [data]="data$ | async"></dumb-component>`
})
class SmartComponent {
  public data$ = this._store.let(someSelector$());

  public form = new FormGroup({
   foo: new FormControl(''),
   bar: new FormControl('')
  });

  constructor(private _store: Store<IState>) {}
}

@Component({
  template: `
    <form [formGroup]="form">
      <input type="text" formControlName="foo" />
      <input type="text" formControlName="bar" />
    </form>
  `
})
class DumbComponent {
  @Input()
  public form: FormGroup;

  @Input()
  set data(v) {
    if (v) {
      this.form.patchValue(v);
    }
  };
}
```

**Comment by jculverwell** [comment]
Thank you for your suggestion.  Unfortunately I am using the router-outlet to init my component.  Did you have any thoughts on how to best do this in that scenario.

**Comment by fxck** [comment]
It doesn't matter if the smart component is the one you use for your route.. where is no such thing as router-outlet, it's always attached to some component / class.. so use that one as the smart component which injects store, creates form and passes it down to a dumb component to render and fill in.

**Comment by jculverwell** [comment]
Hi, Thank you for your response again.  Apologies but I must admit I am having some trouble understanding how this would hang together.

Taking your smart componet but modifying the template to use a router-outlet it would look like this:

```
@Component({
  template: `<router-outlet [form]="form" [data]="data$ | async"></router-outlet>`
})
class SmartComponent {
  public data$ = this._store.let(someSelector$());

  public form = new FormGroup({
   foo: new FormControl(''),
   bar: new FormControl('')
  });

  constructor(private _store: Store<IState>) {}
}

@Component({
  template: `
    <form [formGroup]="form">
      <input type="text" formControlName="foo" />
      <input type="text" formControlName="bar" />
    </form>
  `
})
class DumbComponent {
  @Input()
  public form: FormGroup;

  @Input()
  set data(v) {
    if (v) {
      this.form.patchValue(v);
    }
  };
}
```

I'm not sure this would work even it if does -  doesn't it make the assumption that any component would have the same inputs?

I am sure this is not what you mean but I am struggling to see how I would pass in the inputs.

Sorry to be a pain :)

**Comment by jculverwell** [comment]
Thinking out aloud I guess I could make this work if I had this structure:

Component Hosting a router-outlet
SmartComponent for getting values out of the store abd passing them into the Dumpcomponent
DumpComponent which represents the form

**Comment by fxck** [comment]
As far as I know, router-outlet itself is just a "slot" for a component. So say you have your root component, and it's template would be only `router-outlet`, you'd then perhaps have a router with path `/login`, which would activate component `LoginComponent`, so **that** one will be the one you'll use to inject store and select data, it would have a template containing the "dumb" component, `<dumb-component [data]="data$ | async" [form]="form"></dumb-component>`... what you are showing me is use the `root` component to get data, I'm saying use the one that will be inserted into the router slot.

**Comment by jculverwell** [comment]
Thanks for working this through with me I understand now.  Really appreciate the time you've taken to go through this.

**Comment by tomwanzek** [comment]
I am working with a similar structure to the one proposed by @fxck. The setup has indeed a smart component in a router-outlet, which injects the store (it is the one selecting from the store and dispatching actions to the store (possibly triggering side effects using ngrx/effects).

The alternative approach is that the "dumb" component contains the form completely. In this setup, the form may receive initializing values through inputs.
These data would be observables from the store (selected and mapped as necessary) which are fed into the form component using the `async` pipe. In turn the dumb component emits output events (i.p. `onSubmit`) which are handled by the smart component, e.g. by dispatching events to the store.

``` ts
<not-so-smart-form 
   [initialValues]="initialValues$ | async" 
   (onSubmit)="handleSubmit($event)">
</not-so-smart-form>
```

The reactive form control rests completely inside the `not-so-smart-form` Component.

**Comment by fxck** [comment]
I recently moved away from having form definition inside the "dumb" component, mostly because when you need to use async validation, you will need to inject services using async and stuff. And it's pretty much very-smart-kind-of-component when you do that. Also having the definition inside the smart component helps reusability, since you can easily use the same form structure for different validation rules.

**Comment by tomwanzek** [comment]
@fxck very valid consideration re: async validation.

I guess the reason, I initially landed on the componentized form, is that the router-outlet had different states, only one of which would have the form displayed.

Might play your approach through, to see what it implies for my use case... Food for thought as always :smile:

**Comment by sky-coding** [comment]
I've avoided using Reactive Forms, because when using Reactive Forms, the source of truth for your data (and state) is within FormGroups. And since you cannot put a mutable FormGroup into Store, it means your data/state is being stored and mutated outside of Store, which defeats the purpose of using ngrx/store.

Because of this I've been using Template-Driven Forms, which allows you to store and reduce your data within Store, and add validation as a display-only concern.

**Comment by jculverwell** [comment]
Hmmm, that's interesting, thanks for your advice.  I was kind of going down the reactive forms route as I got the impression this is what the Angular 2 team were favoring. 

If anyone else reads this it would be interesting to know whether you've gone down the template driven approach or reactive forms.

**Comment by okhomenko** [comment]
@jculverwell Initially I leaned towards ReactiveForms, because I thought it is the way for consuming `.valueChanges` and `.statusChanges` streams. I implement autosave forms, and I need to watch all changes on forms and if form is valid - store it with ngrx/store.

But then I have watched screencast from @johnlindquist on EggHead and realized that I can mix Template Forms and streams from Reactive Forms. https://egghead.io/lessons/angular-2-use-rxjs-streams-with-angular-2-forms

Here is final plunker https://embed.plnkr.co/9aNuw6DG9VM4X8vUtkAa?show=app%2Fapp.components.ts,preview

As you can see from this plunker - all inputs are defined as template forms, but then in ngAfterViewInit there is subscription to `valueChanges` stream.

Not sure if it is relevant to your case.

**Comment by jculverwell** [comment]
Thank you.  That is really helpful,  I'm also using an 'autosave' approach for some of my forms.  I think I am pretty much sorted now with the forms approach.  The latest issue I am tripping over is how best to handle errors from services as I describe here https://github.com/ngrx/store/issues/261  .  Welcome any thoughts on this.

**Comment by MikeRyanDev** [comment]
Seems like this has been resolved. Please reopen and leave a comment if it is not.

@jculverwell, feel free to open another issue for handling errors from services if need be.

**Comment by born2net** [comment]
Hi guys,
I am just wondering what is now (Feb 2017) the recommenced way to connect a Form to an ngrx store stream, with least amount of code, is ```this.form.patchValue(v);``` the way?

regards

Sean

**Comment by fxck** [comment]
https://github.com/ngrx/core/issues/12

**Comment by born2net** [comment]
thanks checking and will reply on that post
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by born2net** [comment]
found this great way to auto connect store to form reactively:
https://netbasal.com/connect-angular-forms-to-ngrx-store-c495d17e129
really cool!
