### ISSUE TITLE
Thoughts on error handling

### ISSUE THREAD

**Issue by jculverwell** [ngrx/store#261]
I have a component which gets it's data from a service.  When I want to update the data I pass it into a function on the service called updateNoteLinkingSettings which does a http post and if all goes well if then updates the NgRX store.

My question is what it the best way to notify the component if anything goes wrong with the update.  Off the top of my head I can think of a couple of approaches.  

1) I could create an additional observable on the NoteLinkingSettingsService called something like errors$.  Then I could catch errors in the http post and push them into this observable.  The component would simply subscribe to this observable.

2) I could get the updateNoteLinkingSettings function to return an observable with some indication whether it passed.  If it failed I could do something the Observable.throw and then subscribe and catch this on the call to updateNoteLinkingSettings.

3)  I could create a store/reducers specifically for errors.

Welcome any thoughts on this.

``` javascript
export class NotelinkingsettingsComponent {
   formdata$: Observable<INoteLinkingSettings>;
    constructor(private toastr: ToastsManager, private notelinkingservice: NoteLinkingSettingsService) {

    this.formdata$ = this.notelinkingservice.noteLinkingSettings$;
 }

  saveForm(settings: INoteLinkingSettings) {
    this.notelinkingservice.updateNoteLinkingSettings(settings);
  }
}


export class NoteLinkingSettingsService {
    noteLinkingSettings$: Observable<INoteLinkingSettings>;
    constructor(private authHttp: AuthHttp, private store: Store<AppStore>) {
        this.noteLinkingSettings$ = store.select<INoteLinkingSettings>(state => state.notelinkingsettings);
    }

    updateNoteLinkingSettings(notelinkingsettings: INoteLinkingSettings)  {
        this.authHttp.post(`${BASE_URL}`, JSON.stringify(notelinkingsettings), HEADER)
            .subscribe(action => {
                this.store.dispatch({ type: UPDATE_NOTELINKING_SETTINGS, payload: notelinkingsettings });
            }
        );
    }
```

**Comment by jculverwell** [comment]
Still struggling to find decent examples of error handling.  In this example http://onehungrymind.com/build-better-angular-2-application-redux-ngrx/ in the comments the author mentions creating a store just for errors.  I guess this could work - all components could subscribe to this error store and then filter out just the errors specific to them.  Welcome your opinions on this.

**Comment by RyanMcDonald** [comment]
How about subscribing to the observable in the component itself, and handling any errors there?

In your component:

``` javascript
saveForm(settings: INoteLinkingSettings) {
    this.notelinkingservice.updateNoteLinkingSettings(settings)
    .subscribe(
      () => {
        // Success
      },
      (err) => {
        // Handle error
      };
  }
```

And then in your service:

``` javascript
updateNoteLinkingSettings(notelinkingsettings: INoteLinkingSettings)  {
    this.authHttp.post(`${BASE_URL}`, JSON.stringify(notelinkingsettings), HEADER)
      .map(action => {
        this.store.dispatch({ type: UPDATE_NOTELINKING_SETTINGS, payload: notelinkingsettings });
      }
    );
}
```

**Comment by jculverwell** [comment]
Thanks Ryan.  I've gone with your approach.

**Comment by fxck** [comment]
https://github.com/ngrx/store/issues/248

**Comment by orizens** [comment]
hi @jculverwell 
you can add an action which describes the failure and dispatch it to the store, i.e "UPDATE_NOTE_FAILED".
you can integrate ngrx/effects and perhaps organize this flow better.
then, upon failed action, you should design the component to render a proper view or a message.

**Comment by jculverwell** [comment]
Thanks all.  Got lots of ideas now, appreciate your help.
