### ISSUE TITLE
AoT Compilation issue

### ISSUE THREAD

**Issue by splacentino** [ngrx/store#262]
Hello.

I am using ngrx/store in my Ionic2 application. The application is build on platform using ngc with AoT compilation.

If I declare my store as this, ngc won't compile because it is dynamic.

``` js
  imports: [
    StoreModule.provideStore({
      leads: leadsReducer,
      activeLead: leadReducer,
      points: pointReducer,
      credentials: credentialReducer,
      meta: metaReducer
    })
 ]
```

So I create an `index.ts` file on my reducers folder to export a function:

``` js
export function appStore(): any {
  return compose(combineReducers)({
      leads: leadsReducer,
      activeLead: leadReducer,
      points: pointReducer,
      credentials: credentialReducer,
      meta: metaReducer
  });
};
```

And then import it in my `app.module.ts`:

``` js
  imports: [
    IonicModule.forRoot(MyApp),
    StoreModule.provideStore(appStore)
  ],
```

This way I can compile it but if I serve it locally (`ionic serve`) the store is not working:

``` js
constructor(public navCtrl: NavController, private store: Store<any>) {
  store.select('meta').subscribe(x => console.log(x)); 
  // log: Undefined 
 // even if 'meta' has a default value
}
```

If followed this https://github.com/ngrx/store/pull/208/files?diff=split&short_path=04c6e90 without any success.

Any idea ? Thank you

**Comment by splacentino** [comment]
Fixed.

I forgot to turn lambda as function.

Thanks

**Comment by gmorel** [comment]
Hi @splacentino,

I get the same issue.
```js
constructor(public navCtrl: NavController, private store: Store<any>) {
  store.select('meta').subscribe(x => console.log(x)); 
  // log: Undefined 
 // even if 'meta' has a default value
}
```

What do you mean by 
> I forgot to turn lambda as function.

?

Cheers

**Comment by splacentino** [comment]
@gmorel 

The AOT compiler need reference to a function as this:
```js
export function() {}
```

instead of:
```js
const fn = function() {}
export fn
```

If I remember I did
```js
const appStore = () => {}
export appStore
```

Instead of:
```js
export function appStore(): any {
```

But I can't remember..

**Comment by gmorel** [comment]
Thanks :+1:

**Comment by splacentino** [comment]
@gmorel Did it help ?

**Comment by gmorel** [comment]
Yes, all is working now.

Thanks :+1:
