### ISSUE TITLE
Update docs to include advice when dealing with 3rd party components

### ISSUE THREAD

**Issue by brian428** [ngrx/store#264]
I recently started building an app and decided to include ngrx store. Things seemed to be going well until I started introducing third-party components (such as PrimeNG). The main problem seems to be cases where components that I don't have much control over attempt to modify the data passed into them.

Obviously, this violates the immutability of the state data being fed into the components, and I'm not sure what the solution is. One option seems to be to manually clone the state data and feed that into the component instead, but that seems to introduce a lot of redundancy. Going that way, the flow would be:
- Select state out of the Store and map over it to clone it.
- Pass the cloned data into the 3rd party component
- Monitor for changes via events on the 3rd party component and/or my own component
- Dispatch actions into the Store to synchronize the changes back into the state
- Deal with the fact that after the store is updated, the selector will trigger a re-map/re-clone to push the "new" (but not really, from the 3rd party component's perspective) state back into the 3rd party component. 

If a significant number of 3rd party components like this are used, this seems to introduce a lot of overhead that is mostly redundant. The mismatch seems to be due to the fact that many (most?) 3rd party components aren't adhering to the ngrx way of doing things (immutable state).

I'm not sure what the answer is, and I'm concerned because even at this early stage this looks like it will require a lot of extra work to deal with. Which is making me rethink the viability of ngrx Store in my situation. Since it seems like this could be a very common concern, is there any chance the docs or guide could be updated to cover this type of scenario?

**Comment by robwormald** [comment]
Can you provide an example of this? If a component is circumventing stuff like ngModel / Value Accessors, then there's not a whole lot of anything we're going to be able to do about it, and such issues should really get reported to said component vendor...

**Comment by brian428** [comment]
Right, to be clear, this is more centered on visual/layout components than on things like form fields. Take their DataTable component (http://www.primefaces.org/primeng/#/datatable), which implements a number of features that may manipulate bound data (such as sorting, filtering, paging, infinite scrolling, and so on). In my case, the issue I happened to run into first was simply equality checking. In their case, they're adding a temporary flag on objects as they recurse an object tree (https://github.com/primefaces/primeng/blob/31ba269de0c71d7b8a2d9f5a32eccea88c74bf5e/components/dom/domhandler.ts#L301).

I'm sure this could (and probably should) be done in a way that doesn't rely on a temporary "hidden" property, but I point it out simply because it instantly cast light in the problem. Like I said, I just got concerned that immutable data plus 3rd party components could potentially turn into a headache. Mainly because I'm not sure how well immutable data is supported by the wider ecosystem, given that this seems to be a fairly new idea in the Angular 2 space. So I'm trying to wrap my head around the possible problems while I still have time to make some decisions.

**Comment by kylecordes** [comment]
We have been dealing with this by thinking of third-party components based on a pervasive mutable state model as part of the "outside world". That is not such a bad thing, the outside world already includes all the other external resources we talk to, and of course the user. Our applications here are a hybrid between a core portion with managed state, and various ancillary portions with other ways of thinking of the world. Over time, if managed state change and immutability gain more popularity among Angular developers, I expect the need for this will gradually reduce.

(More broadly... we are not at the end of history. Angular (2 at the moment) is in many ways the best platform/library I have used so far, and Store has been greatly helpful in organizing and orchestrating complex application behaviors. Major kudos to everyone involved. But I fully expect some years from now to be talking with fellow developers about how we used to use Angular 2 through Angular 13, and it was great at the time, but we are now getting much better results with FooWhatever 0.7. Maybe the next major disruptive change will be from below, if languages which bake immutability and dataflow in the language level gain major popularity. Or maybe something else entirely.)

**Comment by brian428** [comment]
Thanks, Kyle!

**Comment by rupeshtiwari** [comment]
I found this website where basically it is explained to create wrapper component and intercept methods and emit events and modify state by watching store changes. https://www.pluralsight.com/guides/front-end-javascript/ui-state-management-with-redux-in-angular-4. However, I was thinking this is still redundancy. I wish if ui bootstrap team could publish library which is redux compliant. Which we can use ngrx/store or any redux one way data flow approach.
