### ISSUE TITLE
ngOnInit triggers twice after adding second store

### ISSUE THREAD

**Issue by minuz** [ngrx/store#265]
Hi All, 

I'm not sure if I'm doing something wrong (very likely) or if there's a bug.
https://github.com/angular/angular/issues/6782

This link suggest that something went wrong and that's why is loading twice.
However, debugging the code, on the first run of the ngOnInit, everything runs fine, no exceptions at all. Then the second run will get many errors.

I've been following the pattern implemented on example-app
If I have just one reducer, my code works absolutely fine. The moment I add the second reducer and use the combineReducer, then I start to get this issue.

I'll be very grateful if anyone can point me a direction on how to find what's the issue with this.  

Sample files: 
[tsfiles.zip](https://github.com/ngrx/store/files/565647/tsfiles.zip)

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
