### ISSUE TITLE
store.select() parameter - only string working

### ISSUE THREAD

**Issue by smatthews1999** [ngrx/store#266]
I have a simple app state and reducer...
```
 export interface AppState{
     chatWith: UserModel;
     allUsers: UserModel[];
 }
 const initialState: AppState = {
  chatWith: null,
  allUsers:new Array()
}
export const SET_CHATTINGWITH = 'SET_CHATTINGWITH';
export const SET_USERS = 'SET_USERS';

export const stateReducer: ActionReducer<AppState> = 
    (state=initialState, action: Action) => {
    console.log('stateReducer ',action.type, action.payload);
    switch (action.type) {
        case SET_CHATTINGWITH:
            
            return Object.assign({}, state, {chatWith:action.payload}) ;
        default:
            console.log('reducer set state to ', state);
            return state;
    }
}
```
And trying to subscribe in a component using a store...
```
 constructor(
    private store: Store<AppState>
  ) {
    this.store.select(a=>a.chatWith).subscribe(cw => {
      console.log('subscribe store', cw);
  }
}
```
However the above subscribe will not be called when calling the reducer.
If I change the subscribe to the following...
```
 this.store.select('stateReducer').subscribe(cw => {
      console.log('subscribe store', cw);
```
Then it will work and I will get the whole state from subscribe.  However what I really want is just the one property of state.  Is this not working?  Am I doing this wrong?
Thanks
Sam

**Comment by KwintenP** [comment]
Could you show the rootReducer which u are using to create the store?

**Comment by smatthews1999** [comment]
I have none.  That is my only reducer.

You don't mean @NgModule provider declaration right?

**Comment by KwintenP** [comment]
Somewhere in your code you are doing this (copy from the documentation in the README.md).

``` typescript
@NgModule({
  imports: [
    BrowserModule,
    StoreModule.provideStore({ counter: counterReducer })
  ]
})
```

Can you show that snippet.

**Comment by smatthews1999** [comment]
```
 providers: [ provideStore({stateReducer}) ],    
    bootstrap: [AppComponent]
```

I'm guessing I did that wrong.  Sorry I've been trying out a few implementations and missed that.

**Comment by KwintenP** [comment]
The problem is here, you are basically doing this (if you un-es6 this code):

``` typescript
providers: [
    provideStore({stateReducer: stateReducer})
    ],    
    bootstrap: [AppComponent]
```

This means that the state object in your store will have a single property called 'stateReducer' with the result from that stateReducer.

If you want two properties in your state object, you'll need to define two reducers and define the provideStore method like this:

``` typescript
providers: [
    provideStore(
         {
             chatWith: chatWithReducer,
             allUsers: allUsersReducer
         })
    ],    
    bootstrap: [AppComponent]
```

This will result in a state object with the 'chatWith' and the 'allUsers' property. This way, you'll be able to fetch them as you subscribed.

**Comment by smatthews1999** [comment]
Ok thank you.  I think I get it now.  I got this idea watching the Rob Womald video.  What I missed is, the properties of AppState can span more than one reducer.
