### ISSUE TITLE
What is the correct pattern for load and edit in ngrx/store

### ISSUE THREAD

**Issue by moniuch** [ngrx/store#267]
I was wondering about the recommendable pattern for subscribing to a data source and then, once it's loaded, remaining subscribed to the store where the textarea value is stored.

Currently I am pulling data from service (in an @Effect() load$) and then trying to display data in text area like so:

```
        this.code$ = store.let(fromRoot.getCodeSubstore);
        this.storeSub = this.code$.subscribe(codeState => {
            if(!codeState.loaded){
                this.store.dispatch(new codeActions.LoadAction({}));
            }
        });
```
and displaying like in:

`{{ ($code | async).html }}`

Another problem I am facing is that the textarea value (`codeState.html`) is not visible after load, ie. until I switch to another route and back. So I'm presuming I'm not doing it the right way. Any advice, please?

**Comment by glendaviesnz** [comment]
Normally you would access the code slice of your state with 

this.code$ = store.select('code');

and then use .let to apply additional selectors to the that slice of the state. 

It is a bit hard to tell from the limited code you have posted why you might be having problems with the value not displaying on first load. If switching to .select to get your state slice doesn't fix it then post details about your reducer and store setup.

**Comment by MikeRyanDev** [comment]
Seems like this has been resolved. Please reopen and leave a comment if it is not.
