### ISSUE TITLE
Store does not dispatch action after an exception

### ISSUE THREAD

**Issue by twmobius** [ngrx/store#268]
I am building a web application which mostly consumes data from a remote API. If an API http request fails, for whatever reason (ie due to validation error), it returns a status code different to 200 (in the range of 400-500). 

This is caught by the catch call in the effects block (seen below), which in turn invokes the matching action to notify the store of the event. 

The problem that I am facing is that if the http call fails, any subsequent request to the store via ` store.dispatch(this.actions.saveNote(note));` is not being executed at all.

This is the code in question:

Store actions:

```
@Injectable()
export class NoteActions {
  static SAVE_NOTE = '[Note] Save Note';
  saveNote(note): Action {
    return {
      type: NoteActions.SAVE_NOTE,
      payload: note
    };
  };

  static SAVE_NOTE_SUCCESS = '[Note] Save Note Success';
  saveNoteSuccess(note): Action {
    return {
      type: NoteActions.SAVE_NOTE_SUCCESS,
      payload: note
    };
  };

  static SAVE_NOTE_ERROR = '[Note] Save Note Error';
  saveNoteError(): Action {
    return {
      type: NoteActions.SAVE_NOTE_ERROR
    };
  };
}
```

Store effects: 
```
@Injectable()
export class NoteEffects {
  constructor(
    private update$:Actions,
    private actions:NoteActions,
    private service:NotesService
  ) {}

  ...

  @Effect() saveNote$ = this.update$
    .ofType(NoteActions.SAVE_NOTE)
    .map(action => action.payload)
    .switchMap(note => this.service.save(note))
    .map(note => this.actions.saveNoteSuccess(note))
    .catch(() => Observable.of(this.actions.saveNoteError()));
  
   ... 
}
```

At the same time the actual http calling service is simple:

```
@Injectable()
export class NotesService {
  constructor(
    private http:Http
  ) {}

  ...

  save(note:Note): Observable<Note> {
    if( note.id ) {
      var url = '/notes/' + note.noteId;

      return this.http.put(url, note, this.createRequestOptions())
        .map(res => res.json());
    }
    else {
      return this.http.post('/notes', note, this.createRequestOptions())
        .map(res => res.json());
    }
  }

  ...
}
```

Am I doing something wrong? Is this a bug?

**Comment by fxck** [comment]
Had the same problem yesterday. It's expected(yet undesired when it comes to effects) behaviour.

> catch catches errors on the source observable and replaces it with a new observable. **After your effect errors one time the source observable is no longer subscribed to**

It basically unsubscribes your effects from listening to actions. Put the `catch` inside switch map for a "fix".

**Comment by twmobius** [comment]
Hum...so the catch must go at the service invocation point (i.e `switchMap()`)? Then what is the purpose of the catch in the effect?

**Comment by MikeRyanDev** [comment]
Yes, the catch operator must be used immediately on the observable you return in `switchMap`. The mental model I use for `catch` is: the first observable threw an error and is no longer working, use this new observable instead.

**Comment by vkvarma** [comment]
Hi ,
I am able to dispatch action after doing the nesting of the catch into switchMap( as said above )
but when i receive any error into effects catch but my UI gets freeze .
Unable to do any action on UI (e.g. click on menu , click on button etc).

When i am calling http service from components rather than effects and handling error into the error block of subscribe inside component then everything is working fine.

**Comment by jotatoledo** [comment]
@vkvarma can you please open a new issue and link to this one?

**Comment by zpydee** [comment]
Thanks all for this thread. was facing a similar issue.
