### ISSUE TITLE
Reasonable to use ngrx/store with Angular 1?

### ISSUE THREAD

**Issue by joshuacc** [ngrx/store#27]
I looked through the docs and issues, but didn't find this question addressed anywhere.
1. Is it possible to use this library with Angular 1
2. Is it reasonable to do so?

**Comment by robwormald** [comment]
1. short answer: currently, no.
2. long answer: in theory, yes, with some work:
3. see #4 for the first step 
4. some way of integrating properly with angular1's digest cycle would have to be investigated
5. probably need to port the rx.angular bindings from rxjs4 to rxjs5 (which this library uses) - wouldn't be too difficult but goes with the prevous.
6. maybe. possibly. angular1 doesn't have the same sort of performance benefits you get with reactivity / immutablity in angular2. all of the mental benefits would still apply (that is, single state tree, easy testing, etc). 

It would _probably_ (though i haven't really even thought about it) in an angular/upgrade situation, where you were running ng1 and ng2 within each other.

**Comment by joshuacc** [comment]
Thanks for the thorough answer @robwormwald!

**Comment by Hotell** [comment]
I'll just leave it here https://gist.run/?id=d93766a07c516361fa75a376273590d4
ngrx/store with angular 1 and ngMetadata. Like a Boss

**Comment by mickdelaney** [comment]
has anyone got this to run lately, we're using angular 1 with rxjs/typescript + angular 2 with ngrx so we'd like to unify both approaches. but it seems that the latest ngrx depends on angular 2. 

ERROR in ./~/@ngrx/store/bundles/store.umd.js
Module not found: Error: Cannot resolve module '@angular/core' in c:\development\mickdelaney\angular1-ngrx-webpack\node_modules\@ngrx\store\bundles
resolve module @angular/core in c:\development\mickdelaney\angular1-ngrx-webpack\node_modules\@ngrx\store\bundles

  looking for modules in c:\development\mickdelaney\angular1-ngrx-webpack\src
    c:\development\mickdelaney\angular1-ngrx-webpack\src\@angular doesn't exist (module as directory)
  looking for modules in c:\development\mickdelaney\angular1-ngrx-webpack\node_modules
    c:\development\mickdelaney\angular1-ngrx-webpack\node_modules\@angular doesn't exist (module as directory)
  looking for modules in c:\development\mickdelaney\node_modules
    c:\development\mickdelaney\node_modules\@angular doesn't exist (module as directory)
[c:\development\mickdelaney\angular1-ngrx-webpack\src\@angular]
[c:\development\mickdelaney\angular1-ngrx-webpack\node_modules\@angular]
[c:\development\mickdelaney\node_modules\@angular]
 @ ./~/@ngrx/store/bundles/store.umd.js 2:117-141

ERROR in [default] c:\development\mickdelaney\angular1-ngrx-webpack\node_modules\@ngrx\store\src\ng2.d.ts:1:49
Cannot find module '@angular/core'.

**Comment by stephengardner** [comment]
+1, any update?

**Comment by jbadeau** [comment]
https://github.com/ngrx/store/issues/98

**Comment by jbadeau** [comment]
ng-metadata works fine with the latest version of nerd https://github.com/jbadeau/Angular1-scaffold/tree/ngrx

**Comment by jbadeau** [comment]
In fact the ngrx, ngmetadata and angular2 all work together just fine 😋 https://github.com/jbadeau/Angular1-scaffold/tree/ng1-ng2-hybrid-app
