### ISSUE TITLE
One step backwards in store

### ISSUE THREAD

**Issue by michael34** [ngrx/store#275]
Is it possible to go back one step basically revoking the last dispatch.

**Comment by bfricka** [comment]
You might want to look at the intro to [ngrx store](https://gist.github.com/btroncone/a6e4347326749f938510). This can be easily implemented using a meta-reducer. You can also look at the redux-devtools to see how they are doing time-travel.

**Comment by michael34** [comment]
@bfricka Alright. Thanks.
