### ISSUE TITLE
@ngrx and ng-ix18n

### ISSUE THREAD

**Issue by tschuege** [ngrx/store#277]
In my app.module I import the ngrx StoreModule as proposed in many tutorials on the web which works just fine

```
 @NgModule({
    imports: [
        StoreModule.provideStore({reducer1, reducer2})
        ....
```

But to support internationalisaziton I run ng-ix18n as decribed in the angular docs (https://angular.io/docs/ts/latest/cookbook/i18n.html)

Doing that I get the following error:
`Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol INITIAL_REDUCER in ..../node_modules/@ngrx/store/src/ng2.d.ts, resolving symbol provideStore in ..../node_modules/@ngrx/store/src/ng2.d.ts, resolving symbol StoreModule ....`

So ngrx should support a way to import the module that works with the compilation in ng-ix18n

**Comment by wizardnet972** [comment]
What do you want to store? i18n dictionary? if so use APP_INITIALIZER token to fetch them from the server, and use ngrx-token to save it to the store as init values.

**Comment by tschuege** [comment]
I'm not sure if I understand you right. It's not that I want to store anything related to i18n. I just want to import all the ngrx related stuff into my module in a way that works with ng-xi18n.
Doing it the usual way by using StoreModule.provideStore() results in the erro pasted in the initial comment.

Probably the error occures when ng-xi18n tries to compile ahead of time (AOT) in some way. But I'm not sure about that because I unfortunately don't know much about it...

**Comment by clembu** [comment]
The error says there's a problem with the reducers. Can we see those?

**Comment by tschuege** [comment]
Yesterday I tried to reproduce the error but i couldn't. I made some changes to my reducers since I posted the issue and some of these changes must have removed the problem. I also made a small demo project with only one simple reducer and ng-xi18n worked there as well.
So it must have been a problem with my code. 
Sorry for the inconvenience and thanks for your help!
