### ISSUE TITLE
Inconsistent state when dispatching an action inside a subscription

### ISSUE THREAD

**Issue by peterbakonyi05** [ngrx/store#279]
Hi,

I noticed something weird. Tried to make the example as simple as possible, that's why it is so silly (the production code where we have a similar issue is much more complicated).

Reducer
```ts
export type State = string[];
const initialState = [];
export function reducer(state = initialState, action: Action): State {
	switch (action.type) {
		case "FIRST":
		case "FIRST_COMPLETE":
		case "SECOND":
		case "SECOND_COMPLETE": {
			console.log(`REDUCER: ${action.type}`);
			return state.concat(action.type);
		}
		default: {
			return state;
		}
	}
}
```

Effect
```ts
	@Effect()
	a$: Observable<Action> = this.actions$
		.ofType("FIRST", "SECOND")
		.map(action => {
			console.log(`EFFECT: ${action.type}`);
			return { type: `${action.type}_COMPLETE` };
		});;
```

Subscription
```ts
    let did = false; // dirty way to make sure we dispatch first once

    store.select("order")
      .do(() => {
        if (!did) {
          did = true;
          store.dispatch({ type: "FIRST" });
        }
      })
      .subscribe((data: any) => {
        console.log("SUBSCRIBER: ", data);
      });

    store.dispatch({ type: "SECOND" });
```

Output
```
REDUCER: FIRST // coming from the do
SUBSCRIBER:  ["FIRST"]
EFFECT: FIRST
REDUCER: FIRST_COMPLETE // coming from the first effect
SUBSCRIBER:  ["FIRST", "FIRST_COMPLETE"]
SUBSCRIBER:  [] // THIS SHOULD HAVE BEEN THE FIRST OR SKIPPED
REDUCER: SECOND
SUBSCRIBER:  ["FIRST", "FIRST_COMPLETE", "SECOND"]
EFFECT: SECOND
REDUCER: SECOND_COMPLETE
SUBSCRIBER:  ["FIRST", "FIRST_COMPLETE", "SECOND", "SECOND_COMPLETE"]
```

So the issue is that if you dispatch an action inside the subscription, that will change the state synchronously, the subscriber is called first with the new state, but then it will be called with the old state, because that is in the queue already (I assume). I understand that this is probably an RxJS issue and the example above is a bad code/pattern, but still, I think this is not the expected behavior and since it is related to store and effect logic, first I wanted to report the issue here.

Thanks,
Peter

**Comment by peterbakonyi05** [comment]
I kept investigating, and reported another issue that seems to be the root cause of the problem:
https://github.com/ReactiveX/rxjs/issues/2155

**Comment by peterbakonyi05** [comment]
There is another wrong order (probably the root cause is the same). This is actually what we have encountered and as a quick fix, we added a `setTimeout 0` before dispatching the `SECOND` action. Now I am trying to find the correct solution. :)

Reducer and effect are the same.

Subscrtiption
```ts
store
      .select("order")
      .subscribe((data: string[]) => {
        if (data.length === 2) {
          this.store.dispatch({ type: "SECOND" });
        }
        console.log("SUBSCRIBER: ", data);
      });
  
    this.store.dispatch({ type: "FIRST" });
```

Output
```
SUBSCRIBER:  []
REDUCER: FIRST
SUBSCRIBER:  ["FIRST"]
EFFECT: FIRST
REDUCER: FIRST_COMPLETE
EFFECT: SECOND // THIS IS WRONG HERE
SUBSCRIBER:  ["FIRST", "FIRST_COMPLETE"]
REDUCER: SECOND
SUBSCRIBER:  ["FIRST", "FIRST_COMPLETE", "SECOND"]
REDUCER: SECOND_COMPLETE
SUBSCRIBER:  ["FIRST", "FIRST_COMPLETE", "SECOND", "SECOND_COMPLETE"]
```

As you can see the `SECOND` effect is running before the `SECOND` reducer, so if the `SECOND` effects gets the state from the store, it will see the previous state, which is clearly not what you would expect. :)

**Comment by peterbakonyi05** [comment]
In case you would like to try, here is a working demo: https://github.com/peterbakonyi05/ngrx-store-inconsistent-state :)

**Comment by vascofernandes** [comment]
I have the same problem I believe.


```Javascirpt


```

**Comment by robwormald** [comment]
Please check this against NgRx v4 (pretty sure we fixed this a while back), and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!

**Comment by doronsever** [comment]
@robwormald is it good practice to put a dispatch inside a selector?
For instance, I want to check if a certain user is inside my store and if not to fetch him.
Is it valid to do something like this?

```
const searchedUserId = 'abcdefg'; 
this.selecedUser$ = this.store.select(state => {
    const selectedUserIndex = state.userList.findIndex(searchedUserId)
    if (selectedUserIndex === -1) {
        this.store.dispatch(new UsersActions.FetchUsers(searchedUserId));  
    }
    else {
       return state.userList[selectedUserIndex]
    }
})```

**Comment by jotatoledo** [comment]
@doronsever  I would say no, as you are adding one more responsibility to something pretty much focused as a selector (get info, not generate a state transition)

**Comment by doronsever** [comment]
@jotatoledo So how would you suggest to accomplish this?

**Comment by maxime1992** [comment]
Doesn't seem related to this issue, you should rather ask on SO or gitter

**Comment by jotatoledo** [comment]
@doronsever  I agree with @maxime1992 , the issue tracker is no place for support questions. Please use gitter or SO

**Comment by rupeshtiwari** [comment]
I agree with @maxime1992 <https://github.com/maxime1992> too!  Additionally
i would encourage to join gitter you will love to see many people chatting
in various questions and their possible solutions. I love gitter.
