### ISSUE TITLE
divorce core from angular2

### ISSUE THREAD

**Issue by robwormald** [ngrx/store#28]
store should ideally work as a standalone module (though DI is a pretty core part of this...) - investigate moving the angular2 imports into a root file that imports the `store.ts` code.

**Comment by dsebastien** [comment]
+1, I'd like to use this with ng1

**Comment by robwormald** [comment]
initial implementation of this is in 1.3+

**Comment by dsebastien** [comment]
Cool, but there's still the devDependency on Angular 2. Should I care?

**Comment by robwormald** [comment]
_initial_ implementation. 

devDeps wouldn't be installed in an end user app. This would need more work to function in an ng1 application though.
