### ISSUE TITLE
RE: ngrx/store in feature module

### ISSUE THREAD

**Issue by samliaw** [ngrx/store#281]
I have a ngrx/sotre in main app.module, also also have a ngrx/store in feature module. 

When I try to import the feature module into the app.module, I find that the store in feature module is not being called at all. I have read somewhere that the ngrx/store should only be initialised and used only once per application. If this is the case, I will need to redesign the application.

Thanks for answering me.

**Comment by clembu** [comment]
For now, ngrx/store is a one-module thing only.
But changes are going to happen. You might want to read this:
https://gist.github.com/MikeRyan52/5d361681ed0c81e38775dd2db15ae202

Also your problem is fully discussed over at #211

**Comment by arangelp** [comment]
Is there any news about this topic?
I would be awesome to be able to use nrgs in different modules

**Comment by abdulhaq-e** [comment]
@arangelp #269 provides a solution, it has been merged but the feature is not documented fully nor released.

**Comment by arangelp** [comment]
@abdulhaq-e I checked the ticket #269 but I couldn't find how to proper use the Store in different modules with AOT
Could you provide a short example how to achieve this?

**Comment by robwormald** [comment]
Implemented and released in v4.
