### ISSUE TITLE
AngularJS?

### ISSUE THREAD

**Issue by JimLynchCodes** [ngrx/store#283]
This might be a stupid question, but is this library compatible with AngularJS 1.5 and/or is there an equivalent reactive redux library for AngularJS?

**Comment by fxck** [comment]
Currently ngrx is ng2 only. There were some community efforts(search issues) to bring it to ng1, but nothing official.

**Comment by JimLynchCodes** [comment]
Wow that fast. :) 

Yeah, I really like Angular 2, but I accepted a "challenge" to build something in AngularJS. I scaffolded out "TodoMVC" with no Redux design and it seems like a big cluttered mess. :/
I don't even know how to pass data around now. lol.

**Comment by MarkPieszak** [comment]
You can do regular Redux itself in AngularJS, or anything for that matter. It's really nothing but an event store. NgRx on the other hand is a whole thing, that's woven around ng2, RxJs, etc, so it would be too much to move it to ng1 I'd imagine. :/

**Comment by forforeach** [comment]
There is an Angular bindings for Redux called ng-redux - [https://github.com/angular-redux/ng-redux](url). It makes bridges between angular app and regular redux.
