### ISSUE TITLE
Organizing state as recommended by Redux?

### ISSUE THREAD

**Issue by csquillen** [ngrx/store#286]
Is it possible to use store.select() on a store structured in the shape recommended by Redux?  Redux recommends storing entities in an object keyed by ID, rather than in an array.  Here is the recipe in the Redux docs:

http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html

I'm trying to use store.select() on a state shaped this way like so:

```
store.select(state => state.contacts)
    .map(contacts => contacts.allIds.map(id => contacts[id]))
    .filter(contact => contact.type == 'customer') //Removing this works but I need a filter!
    .subscribe(customers => this.customers = customers);
```

However, I am getting the following error:

`store.select(...).map(...).filter is not a function`

**Comment by DzmitryShylovich** [comment]
You need to import it `import 'rxjs/add/operator/filter';`

**Comment by csquillen** [comment]
@DzmitryShylovich That was it.  Thank you!
