### ISSUE TITLE
Weird ng-cli serve hanging issue while building

### ISSUE THREAD

**Issue by mattheffernan** [ngrx/store#287]
node; 4.4.0
npm: 3.10.6
ng-cli; 1.0.0-beta.22-1

I'm new to the project so it could be me but I have been able to fix the issue I'm having by using the package.json file from the example project and reinstalling the modules.  The example is using 1.0.0-beta.17 and ng 2.1.0 vs current version of 1.0.0-beta.22-1 and ng 2.2.3.  I'm not positive if its the upgraded ng or the cli but there seems to be something going on.  

When you fire ng serve it gets to 20% building modules and then it just hangs.  If I comment out the StoreModule.provideStore(reducers) method from the modules imports property and then re-run the ng serve and it finishes successfully, I can then uncomment the StoreModule.provideStore(reducers) method the watch will re-compile and my app will work like normal.  If I run the beta.17 package.json dependencies then the app works like it should without the extra step to remove/add back the providerStore.

**Comment by michaeljpeake** [comment]
Glad to hear this isn't just me. Trying to find fix, similar to the ones [here](https://github.com/angular/angular/issues/10789).

**Comment by bertrandg** [comment]
Same for me, seems related to the last CLI version beta22 enabling AOT by default: 
https://github.com/angular/angular-cli/issues/3368

**Comment by bertrandg** [comment]
I went back to `1.0.0-beta.21` and works again for me.

**Comment by michaeljpeake** [comment]
Thanks for pointing that out @bertrandg. I rolled back to `1.0.0-beta.21` and all seems fine now.

... ahhh snap!

**Comment by MikeRyanDev** [comment]
This should be fixed in beta 24 of angular-cli
