### ISSUE TITLE
Examples of using store.select() for common use cases?

### ISSUE THREAD

**Issue by csquillen** [ngrx/store#288]
Can anyone point me to basic examples of using store.select() to select a single entity by id (primary key) and an example of using it to select a collection of entities by a foreign key or other field?

In other words, using store.select() to do the following:

```
store.subscribe(state => {
    let customer = state.customers.find(customer => customer.id == 1);
});

store.subscribe(state => {
    let addresses = state.addresses.filter(address => address.customer_id == 1);
});
```

Also, is subscribing to state directly this way okay to do?

**Comment by fxck** [comment]
What most of us do is use https://github.com/paularmstrong/normalizr it turns..

```typescript
[{
  id: 1,
  name: 'foo'
}]
```

..into..

```typescript
{
  entities: {
     customers: {
        1: {
          id: 1,
          name: 'foo'
        }
     }
  }
}
```

..which is much easier to consume.


You'd then do..

```typescript
store.map(state => state.entities.customers[1])
```

..or supposing that that id is from say query param instead of being hard coded, you'd do:

```typescript
params
  .pluck('id') // select id from query params
  .switchMap(id => store.map(state => state.entities.customers[id]));
```

And yes, subscribing to state this way is fine, but you don't want to do that *most* of the time, you want to use `async` pipe in the template instead, preferably along passing the result down to another component:

```typescript
user$ = this._router.params
  .pluck('id')
  .switchMap(id => store.map(state => state.entities.customers[id]));
```

```html
<user-card [data]="user$ | async"></user-card>

```

**Comment by csquillen** [comment]
@fxck Thanks for the info.  I like this approach of simply using standard array-like operators.  Why does store.select() exist?  Is there any simple API documentation for it and the other methods on store?

**Comment by fxck** [comment]
select is just a wrapper around map/pluck(depending whether you pass it string or function)

it does `map().distintctUntilChanged()`, nothing else

https://github.com/ngrx/core/blob/master/src/operator/select.ts

**Comment by csquillen** [comment]
@fxck I see.  Do you use select() most of the time for the benefit of distinctUntilChanged()?

**Comment by csquillen** [comment]
@fxck Also, how do you chain filter() to store to get the result set in my example above?

**Comment by fxck** [comment]
I'm not sure what you are trying to do in your example.

**Comment by csquillen** [comment]
@fxck If one of my "tables" in the store is addresses, how do I select or filter the addresses to return only the addresses that belong to a certain customer?

**Comment by fxck** [comment]
and where is that id of a customer coming from?

**Comment by csquillen** [comment]
@fxck In my example above, the customer id is hard-coded to 1.  However, in a real Angular 2 component that displays a customer and its addresses, the customer id would come from a route param.

**Comment by fxck** [comment]
ideally you want to create a bunch of small, composable selector functions and then call them with the `.let` operator.. this makes it easily reusable in any component

```typescript
// customer.selector.ts
getAddressesSlice$ = () => {
  return state$ => state$.select(state => state.addresses);
}

getAddressesForCustomer$ = (id) => {
  return state$ => state$
    .let(getAddressesSlice$())
    .select(address => addresses.filter(adr => adr.customer_id === id);
}
```

```typescript
// customer.page.ts
import { getAddressesForCustomer$ } from './customer.selector' ;

addresses$ = this._route.params
  .pluck('id')
  .switchMap(id => this._store.let(getAddressesForCustomer$(id))
```

```html
<!-- customer.page.html -->
<ul>
  <li *ngFor="let adr of addresses$ | async">
    {{ adr | json }}
  </li>
</ul>

<!-- ..or better.. -->
<customer-adresses [data]="addresses$ | async"></customer-adresses>
```


this is all pretty well explained in the `@ngrx/example-app`

**Comment by csquillen** [comment]
@fxck Okay, thanks.
