### ISSUE TITLE
@typings for @ngrx/store

### ISSUE THREAD

**Issue by gouravcoder** [ngrx/store#289]
Hi, where can i find typings for @ngrx/store, @ngrx/db, etc... ?

**Comment by gouravcoder** [comment]
sorry, found it my bad.

**Comment by sledorze** [comment]
@gouravcoder please close :)

**Comment by denyo** [comment]
@gouravcoder A hint were you found it would be great. Thank you!

**Comment by brandonroberts** [comment]
@denyo there isn't a special for the typings. They are included when you install the packages

**Comment by denyo** [comment]
@brandonroberts Thanks for the quick reply. 
I already had them but didn't really notice because I was looking for more detailed comments on each function like I am used to from DefinitelyTyped.
