### ISSUE TITLE
Composing reducers as in Redux's combineReducers

### ISSUE THREAD

**Issue by michaelbromley** [ngrx/store#29]
Hi Rob,

I am currently developing an ng2 app and using Redux for state management. I am really interested in switching to ngrx/store, but a few things are still not clear to me. Forgive me if this information is already there somewhere, I've spend a while searching and can't figure it out:

**How would one go about assigning a reducer to a specific portion of the state tree, as in Redux's combineReducers function?**

In the examples I can find, the state tree is very simple and the reducer(s) can easily operate on the entire state tree without this being unwieldy. Of course, in a real-world app you may have a reducer that needs to operate on the `state.customers.list.filter` object, and just have the `filter` object passed in to the reducer as the `state` arg, and have its return value written back to the correct portion of the state tree.

Thanks for any help, and kudos for pushing rxjs so hard - I am just starting to appreciate the power! :+1:

**Comment by fxck** [comment]
`provideStore` is equivalent of `combineReducers`, you pass it your reducers: `provideStore({ users, articles })` and then `state` inside the reducer will have the right portion of the state tree, not the whole tree. It's really the same as `combineReducers`.

**Comment by michaelbromley** [comment]
@fxck Thanks, I thought I must have missed it somewhere. Looking forward to trying this out in my app!
