### ISSUE TITLE
AOT doesn't work with angular 2.3.* +

### ISSUE THREAD

**Issue by fxck** [ngrx/store#295]
Throws `No provider for Store!`. Works fine with 2.2.*.

https://github.com/ngrx/store/issues/78#issuecomment-266793234

**Comment by mmrath** [comment]
A sample repo to reproduce can be found  at https://github.com/angular/angular/issues/13521
This might be a angular issue though

**Comment by juanlizarazo** [comment]
I get `No provider for Dispatcher!`, same issue. With Angular 2.3.1 and @ngrx/store

**Comment by mmrath** [comment]
This is now resolved in angular master. I tried the latest snapshot builds and it works. Waiting for the      next minor release.
