### ISSUE TITLE
Change Action interface to accept a type parameter of the payload

### ISSUE THREAD

**Issue by KiaraGrouwstra** [ngrx/store#297]
I'd been thinking for inference purposes it's currently a bit unfortunate that `Action` leaves its `payload` type implicit, rather than e.g. parameterizing the class with a generic `<T>` matching its `payload` type. Might this perhaps be of use?

**Comment by garkbit** [comment]
I'd really love to see this as well.

**Comment by robwormald** [comment]
we're going to have a rethink on type inference in Store once typescript 2.1 is available for angular/core. There's a number of new features that will let us flow types through more simply.

**Comment by MikeRyanDev** [comment]
I think the better solution would be to drop `payload` from the interface altogether:

```ts
interface Action {
  type: string;
}
```

And then make `Store.dispatch` generic:
```ts
dispatch<T extends Action>(action: T): void;
```

**Comment by KiaraGrouwstra** [comment]
@MikeRyan52: it seems there may be places where actions are instantiated outside of `dispatch` as well, e.g. when making them in effects (`ngrx/effects`). It would be nice to get type safety for their constructor parameter in there as well.

**Comment by SethDavenport** [comment]
Plug for flux-standard-action, or something whose typings are compatible: https://github.com/acdlite/flux-standard-action/blob/master/src/index.d.ts

**Comment by peterholak** [comment]
You can do a lot even without TypeScript 2.1 features, if you allow the user to supply a union of all possible action types, see https://goo.gl/3R9KeS (links to http://www.typescriptlang.org/play/, you can see errors in the editor there). You get type-checked actions, autocomplete, etc. (you could also do it with a `payload` property, even though my example doesn't use it.)

**Comment by fxck** [comment]
That's pretty much what the example app is doing already.

https://github.com/ngrx/example-app/blob/master/src/app/actions/book.ts#L56

**Comment by alexciesielski** [comment]
Looking forward to this as well

**Comment by ovangle** [comment]
@MikeRyanDev

Instead of dropping `Action.payload`, what about about dropping `Action.type` strings when making `Action` generic?

e.g.
https://gist.github.com/ovangle/699f6a45423b8a67360be1b98a77da76

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
