### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by slawojstanislawski** [ngrx/store#300]
**Current behavior**
The error appears after creating angular-cli (beta-24) project, adding a simple reducer, and building the project. It looks as if an undefined action was passed to reducers. The problem doesn't seem to appear when running in development: `ng serve`

**Reproduction of the problem with instructions**
- install angular-cli: `npm install angular-cli@1.0.0-beta.24 -g`
- create a new ng-cli project: `ng new test-project`
- visit the [plunkr](https://plnkr.co/edit/Wmftc7), download the code as .zip and put the extracted files at the root of the newly created ng-cli project
- run `npm install` to install ngrx-related libs (added in package.json from the plunkr)
- run `ng serve --prod`

**Environment:**
OS: Windows 10 x64
browsers: reproduced in Chrome, FF, IE11
node: v6.9.2
npm: v3.10.9
angular-cli: 1.0.0-beta.24

**Comment by MikeRyanDev** [comment]
There is an issue with how you are composing your production reducer.

Instead of:
```ts
const productionReducer: ActionReducer<RootState> = compose(
  localStorageSync(['user'], true),
  combineReducers(reducers)
);
```

it should be:
```ts
const productionReducer: ActionReducer<RootState> = compose(
  localStorageSync(['user'], true),
  combineReducers
)(reducers);
```
