### ISSUE TITLE
How to inject services to reducer?

### ISSUE THREAD

**Issue by 888dev** [ngrx/store#301]
I have loggerService that sends my errors to the server. Is there some option to inject my service inside reducers?

**Comment by fxck** [comment]
you don't, reducers are supposed to be pure functions, use @ngrx/effects if you need to do async or whatever

**Comment by yelenka** [comment]
thanks

**Comment by 888dev** [comment]
But still can I catch errors from reducers and in any way to store it on server, using my loggerService?

**Comment by fxck** [comment]
What errors? Javascript errors?

**Comment by 888dev** [comment]
yes i need to store it via my loggerService

**Comment by fxck** [comment]
Can't just set up global listener for any error? Why does it have to be inside reducers?

Or just use https://trackjs.com/ or https://sentry.io/welcome/ ?

**Comment by 888dev** [comment]
I need in some way to catch errors from reducers and send it to the server via my loggerService. I use window.onerror, but its not enough. Any ideas?

**Comment by littleStudent** [comment]
Add the error state to your reducer. Let your `loggerService` subscribe to this data. Then you can do whatever you want with it.

**Comment by yelenka** [comment]
thanks it really help
