### ISSUE TITLE
Question about Store

### ISSUE THREAD

**Issue by amirduran** [ngrx/store#302]
If I have two multiple reducers: StudentsReducer, ExamReducer, and I fire store.dispatch(action) how store knows which reducer should be called (StudentReducer, ExamReducer), or all reducers are called, and based on type parameter, specific action will be performed?

Thx

**Comment by fxck** [comment]
all reducers receive all actions

**Comment by amirduran** [comment]
Ok, and where reducers are subscribed to the dispatch event?

**Comment by fxck** [comment]
in `provideStore()`

```
StoreModule.provideStore({ counter: counterReducer })
```

**Comment by amirduran** [comment]
Great, thank you for answers
