### ISSUE TITLE
How to handle errors in reducers?

### ISSUE THREAD

**Issue by 888dev** [ngrx/store#303]
I need in some way to handle errors from reducers and save it in logger. How can I do it?
Thanks !!!

**Comment by wizardnet972** [comment]
Let me try to improve your question:

How to write a log to each cases in switch statements? or how to inject service into reducer?
What I mean for example is I have this code in the reducer:

```
switch(action) {

  case ACTION: 
      try {
        .....      
      }
      catch(e) {
      logger.log('ACTION', e);
     }

   case OTHERACTION: 
      try {
        .....      
      }
      catch(e) {
         logger.log('ACTION', e);
      }
}
```

My answer to your question is: You should 
do meta-reducer like [ngrx-logger](https://github.com/btroncone/ngrx-store-logger) .
or catch in effects
or use global javascript variable 
or verify that your payload is cannot be null or invalid data.

**Comment by 888dev** [comment]
thanks
