### ISSUE TITLE
Which part of the state is updated

### ISSUE THREAD

**Issue by amirduran** [ngrx/store#304]
Something is still not clear to me. How reducer exactly knows which part of the Store to change. 

If Store keeps instance of the following interface:

`export interface AppStore {
  items: Item[];
  selectedItem: Item;
  widgets: Widget[];
  selectedWidget: Widget;
  };`

How items reducer exactly knows which part of the Store he has to change? 

In my example, there is a reducer for items: 

`export const items = (state: any = [], {type, payload}) => {
  switch (type) {
    case 'ADD_ITEMS':
      return payload;
    case 'CREATE_ITEM':
      return [...state, payload];
    case 'UPDATE_ITEM':
      return state.map(item => {
        return item.id === payload.id ? Object.assign({}, item, payload) : item;
      });
    case 'DELETE_ITEM':
      return state.filter(item => {
        return item.id !== payload.id;
      });
    default:
      return state;
  }
};`

How exactly this reducer knows that he has to change items attribute of the AppStore object?

I'm working using this example: 
https://github.com/onehungrymind/fem-ng2-ngrx-app

Thx for helping

**Comment by simb** [comment]
I believe this happens when you bootstrap the provider.

StoreModule.provideStore({items, selectedItem, selectedWidget})

"items" represents your items reducer in your app store.

**Comment by amirduran** [comment]
Yes yes, that is correct, but when reducer is executed, how reducer knows which part of the store to change?

**Comment by robwormald** [comment]
@amirduran it doesn't. each reducer is called with each action, for every action. its up to the developer to either handle that action or simply ignore it.

**Comment by littleStudent** [comment]
each reducer can only update its own part of the state. So your `items` reducer can only update items. It does not even have access to a different part of the state.

**Comment by amirduran** [comment]
@littleStudent Exactly what I was looking for. Thank you for answering. 

The last question 😃  where do I tell reducer for which part of the state is reducer responsible? Does library implicitly recognise that by having same names for store elements and reducer names?

**Comment by littleStudent** [comment]
take a look at the example in the readme.
```Javascript
StoreModule.provideStore({ counter: counterReducer })
```

`counterReducer` handles one part of the state -> `counter`

**Comment by amirduran** [comment]
@littleStudent That is what I thought 😄  Thank you mate
