### ISSUE TITLE
Lazy Loading of reducers

### ISSUE THREAD

**Issue by arat3091** [ngrx/store#308]
Well i am trying the way told in the below URL for the 
https://github.com/ngrx/store/issues/197

but the problem is that  my root reducer is below

const productionReducer: ActionReducer<State> = combineReducers(reducers);

export function reducer(state: State, action: Action) {
  return productionReducer(state, action);
}

now  where to introduce the asyncReducers in the obove root reducer.

With the example of blog post given by MikeRyan52 i get the errors of state undefined.

I just need an example may be in the example app for the lazy loading feature modules

**Comment by evanjmg** [comment]
I'm no expert on ng store, but I use the routes to load my reducers (or at least keep them in the lazy submodule that I need). I think this is a very organised and clean approach to route based reducers. Though if you want to clean up and replace reducers you can also do something like in here https://github.com/ngrx/store/issues/197
 ````
// ngModule in imports
...
imports: [StoreModule.provideStore(AppModule.reducers())]
})

// my App Module that is being decorated by ngModule
export class AppModule {

  static reducers(): ActionReducer < any > {
    return combineReducers(Object.assign({},
      Reducers,
      ...(ROUTES.filter(route => (route.data && route.data['reducers'])).map(route => {
       return route.data['reducers'];
    }))
    ));
  }
})
// my routes
const ROUTES = [ {
  path: PATHS.GUESTS_PATH,
  loadChildren: () => System.import('./submodules/guest-book')
    .then((comp: any) => comp.default),
  data: {
    reducers: GuestBookReducers,
    preload: true
  }
},
{ path: PATHS.ADMIN_ROOT_PATH, loadChildren: () => System.import('./submodules/admin').then((comp: any) => comp.default),
  data: {
    reducers: AdminReducers
  }
}]
```

**Comment by snarun** [comment]
But this will not split the build module in chunks. The module will still be part of the main bundle. We may need a better approach of stitching reducers to the main stream, on a need basis while keeping the module in chunks.

**Comment by robwormald** [comment]
Implemented and released in v4.
