### ISSUE TITLE
State observers array items constantly increasing

### ISSUE THREAD

**Issue by josh-sachs** [ngrx/store#309]
I want to preface by saying that I don't have a really deep understanding of rxjs or using the chrome debuging tools.  I've put together an angular 2 application on top of ngrx/store and I've been trying to understand why after several hours left running (no interaction) javascript memory usage grows 10x and the app eventually crashes the browser. 

When i do heap shot comparisons, the issues all stem from (array) constantly getting larger.  The top item points to "observers in State".   All of my components have a private _state$ observable obtained via store.select(), and then all the component's observables are chained off of that.  with various maps, dos, distinctUntilChange etc... when I subscribe to the store directly, it is always with a Take(1).  I'm using async pipes wherever an observable is surfaced to the DOM. 

I'm not sure if there is an issue with the store here or if I'm just slow...  
![array](https://cloud.githubusercontent.com/assets/11616365/21743690/73dff04c-d4d5-11e6-81b7-3129c7135379.PNG)

**Comment by MarkPieszak** [comment]
Are you leaving devtools open for that extended period of time on the page? It might be happening because of that?

**Comment by abdulhaq-e** [comment]
Maybe related: https://github.com/ngrx/store/issues/167

Try rxjs 5.0.3 and see if that still happens.

**Comment by josh-sachs** [comment]
I'm running 5.0.3 - I was aware of that issue and was awaiting it's release until I made this post.   I am leaving dev tools open for that extended period - is that known to cause issues?

**Comment by abdulhaq-e** [comment]
Yes, see this comment: https://github.com/ngrx/store/issues/167#issuecomment-267728254

**Comment by josh-sachs** [comment]
Is @ngrx/store-devtools a separate package?  The comment references it I'm not importing that anywhere.

**Comment by abdulhaq-e** [comment]
Sorry I thought you were. Yes, it's a separate package that can be used for logging action etc (other packages exist).

So you are not doing any kind of logging?

**Comment by josh-sachs** [comment]
Correct, I open the page and let it for a few hours and the memory climbs.  I do have the Chrome Developer Tools window open during that time. 

Just to be clear, here is how I'm consuming. 

`
let _$state = Store.select('stuff');
let a$ = _$state.map(stuff => stuff.a).distinctUntilChanged();
let b$ = _state$.map(stuff => stuff.b).distinctUntilChanged();
let c$ = _state$.map(stuff => stuff.c)
                 .do(c => process(c))
                 .distinctUntilChanged();
`

I assume this is an appropriate pattern?

**Comment by josh-sachs** [comment]
I'm following up to see if there is any more information I can provide on this.  If it is unlikely to be an issue with ngrx/store based on the information I've given so far, we can close.

**Comment by philjones88** [comment]
I just hit this too.

Turned out even though I hadn't got the dev tools open it was still storing the states.

I was missing the `maxAge` option so it would build up over time and crash Chrome eventually.

**Comment by josh-sachs** [comment]
@philjones88 what is the maxAge option?  can you link to info?

**Comment by philjones88** [comment]
https://github.com/ngrx/store-devtools#instrumentation-with-the-chrome--firefox-extension-preferred

maxAge is how much "previous state" should be stored. If you don't set it, it will store everything and get very big!

**Comment by josh-sachs** [comment]
What if we haven't got @ngrx/store-devtools installed?  I was referring to Chrome dev-tools (F12) when I say haven't got dev-tools open.   I'm going to look into this module regardless now that it is on my radar - just looking to clarify.

**Comment by philjones88** [comment]
You probably have a memory leak in your code then.

I have tables of data updating every second by NGRX store actions and the memory usage is stable over a long time.

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
