### ISSUE TITLE
Hot Module Reload state persistence

### ISSUE THREAD

**Issue by Mark-McCracken** [ngrx/store#311]
Hi guys,
I've been trying to implement Hot Module Reloading in a CLI generated project.
Managed to get this working by using the following as a guide: https://github.com/jschwarty/angularcli-hmr-example
however the state is lost between module reloads.

There was an issue in here, but it's from May last year using systemjs.
Found this library, ngrx-store-hmr, but it's 10 months old and uses syntax from angular which I think is outdated.

My hmr.ts file looks like the following:
```
import { NgModuleRef, ApplicationRef } from "@angular/core";
import { createNewHosts } from "@angularclass/hmr";

export const hmrBootstrap = (module: any, bootstrap: () => Promise<NgModuleRef<any>>) => {
  let ngModule: NgModuleRef<any>;
  module.hot.accept();
  bootstrap().then(mod => ngModule = mod);
  module.hot.dispose(() => {
    let appRef: ApplicationRef = ngModule.injector.get(ApplicationRef);
    let elements = appRef.components.map(c => c.location.nativeElement);
    let makeVisible = createNewHosts(elements);
    ngModule.destroy();
    makeVisible();
  })
};
```

and my main.ts file looks like so:
```
import './polyfills.ts';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { environment } from './environments/environment';
import { AppModule } from './app/';
import { hmrBootstrap } from './hmr';

if (environment.production) {
  enableProdMode();
}

const bootstrap = () => {
  return platformBrowserDynamic().bootstrapModule(AppModule);
};

if (environment.hmr) {
  if (module['hot']) {
    hmrBootstrap(module, bootstrap);
  } else {
    console.error('HMR is not enabled for webpack-dev-server!');
    console.info('Are you using the --hmr flag for ng serve?');
  }
} else {
  bootstrap();
}
```

Does anyone know how to integrate state persistence between module reloads, that could slot into the above code?

**Comment by glendaviesnz** [comment]
Have you looked at https://github.com/qdouble/angular-webpack2-starter ? It implements HMR with ngrx-store.

**Comment by Mark-McCracken** [comment]
No, mainly because I've been using the CLI. A lot of people I've spoken to don't seem too familiar with setting up and customising webpack to their needs, but love the CLI. It would be great to have a working example of a CLI generated project that can have this to share with others.

I'll look into the web pack repo, but not sure if I'll be able to port the implementation to the CLI, as I don't really know properly the details of how either web pack or the CLI implements things.

Was hoping someone in here might know what to do?

**Comment by ChrisMurphy** [comment]
@Mark-McCracken I'm having the same issue, did you get anywhere? Have raised this on stackoverflow: http://stackoverflow.com/questions/41679716/angular-cli-hmr-and-ngrx

**Comment by MarkPieszak** [comment]
I have HMR holding onto NgRx state here, it's in a .NET Core & Angular Universal Webpack repo, but I believe it would work in the same scenario? (Not positive)

Here is where I'm handling HMR and the state:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/state/hmr.ts

Here you can see I'm injecting it into the main browser file:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/bootstrap-client.ts#L28-L31

@Mark-McCracken @ChrisMurphy

**Comment by joshwiens** [comment]
@Mark-McCracken - https://github.com/qdouble/angular-webpack2-starter/blob/no-universal-support/src/app/reducers/index.ts#L24-L31

**Comment by pacjin79** [comment]
@MarkPieszak Your approach works well, and it's a simple modification to add the store as a listener during module.hot.dispose, so thanks a million,  I'd suggest every one here looking for a solution to take a look at Mark's recommendation.  Essentially.  modify your hmr.ts like so:

`export let appState:any = {};

export const hmrBootstrap = (module: any, bootstrap: () => Promise<NgModuleRef<any>>) => {
   let ngModule: NgModuleRef<any>;
   module.hot.accept();
   bootstrap().then(mod => ngModule = mod);
   module.hot.dispose(() => {
     let appRef: ApplicationRef = ngModule.injector.get(ApplicationRef);
     let elements = appRef.components.map(c => c.location.nativeElement);
     **let store:Store<any> = ngModule.injector.get(Store);
     store.take(1).subscribe(s => {
      appState = s;
    });**
    let makeVisible = createNewHosts(elements);
    ngModule.destroy();
    makeVisible();
  });
};
`

Then in your app.module.ts file, change your store to accept the exported appState from step 1 as the initial state like so 

`
**import {appState} from "../hmr";**

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    FeaturesModule,
    MaterialModule,
    HttpModule,
    RouterModule.forRoot(featureRoutes, {useHash: true}),
    **StoreModule.provideStore({router: routerReducer, application: reducer}, appState),**
    StoreDevtoolsModule.instrumentOnlyWithExtension(),
    RouterStoreModule.connectRouter()
  ],

  providers: [
    {
      provide: Http,
      useFactory: httpFactory,
      deps: [XHRBackend, RequestOptions, Store]
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`

**Comment by e-cloud** [comment]
@Mark-McCracken your link is broken, @pacjin79 your code's style needs improvement for better readibility.

**Comment by valerius257** [comment]
Unfortunately the workaround proposed by @pacjin79 is not working when changes occur in lazy loaded modules.

**Comment by e-cloud** [comment]
@valerius257 you may have a look at https://github.com/e-cloud/ngrx-store-hmr-integration

**Comment by joshwiens** [comment]
I linked this once further up but this is possible to implement inside the `@angular/cli` based on @qdouble's hmr work in https://github.com/qdouble/angular-webpack2-starter

Literally, all you need to do is add `environment.hmr.ts` as normal & then duplicate @qdouble's HRM implementation ( make sure to show some comment love if you are going to `cmd + c` and not implement your own version). 

It works like a charm.

**Comment by thewebuiguy** [comment]
@MarkPieszak  your links go to 404 pages.

**Comment by robwormald** [comment]
Closing this as we're migrating to https://github.com/ngrx/platform. Feel free to re-open over there if there's something we can do to improve HMR. Thanks!
