### ISSUE TITLE
Creating meta-reducer with DI

### ISSUE THREAD

**Issue by chimon2000** [ngrx/store#313]
**Question**
Is it possible to create a meta-reducer and inject dependencies? 

I have seen this question posted [elsewhere](https://gist.github.com/btroncone/a6e4347326749f938510#gistcomment-1886851), but w/o a response. I know that it is possible using [ng2-redux](https://github.com/angular-redux/ng2-redux/blob/master/docs/di-middleware.md)

**Comment by adharris** [comment]
The store has a `replaceReducer` method which could be used:

```typescript
import { reducers } from './somewhere';
import { ActionReducer, combineReducers, Store, Action } from '@ngrx/store'

@Injectable()
class InjectedMetaReducer {

    private reducer: ActionReducer;

    constructor(private store: Store<any>) {
        this.reducer = combineReducers(reducers);
        this.store.replaceReducer((state, action) => this.metaReducer(state, action));
    }

    metaReducer(state: any, action: Action) {
        return this.reducer(state, action); 
    }
}
```

That won't run until it's injected somewhere.  Probably in your AppComponent.

**Comment by chimon2000** [comment]
Awesome, that was actually exactly what I needed @adharris
