### ISSUE TITLE
error_handler.js:50 EXCEPTION: Uncaught (in promise): Error: Can't resolve all parameters for Store: (?, ?, ?).

### ISSUE THREAD

**Issue by st-clair-clarke** [ngrx/store#318]
Hi, I am using the following in my package.json

```
    dependencies": {
    "@angular/common": "^2.4.3",
    "@angular/compiler": "^2.4.3",
    "@angular/core": "^2.4.3",
    "@angular/flex-layout": "^2.0.0-beta.1",
    "@angular/forms": "^2.4.3",
    "@angular/http": "^2.4.3",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "^2.4.3",
    "@angular/platform-browser-dynamic": "^2.4.3",
    "@angular/router": "^3.3.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1",
    "@ngrx/store-devtools": "^3.2.2",
````

When I run my application I get the following: error_handler.js:50 EXCEPTION: Uncaught (in promise): Error: Can't resolve all parameters for Store: (?, ?, ?).

This occurs after I upgraded to angular-cli@1.0.0.25.5 and @angular/**:^2.3.1

Googling took me to the following page [https://github.com/angular/angular-cli/issues/3707](https://github.com/angular/angular-cli/issues/3707) where my initial issue was was discussed. After following thie instructions to solve the initial issue, this one resulted.  I tried everything suggested but nothing seems to help.

Hope someone can help.
Thanks

**Comment by christophjohannsdotter** [comment]
You've got to take care, not to include the 'Store' to the providers array of your component. I had exactly the same issue, removing Store from Providers solved it, since Store is imported in App already.
