### ISSUE TITLE
Interface Definition of Reducer

### ISSUE THREAD

**Issue by simonh1000** [ngrx/store#32]
If you permit, can I just point you to my stackoverflow question and the answer I got. http://stackoverflow.com/questions/35258703/typescript-ngrx-and-default-store-values/35259282#35259282 

In short, I am struggling to use nested reducers to set default values and was suggested that it is due to the lack of `?` in the definition of `Reducer`
To my mind it makes better design sense if the parent does **not** need to know the definition of the child to be able to add a new child to the global model - at least that it was what I am used to in Elm

**Comment by robwormald** [comment]
ngrx doesn't really care what you do below the "root" reducer level - that is, as long as the reducer function you're passing to the store implements `Reducer`, you can do what you like in the children.

so assuming you want to maintain an array of counters under a `counters` key, you could define your own interface if you wished - there's no reason `counter` needs to implement ngrx's specific interface.

perhaps i'm misunderstanding what you're trying to do though, so if you'd post your reducer code in here i'd be happy to have a look.

**Comment by simonh1000** [comment]
Thanks Rob, that worked, although I wonder whether it is perfectly elegant that my child reducers have a _slightly_ different type signature than the parent.
