### ISSUE TITLE
Store is initialized empty after updating from angular 2.1 to 2.2

### ISSUE THREAD

**Issue by 0radek** [ngrx/store#323]
In 2.1, my `reducers/index.ts` looked like this:

```
// reducers index.ts
import { compose } from '@ngrx/core/compose';
import { combineReducers, ActionReducer } from '@ngrx/store';
import reducer1 from './reducer1';
import reducer2 from './reducer2';
import reducer3 from './reducer3';
import reducer4 from './reducer4';

export default compose(combineReducers)({
  reducer1,
  reducer2,
  reducer3,
  reducer4
});
```

After updating to 2.2, I started seeing an issue which I was able to resolve with help from an issue here:  https://github.com/ngrx/store/issues/190

So, I had to update my `reducers/index.ts` to this to not get any more errors:

```
import { compose } from '@ngrx/core/compose';
import { combineReducers, ActionReducer } from '@ngrx/store';
import reducer1 from './reducer1';
import reducer2 from './reducer2';
import reducer3 from './reducer3';
import reducer4 from './reducer4';

export function reducers(): ActionReducer<any> {
  return compose(combineReducers)({
    reducer1,
    reducer2,
    reducer3,
    reducer4
  })
};
```

Unfortunately, now my store is empty and I receive errors like this: `TypeError: Cannot read property categories of undefined`

So I followed some more advice from that same issues thread, but now my store initializes empty.  Is there something that I am missing?

Thanks

**Comment by bortexz** [comment]
Have a look at [this](https://github.com/ngrx/store/issues/273#issuecomment-272622554) and tell me if it works for you

**Comment by ScaryWolfMan** [comment]
@bertofer Will let you know ASAP.  Unfortunately away from my dev machine right now, sorry about that.  Thank you for your response though, I really appreciate it.

**Comment by 0radek** [comment]
Whoah!  Awesome!

That fixed it.  Thanks bud!
