### ISSUE TITLE
typesafe payload in typescript 2.1.x

### ISSUE THREAD

**Issue by fxck** [ngrx/store#325]
This used to work:

```typescript
export const Types = {
  FOO: label('foo')
};

export class FooAction implements Action {
  public type = Types.FOO;

  constructor(public payload: number) { }
}

export type All =
    FooAction;
```

```typescript
export class FooState {
  bar: number;
}

const initialState = { bar: 0 };

export function fooReducer(
  state: FooState = initialState,
  action: fooActions.All
): FooState {

    case authActions.Types.FOO:
      return Object.assign({}, state, {
        bar: action.payload // this used to have correct type `number`, now it doesn't
      });
}
```

what will be the correct way to get proper types going forward? @MikeRyan52 @brandonroberts @robwormald 

..or it still works and it's just me? The actual error it throws is 

> message: 'Property 'payload' does not exist on type 'All'.

which seems to get resolved when I add payload property even to those action classes that do not need it, but then `action` is always of type `any`, as if it was not filtering it by that switch/case as it used to.

SO question: http://stackoverflow.com/questions/41802385/typescript-2-0-x-vs-2-1-x-type-definition-filtered-by-switch-case-statement

**Comment by brandonroberts** [comment]
See https://github.com/ngrx/example-app/pull/88#issuecomment-272623083

**Comment by fxck** [comment]
Missed that one, thanks!
