### ISSUE TITLE
anything like react redux forms or best practices?

### ISSUE THREAD

**Issue by philjones88** [ngrx/store#326]
I'm looking for guidance mostly on how to use store with angular (2) forms, I'm starting to think my current approach of:

* local component properties
* rehydrate with a `.first()` on a ngOnInit store select
* [(ngModel)] to said properties
* (onModelChange) with dispatching updates

is not the best.

Googling around it looks like the React Redux community has some form libraries.

I quite like the look of http://redux-form.com/6.4.3/examples/simple/ and looking at the dev tools it's dispatching actions and storing the state of the form in the store.

Has anyone done any form CRUD work and can point to some best practices?

**Comment by fxck** [comment]
https://github.com/ngrx/core/issues/12
