### ISSUE TITLE
Aot: Calling function 'makeDecorator', function calls are not supported. 

### ISSUE THREAD

**Issue by tamascsaba** [ngrx/store#328]
When I run:
```
ngc -p ./tsconfig.prod.json
```

I got the following error:

`
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/tonyo/projects/foo/node_modules/@ngrx/store/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /home/tonyo/projects/foo/node_modules/@ngrx/store/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /home/tonyo/projects/foo/node_modules/@ngrx/store/node_modules/@angular/core/src/di/opaque_token.d.ts
`

I use:
```
"@angular/compiler": "^2.4.2",
"@angular/compiler-cli": "^2.4.2",
"@ngrx/core": "^1.2.0",
"@ngrx/store": "^2.2.1",
```

**Comment by tamascsaba** [comment]
Sorry it is not ngrx related problem, i closed the issue :(

**Comment by mikeperri** [comment]
@tamascsaba Were you able to fix it? I'm getting a similar error.

npm install output:
```
+-- @angular/common@2.4.7
+-- @angular/compiler@2.4.7
+-- @angular/compiler-cli@2.4.7
| +-- @angular/tsc-wrapped@0.5.2
| | -- tsickle@0.2.6
| |   +-- mkdirp@0.5.1
| |   | -- minimist@0.0.8
| |   +-- source-map@0.5.6
| |   -- source-map-support@0.4.11
| +-- minimist@1.2.0
| -- reflect-metadata@0.1.9
+-- @angular/core@2.4.7
+-- @angular/platform-browser@2.4.7
+-- @angular/platform-server@2.4.7
| -- parse5@2.2.3
+-- @angular/router@3.4.7
+-- @ngrx/core@1.2.0
+-- @ngrx/effects@2.0.0
+-- @ngrx/router-store@1.2.5
+-- @ngrx/store@2.2.1
+-- core-js@2.4.1
+-- rxjs@5.0.1
| -- symbol-observable@1.0.4
+-- typescript@2.1.4
-- zone.js@0.7.6
```
tsc output:
```
>.\node_modules\.bin\ngc -p tsconfig.json
Error: Could not resolve module @angular/core/src/di/opaque_token
    at StaticSymbolResolver.getSymbolByModule
    at StaticReflector.findDeclaration
    at StaticReflector.initializeConversionMap
    at new StaticReflector
    at Object.createAotCompiler
    at Function.CodeGenerator.create
    at codegen
    at Object.main
    at main
    at Object.<anonymous>
Compilation failed
```
