### ISSUE TITLE
Object not updating on the UI

### ISSUE THREAD

**Issue by jrmcdona** [ngrx/store#332]
I have a simple object called ambassador that I **retrieve from the store** which should be getting the initial state - see the constructor down below.

```
    constructor(
        private store: Store<AppState>,
        private ambassadorActions: AmbassadorActions,
        private router: Router,
        private route: ActivatedRoute,
    ) {
        **this.ambassador = store.select('ambassador');**
    }
```

Let's take this very simple UI which I want to see update after the successful API call.  
```
<div>
    {{ambassador.id}}
</div>
```

I then run these lines of code on the Init.  However, it does not appear my object is getting updated because the UI is not changing.   I have logging turned on and it appears that the object is updated

```
    ngOnInit() {
        this.paramsSub = this.route.params.subscribe(params => this.username = params['username']);
        this.getAmbassador(this.username);
    }

    getAmbassador(username) {
        this.store.dispatch(this.ambassadorActions.getAmbassador(username));
    }
```

What am I missing here?

Thanks!

**Comment by brandonroberts** [comment]
@jrmcdona `store.select('ambassador')` returns an Observable, so you need to subscribe to it to get its value

```html
 {{ambassador.id}}
```

should be
```html
{{ (ambassador | async)?.id }}
```

**Comment by bertrandg** [comment]
Your `ambassador` variable is an observable, you should use `async` pipe:
```
<div>
    {{ (ambassador | async)?.id }}
</div>
```
