### ISSUE TITLE
Observable.forkJoin does not work on Store Observable

### ISSUE THREAD

**Issue by erictsai6** [ngrx/store#333]
Hey,

  Looks like because store.select ultimately returns a Store obj it is not compatible with Observable.forkJoin.  I did a simple test to validate this in the plunker below with where i subscribe to the forkJoin and directly to the store.select.

https://plnkr.co/edit/JYWyji90VOC5Og7CsIdC?p=preview

// Important file is src/app.ts
`Observable.forkJoin([
      store.select('todos'),
      store.select('visibilityFilter')])
      .subscribe((data) => {
        console.log('is this working?  the answer is no');
        console.log(data);
      });`
` store.select('todos')
      .subscribe((data) => {
        console.log('single subscribe works');
        console.log(data);
      });`

**Comment by bertrandg** [comment]
I think `forkJoin` waits for completed observables so test this:

```
Observable.forkJoin([
      store.select('todos').first(),
      store.select('visibilityFilter').first()
])
```

**Comment by erictsai6** [comment]
Much appreciated, that solved it
