### ISSUE TITLE
compilation error between reducer and model, even though types are matching

### ISSUE THREAD

**Issue by jrmcdona** [ngrx/store#334]
Have you guys ever seen an issue when changing the model and changing the reducer initial state to match , you get a compilation error?

My reducer and my model are matching and no matter what variation of changes I try, it will not succeed.

Know what might be wrong?

HMR] bundle has 1 errors
client.js:161 ./ClientApp/app/reducers/ambassador.ts
(10,5): error TS2322: Type '{ id: number; username: string; totalXp: number; }' is not assignable to type 'Ambassador'.
  Object literal may only specify known properties, and 'totalXp' does not exist in type 'Ambassador'.

**Comment by brandonroberts** [comment]
You're gonna have to provide some more context, like snippets of the model and the reducer. There is also a support channel here: https://gitter.im/ngrx/store

**Comment by jrmcdona** [comment]
Cool, thanks for the supper link.  Will go check that out now.

Here is the reducer snippet:

Here is the full model:
```
export interface Ambassador {
    id: number;
    username: string;
    totalXp: number;
}
```

and here is the full reducer:
```
import { Action } from '@ngrx/store';
import { AmbassadorActions } from '../actions';
import { Ambassador } from '../models';

export type AmbassadorState = Ambassador;

const initialState: AmbassadorState = {
    id: 0,
    username: '',
    totalXp: 0
};

export default function (state = initialState, action: Action): AmbassadorState {
    switch (action.type) {
        case AmbassadorActions.GET_AMBASSADOR: {
            return initialState;
        }
        case AmbassadorActions.GET_AMBASSADOR_SUCCESS: {
            return action.payload;
        }
        default: {
            return state;
        }
    }
}
```

**Comment by brandonroberts** [comment]
Why not just use the `Ambassador` interface for your state interface instead of the `type`?

**Comment by jrmcdona** [comment]
I am trying to match your example now.  I was using this https://github.com/bodiddlie/rxheroes/blob/master/app/reducers/hero.ts  and it has a different set up.

**Comment by jrmcdona** [comment]
It is working after I changed it! Thanks
