### ISSUE TITLE
Calling a reducer with a null state doesn't set the state to the initialState.

### ISSUE THREAD

**Issue by simonkazakov** [ngrx/store#335]
Let's say I've this reducer r:
`function r(state = initialState action: Action): State {}`
If I call it with: `r(undefined, action) ` the state would be set to the initialState.
If I call it with `r(null, action) ` I would've expected the state to be set to the initialState, but it's set to null.
Is this the desired behaviour?

**Comment by bortexz** [comment]
I think it is the desired behaviour, as `null` could be the desired value of the state.

**Comment by rarmatei** [comment]
That's expected behavior. 

When you do `r(state = initialState)`, Typescript compiles that to: 

`
function r(state) {
  if(state === void 0) {
    return initialState;
  }
}
`

And: `undefined === void 0` is TRUE but `null === void 0` is FALSE. So by passing in null, it will not return the initialState.
