### ISSUE TITLE
Error while compile with angular-cli, Can't use 'conbineReducers'

### ISSUE THREAD

**Issue by ritox842** [ngrx/store#339]
Iv'e upgrade angular-cli to it's latest version (1.0.0-beta.31) and since then I'm getting the following error message:

> ERROR in Error encountered resolving symbol values statically. Calling function 'combineReducers', function calls are not supported. Consider replacing the function o
> r lambda with a reference to an exported function, resolving symbol rootReducer in XXX

Anyone knows how to fix it?

Thanks.

**Comment by wizardnet972** [comment]
maybe this will help: 
```
npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest
```

**Comment by brandonroberts** [comment]
@ritox842 are you exporting a function for the root reducer? See the example app https://github.com/ngrx/example-app/blob/master/src/app/reducers/index.ts#L74-L84
