### ISSUE TITLE
Memory leak with dispatcher

### ISSUE THREAD

**Issue by bhaniel** [ngrx/store#340]
Hi ,

I noticed that when we have a dispatcher that fire at x amount of time there is a leak with the QueueAction.

`      this.lobbySubscribe = Observable.interval(100).subscribe(() => {
        this.store.dispatch(this.lobbyActions.loadLobbyUpdate(deepClone(lobbyJson)));
      });`

Adding the images from the Heap Profile :
1.
![image](https://cloud.githubusercontent.com/assets/5826742/23013243/7b50e076-f432-11e6-9e57-55853d8d3cfe.png)
2.
![image](https://cloud.githubusercontent.com/assets/5826742/23013297/b4192328-f432-11e6-8af1-bc799a909229.png)

details :

Rxjs : 5.0.3
"@ngrx/core": "^1.2.0",
 "@ngrx/effects": "^2.0.0",
"@ngrx/store": "^2.2.1",

Thanks For the help

**Comment by orizens** [comment]
hi @bhaniel 
this seems to be an rxjs memory leak as referenced in a past issue - https://github.com/ngrx/store/issues/167
you should upgrade rxjs to the latest version

**Comment by bhaniel** [comment]
As I mentioned my rxjx is 5.0.3 also upgraded to 5.1.0 and the issue still there.
