### ISSUE TITLE
Reset form input after action completes

### ISSUE THREAD

**Issue by ArielGueta** [ngrx/store#344]
I have a dumb component that contains an input. When the user clicks on the add button, I'm emitting Output with the text. The smart component fetches the event and dispatch to the store.

How can I reset the input value after the action completes?

```
@Component({
  selector: 'add-post',
  template: "<input #post>
             <button (click)="add.next(post.value)">Add</button>
"
})
export class AddPostComponent {
  @Output() addPost = new EventEmitter();
}
```

**Comment by fxck** [comment]
Use angular's FormControl and pass it down from the smart component.

**Comment by ArielGueta** [comment]
Still, I don't have any way to know when the action completes. ( when you also call a side effect with ngrx/effects)

**Comment by fxck** [comment]
You didn't say you were using effects. You have couple of options, what I do is to import your effect and simply subscribe to it.

**Comment by ArielGueta** [comment]
Subscribe in my dumb or smart component?

**Comment by fxck** [comment]
```typescript
class DumbComponent {
  @Input()
  form: FormControl;

  @Output()
  addPost = new EventEmitter<string>();
}
```

```typescript
import { WhateverEffects } from '../whatever.effect';

class SmartComponent {
  form = new FormControl('');

  constructor(private _ef: WhateverEffects) {
    this._ef.onAddSuccess$.subscribe(() => this.form.reset);
  }
}
```

**Comment by ArielGueta** [comment]
This is awesome!
One last question, it will not be good practice if I will subscribe in my dumb component to save all the form work in my smart component?

**Comment by fxck** [comment]
Dumb components should just receive sync data and emit events, no injecting, no subscribing.

**Comment by ArielGueta** [comment]
OK! thanks a lot!
