### ISSUE TITLE
provideStore with AOT errors

### ISSUE THREAD

**Issue by JimLynchCodes** [ngrx/store#345]
I'm using the newest Angular CLI, and I'm getting this error when I run `ng serve` or `ng build`:

> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 7:3 in the original .ts file), resolving symbol mainStoreReducer in /.../, resolving symbol AppModule in /../, resolving symbol AppModule in /../, resolving symbol AppModule in /../

Is this still the best way to initialize Ngrx/store in the app module?

`StoreModule.provideStore({ counter: counterReducer })`

**Comment by brandonroberts** [comment]
The AOT compatible way of doing it is to return a function for the root reducer. See https://github.com/ngrx/example-app/blob/master/src/app/reducers/index.ts#L66-L84

**Comment by JimLynchCodes** [comment]
Thanks brandon!

My app.module is working now like this:

```
const reducers = {mainState: mainStoreReducer};

const developmentReducer: ActionReducer<MainState> = compose(combineReducers)(reducers);
const productionReducer: ActionReducer<MainState> = combineReducers(reducers);

export function reducer(state: any, action: any) {
  if (environment.production) {
    return productionReducer(state, action);
  }
  else {
    return developmentReducer(state, action);
  }
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    [MaterialModule],
    StoreModule.provideStore(reducer),
    EffectsModule.run(MainEffects),
    StoreDevtoolsModule.instrumentOnlyWithExtension(),
    AngularFireModule.initializeApp(firebaseConfig, {
      provider: AuthProviders.Anonymous,
      method: AuthMethods.Anonymous
    })

  ],
  providers: [],
  bootstrap: [AppComponent,
  ]
})
export class AppModule {
```

Since AOT is becoming pretty standard in Angular 2 and Angular CLI, it seems to me that it would be a good idea to mention this syntax in the README docs for Ngrx/store. What do you think? :)

**Comment by brandonroberts** [comment]
That may be something we'll add to the docs for V4
