### ISSUE TITLE
provideStore was deprecated? 

### ISSUE THREAD

**Issue by maxn0d3x** [ngrx/store#349]
I was looking for provideStore source code here  to check the logic inside.. I couldn't
Instead, I found  StoreModule.forRoot. I am not sure whether or not the method was deprecated from StoreModule because still so many blogs and tutorials and even examples(including offical ngrx book example too)are using provideStore() out there. Looks definitely need to update the document.(still no mention about this situation).
Also, I am interested in whether this project is almost stopped or not because the last update release was Sep. 2016.

**Comment by karolmie1** [comment]
Yes, its deprecated. Issue is described in release notes for 2.1.1, but i guess it needs to be documented smore.

And yeah, the project almost stopped, I'm waiting for important fix merge for month now ...
Nice thing it's that it's open source, so you can always fork and do your own fixes.
Other thing is that effects work nicely, and don't need many upgrades, except for better angular4 integration.

**Comment by loixlab** [comment]
Hum.... I don't know if you have the same as me, but for me in realease 2.1.1 it says:   

BREAKING CHANGE: users should import {StoreModule, Store} from '@ngrx/store' and provide the store as follows:

```js
import {StoreModule, Store} from '@ngrx/store'
import {NgModule} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

@NgModule({
  imports: [
    BrowserModule,
    StoreModule.provideStore(reducer, initialState)
  ]
})
```

So it says **to use** provideStore... not that it is deprecated... ?? I am also following the official app that does use provideStore... Where can we find the correct way to provide the store?

**Comment by brandonroberts** [comment]
In the current release, the above usage is the correct way to use provideStore. In the next major release(V4) `StoreModule.forRoot` will be the correct way to provide store.
