### ISSUE TITLE
Reducer on global state

### ISSUE THREAD

**Issue by thaiat** [ngrx/store#35]
Hi,

I understand that provideStore will map each reducer name to form the global state.
But how would you add a reducer that acts on the global state ?

**Comment by robwormald** [comment]
typically, you wouldn't. all state is pretty much "global" (or alternately, "no state is global") - maybe i'm misunderstanding your question?

**Comment by robwormald** [comment]
this is possible with the new middleware implementation, though that would typically be more for tooling use cases.

**Comment by Memeplexx** [comment]
I may be wrong, but I think what @thaiat is alluding to is something like this: https://github.com/reactjs/redux/issues/749. Seems like a valid use-case.

... and see this highly voted answer:
https://github.com/reactjs/redux/issues/749#issuecomment-164327121

@robwormald do you know if this is somehow possible with ngrx/store?
