### ISSUE TITLE
Is there a way to inject service into reducers?

### ISSUE THREAD

**Issue by naivefun** [ngrx/store#352]
One way would be to pass in with Action constructor, is there any `injectable` way for this? Because some of the data transformation depends on `formatService`. 

Thanks.

**Comment by Liork1** [comment]
Reducers are pure functions.
You should use an effects for it - inject your formatService into your effects, and dispatch a new action with the formatted paylod.

**Comment by SebastianStehle** [comment]
"Pure" means it should not have side effects, but I don't see how a formatService can violate this rule.
