### ISSUE TITLE
Handling Large size data inside the Store

### ISSUE THREAD

**Issue by noynir** [ngrx/store#353]
I have a dashboard app showing off a custom number of widgets. every widget has it's own data source and a user can change parameters for the widgets data. Widgets data could be quite large at times and regardless of size after rendering a chart widget, for instance, we don't need the data anymore. 
I was wondering what should be the best practice in this case:

- Should i save this data to the store, (not sure if this should be part of an app state)? should i worry about size of the store?

- The data parameters are part of the widget and dashboard state so basically i handle the filters change inside the normal flow so now i have a side effect of fetching the data, But if i don't persist the data to the store should i do it through an effect or better to just handle that inside a container component.
i was thinking of doing an effect with dispatch:false and have it call some kind of data service that will provide the data through an observable that is also consumed by the container component.

**Comment by orizens** [comment]
hi @noynir 
> Should i save this data to the store, (not sure if this should be part of an app state)? should i worry about size of the store?

keeping a (very) large data in js memory might influence the app, the browser and more. can you estimate the worst case scenario of "large" data that might be kept in the store? 

regarding the state - if you change the state of a widget and expect it to influence other parts in the app or in the store - then - this might be a good candidate for saving it in the store - although it could be saved in a dedicated class/object. 
Remember - if you delegate portions of any state to sub components while using "OnPush" detection strategy - then - change detection should be fast and precise and would not come with a performance penalty of recalculating the whole store.

>The data parameters are part of the widget and dashboard state so basically i handle the filters change inside the normal flow...

If i understand correctly, then "Filters" might be part of a reducer - managed for each widget (having a json database like stored by id/map).  

> i was thinking of doing an effect with dispatch:false ...
this kind of effect will not dispatch an action - or a side effect back to the store - this case is ok - but you have to make a decision whether this logic should be part of an app wide side effect class or rather an internal logic of a widget.

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
