### ISSUE TITLE
Using ngrx store with angular 2 AOT

### ISSUE THREAD

**Issue by ritox842** [ngrx/store#355]
Hey all.

I'm trying to use ngrx/store with angular 2 AOT but I'm facing difficulties.
I saw this issue 
https://github.com/ngrx/store/issues/190
It's very much the same and solved some of the problems I was faced with but still It wont compile.
I think the reason is that I have nested reducers in the root reducer level but I'm not sure.

This is my root reducer:

```
export function rootReducer() {
  return compose(combineReducers)({
    app: appReducer,
    event: eventReducer,
    lobby: LobbyReducer,
    betCard: combineReducers({
      staticData: betCardStatic,
      dynamicData: betCardDynamic,
      participants: participantsReducer
    }),
    betSlip: betSlip,
    openBet: openBetReducer,
    userProfile: combineReducers
    (
      {
        information: userInformationReducer,
        limits: limitsReducer,
        notifications: notificationsReducer
      }
    ),
    cashier: combineReducers({
      balance: cashierReducer,
      deposit: depositReducer
    }),
    myBets: myBetsReducer,
    edit: combineReducers({
      bet: editBetReducer
    }),
    social: combineReducers({
      connections: connectionsReducer,
      groups: groupsReducer
    }),
    privacy: privacyReducer
  });
}
```

And this is my app module :
` StoreModule.provideStore(rootReducer)`

The error Im getting is 
Uncaught TypeError: Cannot read property 'information' of undefined

Witch I'm guessing it's the reducer that's under 'userProfile' reducer.
Lastly, This is my  'userInformationReducer':

```
export function userInformationReducer(state = userInformationInitState, action: Action) {
.......
}
```

Anyone now how to solve it?

**Comment by brandonroberts** [comment]
Your reducers should take the `state` and `action` and return a new reduced `state`.

```ts
export function rootReducer(state, action) {
  const reducer = compose(combineReducers)({
    ...
  });

  return reducer(state, action);
}
```

See this example app root reducer for reference: https://github.com/ngrx/example-app/blob/master/src/app/reducers/index.ts#L66-L83

**Comment by ritox842** [comment]
Thanks a lot @brandonroberts !!

Finally it works!

**Comment by valimero** [comment]
Tanks a lot too @brandonroberts !

Thats works for me too !!!!
