### ISSUE TITLE
Is there a way to use external store instance?

### ISSUE THREAD

**Issue by dmnBrest** [ngrx/store#359]
I have unusual use case for my project. I need to create ngrx store manually and share it between to separate angular2 apps added to the page. Is there any way to do it? I can't find any examples. 
I tried it with angular-redux/store (https://github.com/angular-redux/store/blob/master/docs/quickstart.md - provideStore() method) and all works, but I can't find something similar in your docs. Please help me to get it work :) Thanks!

**Comment by drcmda** [comment]
One more voice. We deploy a library that internally uses Redux and frameworks can reflect that visually. I was surprised to learn that Angular bindings try to create the store instance. Is there a reason for that?

**Comment by robwormald** [comment]
If this is something you still need support for (should be possible, offhand) - please reopen on https://github.com/ngrx/platform. Thanks!
