### ISSUE TITLE
unmet peer dependency when using Angular CLI and Angular 4.0.0

### ISSUE THREAD

**Issue by dannypule** [ngrx/store#361]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

I'm using Angular Cli 1.0.0 which creates an Angular 4.0.0 project but this is listed as an unmet peer dependency. This is due to ngrx/store requiring "^2.0.0" in it's package json

Node version 6.9.6
npm version 3.10.10

**Comment by rkrisztian** [comment]
Please fix this, I need it for shrinkwrap:

```
$ npm shrinkwrap --dev
(...)
npm ERR! peer invalid: @angular/core@^2.0.0, required by @ngrx/effects@2.0.2
npm ERR! peer invalid: @angular/common@^2.0.0, required by @ngrx/router-store@1.2.5
npm ERR! peer invalid: @angular/core@^2.0.0, required by @ngrx/router-store@1.2.5
npm ERR! peer invalid: @angular/router@^3.0.0, required by @ngrx/router-store@1.2.5
npm ERR! peer invalid: @angular/core@^2.0.0, required by @ngrx/store@2.2.1
```

**Comment by JonathanYates** [comment]
This needs fixing urgently. Please can you provide a release for Angular 4 ASAP. Thanks.

**Comment by dietergoetelen** [comment]
Is there specific a reason why the peerDependency is fixed to `"@angular/core": "4.0.0-rc.1"`? Isn't it safer/better to allow minor upgrades for peerDependencies?

**Comment by rkrisztian** [comment]
@dietergoetelen, wrong ticket, good question. :)

**Comment by ZheyangSong** [comment]
Will this be shipped with next release? And is there a timeframe for the next release?

**Comment by mscudlik** [comment]
please provide the support for angular 4 :)

**Comment by brandonroberts** [comment]
We just got back from ng-conf this past week, so we'll need to finish up the next release but the peer dependencies issue will be fixed soon

**Comment by djindjic** [comment]
@brandonroberts, why closing this issue before its fixed with next release? I'm subscribed :D

**Comment by PaulH1** [comment]
@brandonroberts please could you tell me when the next release (with support for Angular 4) is due?

**Comment by jd-carroll** [comment]
@robwormald This is a critical issue...

If this issue is not appropriately handled in the next several days, then it demonstrates ngrx is not a maintained or production viable project.  Further, anyone looking to consume redux type patterns should look for some other alternative.

I get that this is an open source project and that everyone has a day job.  But as a member of the community, I *want* to help in whatever way I am able.  

If you are looking for PR's I will happily provide one

**Comment by brandonroberts** [comment]
@jd-carroll this project is very much alive and well. This issue has already been resolved in the ngrx platform monorepo: https://github.com/ngrx/platform

We are prepping the monorepo for an alpha release very soon which has full support for Angular version 4 along with the recommended package format.

**Comment by davefedele** [comment]
posting this here as this discussion is across a few places.

There is already a pr that could alleviate these issues as not everyone can switch repos at this time.

Thanks!

[https://github.com/ngrx/store/pull/389](https://github.com/ngrx/store/pull/389)
