### ISSUE TITLE
ActionReducer should be a class but not function

### ISSUE THREAD

**Issue by iron9light** [ngrx/store#362]
ActionReducer should be a class but not function.
So the reducer instance can be created by angular's DI system, then the reducer can use injectable services.
```typescript
export interface ActionReducer<T, V extends Action> {
  reduce(state: Readonly<T> | undefined, action: Readonly<V>): T;
}
```

**Comment by littleStudent** [comment]
why would you want to inject a service?

you **reducer** should be pure. It should **always** have the same output for the same input!!! Thats important.
So there are 2 cases that can happen if you were able to inject a service.

1. Your service has internal state or produces side effects. Which means you can not guarantee that the reducer which uses this service produces the same output for the same input. You dont want that!
2. If you can guarantee that the reducer which uses the service returns the same output for the same input, than your service does not have to be a service at all. But just a simple function. Which means you do not need DI.

Hope this makes sense?

**Comment by iron9light** [comment]
@littleStudent You know what, I think you're right, I wanna do something which produces **side effects**. I should use @ngrx/effects for that.
Thanks!
