### ISSUE TITLE
Any example to create store with sub stores ??

### ISSUE THREAD

**Issue by Dharam625** [ngrx/store#366]
Hi,

I am working on an admin tool which allows create/delete/update operations for tables. And then another configuration which uses these tables. This configuration also allows create/delete/update.

right now i am using multiple stores for each table and configuration which is ending up with many actions, reducers, effects etc. 

I want to create a common store at application level but not able to see any concrete example.
If anyone has or know how to do, please help. I would really appreciate.

Thanks in advance !!!

**Comment by altschuler** [comment]
I've had this same issue and solved it by augmenting the CRUD actions with a `context` property. I've made a generic `crudReducer` which basically does this (semi-pseudo code):

```ts
// reducer
makeCrudReducer(context: string) {
    return (state = initalState, action) => {
        // CRUD actions have the extra `context` property
        if (action.context !== context) {
            return state;
        }

        switch (action.type) {
            case CrudActionType.CREATE:
                ...
        }
    }
}
```

I use it with `combineReducers`:

```ts
// set the reducer/action context for each of the 'tables'
const reducer: ActionReducer<DataState> = combineReducers({
    people: makeCrudReducer('people'), 
    animals: makeCrudReducer('animals'),
});
```

And the actions have the following signature:
```ts
class CrudAction extends Action {
    // inherits the `type` and `payload`
    public context: string;
}
```

Now you can dispatch actions like:

```ts
// will be 'caught' by the `people` reducer
store.dispatch(new CrudCreateAction('people', { name: 'Alan Watts' });

// will be 'caught' by the `animals` reducer
store.dispatch(new CrudCreateAction('animals', { species: 'Cat' });
```

**Comment by Dharam625** [comment]
@altschuler thank you so much. I will try it. :)
