### ISSUE TITLE
Can't install @ngrx/store via npm

### ISSUE THREAD

**Issue by szerhusenBC** [ngrx/store#37]
I get an error if I want to install the package "@ngrx/store" like it is mentioned in the documentation.

I executed the following commands in an empty folder:

```
npm install angular2
npm install @ngrx/store
```

Angular has been installed fine, but when I then try to install the store I get the following error:

```
~/tmp/packagetest$ npm install @ngrx/store
npm WARN package.json packagetest@0.0.1 No repository field.
npm WARN package.json packagetest@0.0.1 No README data
npm http GET https://registry.npmjs.org/ngrx/store
npm http 404 https://registry.npmjs.org/ngrx/store
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@ngrx/store"
npm ERR! cwd /home/stephan/tmp/packagetest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/stephan/tmp/packagetest/npm-debug.log
npm ERR! not ok code 0
```

It doesn't work either when I declare the dependency (version "^1.2.1") in the package.json (incl. angular2) and then execute "npm install". I get the same error then.

I'm running NodeJS 0.10.25 with npm 1.3.10 under Ubuntu 64 14.04.4

**Comment by szerhusenBC** [comment]
Ok, forget about it. It was my fault. I installed NodeJS via Ubuntu's package system and this installed an outdated version. I installed the actual version manually and now it works!

(｡ >艸<)

**Comment by robwormald** [comment]
yeah, its an NPM versioning thing. I'll make a note to add it to the docs.

**Comment by zeeshanjan82** [comment]
I am getting the following error I have installed ngrx/store and ngrx/core from npm
![seed](https://cloud.githubusercontent.com/assets/8342604/15986213/d46fb4d4-301f-11e6-992f-c8bc6c281a11.png)
