### ISSUE TITLE
Implementing API data caching

### ISSUE THREAD

**Issue by ArielGueta** [ngrx/store#370]
Hi guys,

What would be the best way to handle caching the results of my API calls?
Has anybody successfully implemented caching with this library?

I tried to do something like this:

```
class TodosActions {
  
  getTodos() {
    this.store.select("todos").subscribe(todos => {
      if(todos.length) {  return todos; }
      this.store.dispatch(...)
    })
  }
}
```

But this will be an infinite loop.

Any suggestions?

**Comment by ArielGueta** [comment]
Maybe we need to add a method for getting the store value not as observable? Something like:
`this.store.getRawValue()`

**Comment by fxck** [comment]
Assuming you are using @ngrx/effects

```typescript
  @Effect()
  private _oneRequest$ = this._action$
    .ofType(todos.ONE_REQUEST)
    .withLatestFrom(
      this._store.select(getTodosSlice),
      (action, todos) => { 
        if (todos[action.payload]) {
          return undefined;
        } else {
          return action;
        }
    )
    .filter((action) => !!action)
    .switchMap((action) => this._api
      .one(action.payload)
      .map((response) => new posts.OneSuccess(response))
      .catch((err: ErrorData) => Observable.of(new todos.OneFail(err)))
    });
```

you select slice of store that contains todos you already have in state and end the effect (with filter) if the one you are requesting is already there, so the API call doesn't happen and effect doesn't return anything

**Comment by ArielGueta** [comment]
Thanks for the response. I have two problems with your approach.

1. My client does not use ngrx/effects. 
2. Usually the first action will change the `pending` key from the state to be true and the `SUCCESS/FAILURE ` actions will change this to false. In your example the `pending` key that will show the spinner will never change to false.

**Comment by ArielGueta** [comment]
I thinks it should be a simple solution like:

```
const todos = this.store.getRawValue().todos;
if(todos.data.length) return;
dispatch(getTodos());
```

**Comment by javico2609** [comment]
if you not used effect you can create BaseComponent and put this code or you can create util-store.ts, 
I hope it is useful
```
import { Store } from '@ngrx/store';
import 'rxjs/add/operator/take';
import * as fromRoot from './reducers';
 
export function getCurrentState(store: Store<fromRoot.State>): fromRoot.State {
    let state: fromRoot.State;
    store.take(1).subscribe(s => state = s);
    return state;
}
```
