### ISSUE TITLE
Setup Http Polling!

### ISSUE THREAD

**Issue by oberoivarun** [ngrx/store#373]
I want to setup http polling and iam using ngrx effects. I've tried to get some help from Stackoverflow but no successful answers yet. This might not be a github appropriate posting, but even the example app does not help here.

```
@Injectable()
export class TasksEffects {
    constructor(
        private actions$: Actions,
        private TS: TaskService
    ){}

    @Effect()
    onLoadTasksLoadTasks$: Observable<Action> = this.actions$.ofType(tasksActions.ActionTypes.LOAD_TASKS)
        .switchMap(() => {
            return this.TS.index()
                .map((res) => new tasksActions.LoadTasksSuccessAction(res.json()))
                .catch(err => of(new tasksActions.LoadTasksFailAction(err)));
        });
```

I want the switchMap internals to repeat every ten seconds. I've tried many different operators, `repeat`, `retry` coupled with `debounceTime`. Also tried to setup a `Observable.interval(10000)` with `combineAll`, but couldn't get it to work. 

Other help available online tells me that i should be using `interval(10000)`, but that gives an error. `Property interval does not exist on type 'Observable<LoadTasksFailAction>'`

Please advise.

http://stackoverflow.com/questions/43154461/ngrx-store-effects-http-ajax-polling-setup-on-angular-2

**Comment by oberoivarun** [comment]
Nevermind. Somebody finally helped on Stackoverflow. If anyone's interested in the answer, go to the link provided.

**Comment by brandonroberts** [comment]
:+1:
