### ISSUE TITLE
Add middleware that will skip action based on condition

### ISSUE THREAD

**Issue by ArielGueta** [ngrx/store#375]
I'm trying to figure out how to create a middleware that will check a property from the action and based on that will decide if to drop the action or not.

In simple redux I would do it like this:

```
store => next => action => {
    if(!action.payload.someBoolean) {
        next(action);
    }
}
```
How can I do this with ngrx/store? I can't find any useful docs about middlewares...

I'm sorry that I am saying this, but It seems that we are missing essential functionality with ngrx/store that will work as usual with angular redux.

**Comment by fxck** [comment]
There are no docs about middlewares simply because there is little to no middleware out there. 99% of what any redux middleware does is possible with @ngrx/effects. In your example you'd do

```typescript
@Effect()
private _whatever = this._action$
  // handle only action with `type` `WHATEVER_REQUEST`
  .ofType('WHATEVER_REQUEST')
  // end the stream if `action.payload.someBoolean` is false
  .filter((action) => !action.payload.someBoolean)
  // otherwise map the original action to a `*_SUCCESS` action, you can then handle in your reducer
  .map((action) => ({ type: 'WHATEVER_SUCCESS', payload: action.payload }));
```

you'd just need to utilise some sort of convention (it's usually `<name>_REQUEST/SUCCESS/FAIL`)

**Comment by ArielGueta** [comment]
The problem is that the `WHATEVER_REQUEST` will change the `fetching` key from my state to `true` and the spinner will be stuck forever. The check needs to be before `WHATEVER_REQUEST`.

**Comment by fxck** [comment]
Then do not use filter and put a condition inside that map, returning either SUCCESS or SKIP, both of which would set fetching to false.

**Comment by ArielGueta** [comment]
So I need to create a new action for each reducer? that's not DRY, with the original redux I just can do this globally like this: 
```
store => next => action => {
    if(!action.payload.isCached) {
        next(action);
    }
}
```

But unfortunately I can't do this with this library.

**Comment by fxck** [comment]
You can most likely do that as well, using a meta reducer https://gist.github.com/btroncone/a6e4347326749f938510#implementing-a-meta-reducer

**Comment by ArielGueta** [comment]
Yes, I saw this but it seems that you can't control the action it just controls the returning state, or am I missing something?

**Comment by chrissena** [comment]
@ArielGueta 
Can't you just do something like this?

```
// meta-reducer to ignore any actions with truthy isCached 
export const ignoreCached = reducer => {

    return function (state, action) {
        //check for property on action
        if(action.payload.isCached){
            //in this case ignore the action and return the same state
            return state;        
        }
        // if your action doesn't have the property value indicating you should ignore action
        // calculate next state as normal and return it
        return reducer(state, action);
    }
} 
```
Then when hooking up the store...
```
bootstrap(App, [
//wrap relevant state slice (or all state) in ignoreCached meta-reducer
provideStore({people: ignoreCached(people), partyFilter})
]);
```

This seems pretty DRY and analogous to the redux example you provided.
Although I am not exactly sure what you mean by...
>  you can't control the action it just controls the returning state

Surely it is the state that is returned by the (meta-)reducer that you are interested in controlling or am **I** missing something now?

**Comment by ArielGueta** [comment]
But how you pass the `ignoreCached` to all your reducers at once and not one by one like your example?

**Comment by chrissena** [comment]
@ArielGueta  In this example the root reducer is actually the combination of 2 childReducers. 

If you want to wrap all of the child reducers at once you need to manually apply combineReducers first (this is normally taken care of automatically behind the scenes by provideStore).

```
import { combineReducers } from '@ngrx/store';
import { compose } from '@ngrx/core';
.
.
.
bootstrap(App, [
//wrap relevant child reducer (or entire root reducer) in ignoreCached meta-reducer
provideStore( ignoreCached( combineReducers({people, partyFilter}) ) )
]);
```
or if you prefer you can compose both meta-reducers `compose( ignoreCached, combineReducers)`
to give....
```
bootstrap(App, [
//wrap relevant child reducer (or entire root reducer) in ignoreCached meta-reducer
provideStore( compose( ignoreCached, combineReducers)({people, partyFilter}) )
]);
```
If you haven't already, I strongly recommend reading about meta-reducers, reducers in general and other concepts in ngrx/store by reading this excellent guide [Comprehensive Introduction to @ngrx/store](https://gist.github.com/btroncone/a6e4347326749f938510) by @BTroncone. Everything above is covered in great detail there.

Hope that is clearer.

**Comment by ArielGueta** [comment]
Thank you very much I will check it.

**Comment by ArielGueta** [comment]
The problem is if I want to implement caching I can't because I can't access the state from my services. for example:

```ts
class TodosActions {

  getTodos() {
    if( // How can I check here if I already have todos in my state ) {
      return;
    } else {
       this.store.dispatch( { type: GET_TODOS } );
     }
  }
}
```
I don't want to dispatch the `GET_TODOS` action if I already have todos in my store. 

You can see from the implementation of redux docs that they use the plain state object to implement caching. 

```js
function shouldFetchPosts(**state**, subreddit) {
  const posts = state.postsBySubreddit[subreddit]
  if (!posts) {
    return true
  } else if (posts.isFetching) {
    return false
  } else {
    return posts.didInvalidate
  }
}

```
