### ISSUE TITLE
ngrx/store setup sample incorrect?

### ISSUE THREAD

**Issue by momoadeli** [ngrx/store#376]
Here: https://github.com/ngrx/store/blob/master/README.md

StoreModule.forRoot(...) is still being used. I imagine this has deprecated. Needless to say misleading if so

**Comment by krjordan** [comment]
Duplicate #349 

In the next major release `StoreModule.forRoot()` will be the correct way to provide store ([See Comment](https://github.com/ngrx/store/issues/349#issuecomment-285484572)). I agree that it is a bit misleading, but should be resolved with the next major release.

**Comment by thiagogjt** [comment]
Is there an estimate for the v4 release come out?

**Comment by brandonroberts** [comment]
We just got back from ng-conf this past week, so we'll need to finish up the next release but it will be soon
