### ISSUE TITLE
Do you have any plans for the next release ?

### ISSUE THREAD

**Issue by pimenovoleg** [ngrx/store#379]
When ?
What will include ?

**Comment by fxck** [comment]
https://github.com/ngrx/store/pull/269 / https://github.com/ngrx/store/issues/197#issuecomment-291488703 Also you could have asked on gitter, issues should be for bug reports and feature requests.

**Comment by pimenovoleg** [comment]
This is excellent, but is it planned to fix it in a text document (like Roadmap.md) ?
