### ISSUE TITLE
Support for Angular 4 (Ionic 3)

### ISSUE THREAD

**Issue by devmao** [ngrx/store#383]
Hi,

Soon I have to start a new project in Ionic 3 and I really want to use this great module but the question is, when do you think that you are able to release a stable version that supports Angular 4?

Thank you

**Comment by fxck** [comment]
It already does support angular 4.

**Comment by devmao** [comment]
yes in master but it's not released

**Comment by fxck** [comment]
No, the version on npm supports angular 4 just fine.

**Comment by devmao** [comment]
good but the latest version (2.2.1) has angular 2 as peer dep

**Comment by javico2609** [comment]
it's working fine in ionic 3, right now i used an do not have problem

**Comment by scrapcupcake** [comment]
Can confirm, am using store with Angular 4 just fine; the peer dep is annoying, for sure, but doesn't stop any actual code working.

**Comment by devmao** [comment]
Yes, it seems working well, at least on my simple app.
Btw, I'm also using these guys:
- effects
- store-devtools
- angularfire2
- reselect

Therefore, for now, I can ignore these npm warnings:
```
npm WARN @ngrx/effects@2.0.2 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/compiler@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN angularfire2@2.0.0-beta.7-pre requires a peer of @angular/platform-browser-dynamic@^2.0.0 but none was installed.
npm WARN @angular/core@2.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.2.1 requires a peer of zone.js@^0.6.21 but none was installed.
```

**Comment by pmulac** [comment]
It might technically work with Angular v4, but the old peer dependencies prevent the use of npm-shrinkwrap (this is critical for serious apps).  We really need a release that is compatible with v4.

**Comment by brandonroberts** [comment]
We just got back from ng-conf this past week, so we'll need to finish up the next release but it will the peer dependencies issue will be fixed.

**Comment by PG2000** [comment]
@brandonroberts Any news on that ?
