### ISSUE TITLE
ngrx store will be stored in memory?

### ISSUE THREAD

**Issue by BKB503** [ngrx/store#384]
Hi, 
I 'm newbie to angular 2 apps, I want to hold basic information data and share between other components of the application, so far I can see we can choose in 3 different ways of state management or correct me if I'm wrong
1) Redux or ng2 redux
2) Ngrx store 
3) Shared services which is singleton to share across the application
so if some answer my questions that would be great!
1) Redux  or Ngrx  store state stores in IndexDb or memory?,
2) if we close the browser will data be persistent or cleared off ?
3) if we store in indexdb or localstorage how long it will be? or we need to clear based on the requirements
4) Any example with local storage encryption and decryption would be great.

**Comment by orizens** [comment]
> 4. Redux or Ngrx store state stores in IndexDb or memory?

both store in memory  
there are extentions to sync to local storage and indexeddb (ngrx/db in beta though)
> 5. if we close the browser will data be persistent or cleared off ?

if no persistent storage extension is available - then, data is cleared off
> 6.  if we store in indexdb or localstorage how long it will be? or we need to clear based on the requirements

that in the developer's responsibility. Also, check browser's docs for these

**Comment by BKB503** [comment]
@orizens its really helpful from your comments and in regards to encryption and decryption we need to write our own mechanism or some thing library is offering?
