### ISSUE TITLE
Offline capabilities

### ISSUE THREAD

**Issue by maxime1992** [ngrx/store#385]
I've been reading a lot of things lately about offline state management and I was wondering if that was possible with `Redux` (and `ngrx`).

I've found [ngrx roadmap](https://github.com/ngrx/ngrx.github.io/wiki/Roadmap) and saw something interesting : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788403/a6f32b1e-1b6d-11e7-8e30-2a3b448a8620.png)

Then I also took a look into https://github.com/btroncone/ngrx-store-localstorage and it seems quite nice but also very simple and I don't think that it's going to handle retry, synchronisation, rollback, etc.

Luckily, I saw a brand new repo on Github which seems very promising : [Redux Offline](https://github.com/jevakallio/redux-offline). And I was wondering if it would be possible to integrate it with `ngrx` ? Because with `ngrx` we declare our store like that : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788504/309d1492-1b6e-11e7-81c5-6cadc51aa5be.png)

And with `Redux Offline` there's a function `createOfflineStore` : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788525/4be2f906-1b6e-11e7-82dc-b7cbeda2dc37.png)

Also, it seems that effects are handled by `Redux Offline` : 
![image](https://cloud.githubusercontent.com/assets/4950209/24788543/6b16642a-1b6e-11e7-822f-2b9391792c09.png)
and I'm not too sure how it stands with `ngrx/effects`.

There is obviously some work needed to make them work together (if it's possible in the first place) but it seems to be worth it and I'd love to have some feedback about that.

Angular claims to be for every paltforms 
![image](https://cloud.githubusercontent.com/assets/4950209/24788634/dd76aa34-1b6e-11e7-9cac-4c6c6eb032ad.png)

![image](https://cloud.githubusercontent.com/assets/4950209/24788649/f3b3c7fa-1b6e-11e7-802e-c339d316251b.png)

and it's trully a good think. But unless we use `Firebase` or something equivalent, it seems that the synchronization layer is going to be hard to handle (at least if we use redux/ngrx as state management and not directly a browser database, puchDb, etc).

As we're all hearing more and more about PWA awesomeness and how well Angular can be for mobiles (with code splitting, lazy loading, improved change detection, AOT for pre-compiled templates, etc) I think that the next big battle is going to be related to offline capabilities and how to handle the synchronization of the data.

If you have any idea that could hep me figure out how to do that (already ?) with `ngrx` or if you have any knowledge about that topic, please let me know :smile:.

PS : It might not be considered as an issue but this is way too opinionated to go on stackoverflow and needs some serious answer with I hope a lot of content and I don't think it's a good idea to post that on Gitter, that's why I opened it here.

**Comment by orizens** [comment]
hi @maxime1992 
I'm using https://github.com/btroncone/ngrx-store-localstorage for localstorage sync.

**Comment by maxime1992** [comment]
@orizens I've seen `ngrx-store-localstore` and it seems great to handle persistency. But how you handle optimistic or pessimistic UI updates, how you retry to post/get some data, how you rollback an action (if you go for optimistic UI updates) ... It's up to you here.

To me, ngrx-store-localstorage feels like a good start but also that in order to be offline compliant, things remain to do. Maybe ngrx-store-localstorage might be the first brick of a bigger thing ?

I also watched the conf about `Logux` : https://www.youtube.com/watch?v=UUvX7US8TSc which seems great but goes even further than `redux-offline`. Do you see what I mean @orizens ? :)

**Comment by MikeRyanDev** [comment]
Yes, we plan on introducing an `@ngrx/offline` library in 2017. Unlike redux-offline, we plan on building this into @ngrx/effects.

Without getting too ahead of ourselves imagine applying an `@Offline()` decorator to an effect that makes an Http request:

```ts
class BookCollectionEffects {
  @Effect() @Offline() saveCollection$ = this.actions$
    .ofType(BookActions.SAVE)
    .mergeMap(action =>
      this.http.patch(`/book-collection/${action.payload.id}`, action.payload.changes)
        .map(response => new BookActions.SaveSuccess(response))
        .catch(error => of(new BookActions.SaveFailure(error))
      )
    );
}
```

 😉

**Comment by MikeRyanDev** [comment]
Closing as this isn't Store related.

**Comment by maxime1992** [comment]
Can't wait ! Thanks @MikeRyanDev 
(PS : Your [ng-conf](https://youtu.be/cyaAhXHhxgk) talk with @brandonroberts was :ok_hand: congrats !!)
