### ISSUE TITLE
StoreModule.provideStore does not work in child modules

### ISSUE THREAD

**Issue by sijeesh-02** [ngrx/store#386]
StoreModule.provideStore({ app: appReducer , issuer: issuerReducer }) is working when imported in root module and not in child modules.

_I am supposed to use this reducer in child module's components only_

**Comment by mlakhara** [comment]
You do not need to use provideStore again in the child module if you have already done in the root module. If you have lazy loaded modules you can follow this issue. [https://github.com/ngrx/store/issues/197](https://github.com/ngrx/store/issues/197)

**Comment by sijeesh-02** [comment]
Why should I give provide store for all reducers in root module ?

**Comment by brandonroberts** [comment]
You should only provide the store once in the root module to give your app the global Store instance. In the next major release, there will be support for lazy loading reducers.
