### ISSUE TITLE
Production build error

### ISSUE THREAD

**Issue by flauc** [ngrx/store#387]
I know this is probably something with my config, but any help is greatly appreciated. 

I get this error when running AoT build with webpack. 

```
\node_modules\@ngrx\store\src\ng2.js:1
(function (exports, require, module, __filename, __dirname) { import { OpaqueToken, NgModule } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```
The strange thing is that all other packages work fine, only `@ngrx/store`.  This is version 2.2.1

**Comment by brandonroberts** [comment]
Can you share your webpack config?

**Comment by flauc** [comment]
Yes, thank you so much for looking in to it. I'm using a clone of this repo: 

https://github.com/FrozenPandaz/ng-universal-demo

**Comment by brandonroberts** [comment]
Do you have a branch with store that reproduces this issue?

**Comment by teleaziz** [comment]
were you able to fix this? I'm running on the same issue on node when trying to use universal with ngrx

**Comment by teleaziz** [comment]
I ended up adding ngrx to webpack externals in server build config to fix it, something like this https://github.com/angular/universal-starter/blob/master/webpack.config.ts#L87

**Comment by kevinlllR** [comment]
Teleazis, sorry how you ended up adding it? , Then I try the following way and the same error still comes out.
I also use the frozen repository.

```
 externals: [nodeExternals({
      modulesFromFile: true
    }),includeClientPackages(
    /@angularclass|@angular|angular2-|ng2-|ng-|@ng-|angular-|@ngrx|ngrx-|@angular2|ionic|@ionic|-angular2|-ng2|-ng/
  )]
```

**Comment by kevinlllR** [comment]
I added as it is in your repository, but I get the following error
Error: No NgModule metadata found for '[object Object]'.

```
  const serverConfig = webpackMerge({}, commonPartial, serverPartial, {
    entry: options.aot ? './src/main.server.aot.ts' : serverPartial.entry, // Temporary
    plugins: [
      getAotPlugin('server', !!options.aot)
    ],
    externals: [nodeExternals({
      modulesFromFile: true,
      whitelist:[/@angularclass|@angular|angular2-|ng2-|ng-|@ng-|angular-|@ngrx|ngrx-|@angular2|ionic|@ionic|-angular2|-ng2|-ng/]
    })
    ]
  });
```

**Comment by bassrock** [comment]
@kevinlllR  I am experiencing sort of the same issue which I described here: https://github.com/ngrx/store/issues/408

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
