### ISSUE TITLE
Bug: integration.spec.ts: Type 'State' is not generic

### ISSUE THREAD

**Issue by dietergoetelen** [ngrx/store#388]
I'm getting an error when I try to build the latest version of ngrx/store.

**Problem** 
`integration.spec.ts` has an import of `State`, this file is expecting a generic type of `State` while `State` isn't generic anymore.

**Proposal**
Add a generic constraint or is there any reason why `State` isn't generic anymore? 
The compiler seems happy after  changing: 
```
export class State extends BehaviorSubject<any> implements OnDestroy
```

to

```
export class State<T> extends BehaviorSubject<T> implements OnDestroy
```

**Comment by brandonroberts** [comment]
These changes have been implemented in the monorepo where we are migrating the packages: https://github.com/ngrx/platform
