### ISSUE TITLE
Is this specific to angular?

### ISSUE THREAD

**Issue by emmanuelbuah** [ngrx/store#39]
Great library and for anyone that understand the core/concept of redux, they will understand that Rx offers that and more. My only question is, couldn't a redux store implementation using Rx have been achieved without coupling it with angular. Ex. redux isn't glued to react or any other framework. Its just a state management lib. Why not implement this the same way as another option to redux and offer specific(if any) binds to ng as an integration project just like redux offer a react integration. 

I'm asking because I think there is fatigue with the whole angular/react ++ and its always great to have these libraries that focus on their core disciplines without hinging to a framework. Just a thought. Users might just assume this is just for angular which is not the case. Or is it?

**Comment by robwormald** [comment]
as of today, yes - that's mainly because the focus of ngrx as an org is stuff for angular2. that said, there's a PR pending with a bit of a refactor to loosen that restriction, and i'd certainly consider publishing a standalone package once that's ready.
