### ISSUE TITLE
Switch in builder to select store

### ISSUE THREAD

**Issue by kevinlllR** [ngrx/store#392]
Is there any way to do the following or something equivalent in the constructor of any component?

Switch (this.options){ // @Input() options;
case 'A'{
     this.list = this._store.select ('gameA');
    break;
}
case 'B':{
     this.list = this._store.select ('gameB');
     break;
}
}

**Comment by bertrandg** [comment]
Better do this inside `ngOnChanges` hook to keep your list variable sync to latest `@Input()` changes:

``` js
ngOnChanges(changes) {
    if(changes.options) {
        this.list = this.store$.select( this.options === 'A' ? 'gameA' : 'gameB' );
    }
}
```

**Comment by fxck** [comment]
Uhm.. I'd rather do something along these lines

```typescript
options$ = new BehaviorSubject(null);
list$ = this.options$.switchMap((options) => this.store$.select(options === 'A' ? 'gameA' : 'gameB'));

@Input()
set options(v) { this.options$.next(v); }
```

**Comment by kevinlllR** [comment]
thanks
