### ISSUE TITLE
@ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed

### ISSUE THREAD

**Issue by mickeyjohn** [ngrx/store#394]
Hi,
I got "npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed." after npm installing into Agular 4 app. Is it comptible with angular v4 ?

Thanks,
John

**Comment by krjordan** [comment]
Yep, just currently has unmet `peerDependencies`. Check out [issue 383](https://github.com/ngrx/store/issues/383) and [issue 361](https://github.com/ngrx/store/issues/361) for more info.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/store/pull/395
