### ISSUE TITLE
Triggering Angular2 change detection manually

### ISSUE THREAD

**Issue by macdosi** [ngrx/store#396]
What is the correct way to inform cd about store change if it was triggered inside of an event outside angular  ? 
Let say I'm using 3rd party lib that I have event listener attached to it 
`myLib.on('event1' , ()=> { updateStore(); } )`   
I can see that every place with subscription to this store is updated but not inside templates with async filter .

**Comment by dominikstrasser** [comment]
I'm using NgZone in this case (firebase)
```
myLib.on('event1' , ()=> { this.zone.run(()=>updateStore() ) } )
```

**Comment by macdosi** [comment]
Doesn't work. bare in mind the operation 
`myLib.on('event1' , ()=> { updateStore(); } )`
is taking place at the server, so Zone will have no effect on CD.
