### ISSUE TITLE
@ngrx/store@2.2.2 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.

### ISSUE THREAD

**Issue by cloudscape-germany** [ngrx/store#399]
`@ngrx/store@2.2.2 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.`

Could you please update to current RXJS and current Angular 4 release?

**Comment by brandonroberts** [comment]
The dependencies are already up to date. If you have the latest stable of RxJS in your dependencies you will not receive the peer dependencies message.
