### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by curlyfro** [ngrx/store#40]
i'm trying to install via npm: 'npm install @ngrx/store' and i'm getting the error 'Invalid name: "@ngrx/store"'.

what am i doing wrong?

**Comment by CoderMonkies** [comment]
npm install @ngrx/store

This works for me, try clearing out npm cache with 

> npm cache clear

**Comment by curlyfro** [comment]
tried it... still no dice.

c:\Development\Svn\AdMgr\AdManager>npm cache clear

c:\Development\Svn\AdMgr\AdManager>npm install @ngrx/store
npm ERR! unpack Could not read data for @ngrx/store@1.2.1
npm WARN install:@ngrx/store@1.2.1 Invalid name: "@ngrx/store"
npm WARN admanager@0.0.0 No description
npm WARN admanager@0.0.0 No repository field.

c:\Development\Svn\AdMgr\AdManager>npm install @ngrx/store
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "@ngrx/store"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! Invalid name: "@ngrx/store"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Development\Svn\AdMgr\AdManager\npm-debug.log

**Comment by robwormald** [comment]
The two things that usually cause this error are a) an outdated version of NPM (yours looks OK) or b) using some sort of internal / private NPM registry (eg Artifactory) - does the 2nd apply to you?

**Comment by curlyfro** [comment]
no, i'm only using the public npm registry.  i tried at home and at work -- same error.

**Comment by curlyfro** [comment]
it installs now.  YAY!
