### ISSUE TITLE
un wanted reducers emit

### ISSUE THREAD

**Issue by ofirrifo** [ngrx/store#400]
Hi,

I have 3 reducers 
`StoreModule.provideStore({filter: filterReducer, templates: templatesReducer, header: headerReducer}),`

and I  saw that when I dispatch event all the reducers are executed which trigger each subscriber in my component which make server call more then once;

For example:
let say I have 2 reducers: aReducer, bReducer
and one of the components dispatch event that related to  aReducer.
now both reducers: aReducer, bReducer are executed.
aReducer find the relevant type action which is good but
bReducer not find the type action so it go to the default and return state
now in one of my component I have subscription to each one of them
this.store.select(this.FILTER).subscribe(() =>{});
this.store.select(this.TEMPLATES).subscribe(() =>{});

how can I avoid it.

Thanks

**Comment by jotatoledo** [comment]
Could u either reproduce ur problem with a plnkr or reformulate ur question? Im having troubles zo understand you situation.
Thx

**Comment by richarddavenport** [comment]
@ofirrifo  In Redux all reducers are called. When an action is dispatched every reducer function gets executed.

**Comment by ofirrifo** [comment]
@richarddavenport  Thanks.
is there a way to avoid it?
since when all reducers are called the default state return and then I have subscriber that get data from server which I don't need.

**Comment by brandonroberts** [comment]
@ofirrifo can you provide more info about your selectors? Your subscribers should only get updates when the data has changed if you're using `store.select`

**Comment by ofirrifo** [comment]
@brandonroberts is there any option to get help via skype?

**Comment by karptonite** [comment]
@ofirrifo what is your default state? if you are returning a new object each time by the reducer for the default state, that would cause the behavior you are describing. If you are able to return the same object (as in, same reference, not just same content), then that shouldn't register as a data change. Also, are you filtering on the action types in your reducers? as long as you are returning `state` when an action type does not match, and using `store.select`, this shouldn't trigger a new event.

**Comment by ofirrifo** [comment]
@karptonite 
I return the default state and no new state;
if it will help I can take a video of what happened when I debug my code.

## here is one of my reducer:

`

    export function filterReducer(state: Filter = new Filter(), action: FilterAction) {
      let _state;
      switch (action.type) {
        case FILTER_ACTION_OPTIONS.CLEAR_ALL_FILTERS_CLICKED:
          return new Filter();
    
            case FILTER_ACTION_OPTIONS.FILTER_BY_FREE_TEXT_CHANGED:
          return _.merge({}, state, action.payload);
    
        case FILTER_ACTION_OPTIONS.DEVICE_TYPE_CHANGED:
          return _.merge({}, state, action.payload);
    
        case FILTER_ACTION_OPTIONS.DIMENSION_ADDED:
          _state = _.merge({}, state);
          _state.dimensions.push(action.payload.dimensions[0]);
          return _state;
    
        case FILTER_ACTION_OPTIONS.DIMENSION_REMOVED:
          _state = _.merge({}, state);
          _.remove(_state.dimensions, {id: action.payload.id});
          return _state;
    
        case FILTER_ACTION_OPTIONS.VERTICAL_ADDED:
          _state = _.merge({}, state);
          _state.verticals.push(action.payload.verticals[0]);
          return _state;
    
        case FILTER_ACTION_OPTIONS.VERTICAL_REMOVED:
          _state = _.merge({}, state);
          _.remove(_state.verticals, {id: action.payload.id});
          return _state;
    
        case FILTER_ACTION_OPTIONS.AUTHORING_TOOLS_TYPE_CHANGED:
          return _.merge({}, state, action.payload);
    
        case FILTER_ACTION_OPTIONS.FILTER_LOADED:
          return state;
    
        default:
          return state;
      }
    }

`

## and My component code that subscribe 


@Component({
  selector: 'tg-template-list',
  templateUrl: 'template-list.component.html',
  styleUrls: ['template-list.component.scss']
})
export class TemplateListComponents implements OnInit {
  templates$: Observable<ITemplate[]>;
  filter: IFilter;
  showEmptyState = false;
  showSpinner = false;
  goToTop = {};
  serverTotalTemplates = 0;
  selectedFormatType: IFormat;
  FORMAT_ID = "formatId";
  isFormatView: boolean;

  constructor(private templatesDataService: TemplatesService,
              private storeService: StoreService,
              private route: ActivatedRoute) {
  }

  ngOnInit(): void {
    this.route.parent.params.subscribe(this.onRouteChange.bind(this), this.onChangeRouteError);

    this.storeService.subscribeToOnFilterChange(this.onFilterChange.bind(this));
    this.templates$ = this.storeService.getTemplatesObservable();
  }

  onFilterChange(filter: IFilter): void {
    const payload = this.templatesDataService.createFilterPayLoad(filter, 0);

    this.showSpinner = true;
    this.templatesDataService.getServerTemplates(payload)
      .subscribe(this.onFilterSuccessGetTemplate.bind(this), this.onChangeRouteError);
  }

  onRouteChange(params: Params): void {
    this.isFormatView = params[this.FORMAT_ID] !== undefined;

    if (this.isFormatView) {
      this.selectedFormatType = FORMATS.find(format => {
        return format.id === params[this.FORMAT_ID];
      });
    }
  }

  loadMoreTemplates(): void {
    const templates = this.storeService.getTemplateState();
    const from = templates.length;

    if (from < this.serverTotalTemplates) {
      const filter = this.storeService.getFilterState();
      const payload = this.templatesDataService.createFilterPayLoad(filter, from);

      this.showSpinner = true;
      this.templatesDataService.getServerTemplates(payload)
        .subscribe(this.onLoadMoreSuccessGetTemplate.bind(this), this.onChangeRouteError);
    }
  }

  onFilterSuccessGetTemplate = (response): void => {
    let templates: ITemplate[] = this.extractTemplatesFromResponse(response);
    this.showEmptyState = templates.length === 0;
    this.storeService.dispatch(TEMPLATE_ACTION_TYPES.DATA_LOADED, templates);
    this.goToTop = {};
  };

  extractTemplatesFromResponse(response): ITemplate[] {
    this.showSpinner = false;
    this.serverTotalTemplates = response.metadata.total;
    return response.result;
  }

  onLoadMoreSuccessGetTemplate(response): void {
    let templates = this.extractTemplatesFromResponse(response);
    this.storeService.dispatch(TEMPLATE_ACTION_TYPES.LOAD_MORE_DATA, templates);
  }

  onChangeRouteError = (): void => {
    this.showSpinner = false;
  };

}
`

**Comment by karptonite** [comment]
One potential issue I see: you do the default as `state: Filter = new Filter()`. Try instead something like:
```typescript
const defaultFilter = new Filter();
export function filterReducer(state: Filter = defaultFilter, 
```
I'm not sure if that is an issue, but it will at least help eliminate a potential problem.

Also, be aware that while there is no technical reason you can't use your Filter class as part of `state`, if you want to use the redux devtools for debugging, I believe that you are best off sticking to plain objects for your state, defined by interfaces.

Also, make sure that your Filter change selector excludes events where there is a transition from null or undefined to the default filter.

**Comment by ofirrifo** [comment]
@karptonite 

Thanks, I will try it

**Comment by jotatoledo** [comment]
You should take a look at the example app, and try to apply some of the concepts in it on ur application

**Comment by ofirrifo** [comment]
Finally I found my problem.

I had a subscriber which I didn't unsubscribe and once I fix it everything is good.

Thanks for you'r help.

**Comment by jotatoledo** [comment]
@ofirrifo consider closing the issue if its solved
