### ISSUE TITLE
ngrx store not working in production build

### ISSUE THREAD

**Issue by whizkidwwe1217** [ngrx/store#401]
ngrx store's **subscribe** does not work when building in production (ng build --prod) using angular-cli but is working perfectly fine in development mode (ng build)

Version: **ngrx/store (2.2.2 or 2.2.1)**

_see code snippets below:_

**app.store.ts**
```
export interface AppStore {
    pages: Page[];
}
```
**app.module.ts**
```
imports: [
    ...,
    StoreModule.provideStore({ PageReducer })
  ]
```
**home.component.ts**
_in the constructor, the subscription to ngrx always returns null 'data'_
```
export class HomeComponent implements OnInit {
    pages: Observable<Page[]>;

    constructor(private router: Router, private store: Store<AppStore>, private pageService: PageService) {
        this.pages = this.store.select("PageReducer");
        this.pages.subscribe((data) => {
            console.log(data);
        });
    }
    
    ngOnInit(): void {
        this.pageService.getPages().then((p) => {
            console.log(p);
           this.store.dispatch({ type: "GET_PAGES", payload: p });
        });
    }
}
```
**home.component.html**
_even the async pipe does not work in production build_
` *ngFor="let page of pages | async">`

**page.reducer.ts**
```
import { Observable } from 'rxjs';
import { Store, Action, ActionReducer } from '@ngrx/store';
import { select } from '@ngrx/core';
import { Page } from "app/shared/page";

export const PageReducer = (state: Page[], action: Action): Page[] => {
    switch (action.type) {
        case "GET_PAGES":
            return action.payload;
        default:
            return state;
    }
}
```

**Comment by LancerComet** [comment]
+1, same problem :(

**Comment by brandonroberts** [comment]
Can you reproduce this in a plunker or github repo? Not the full app, just a small reproduction of the issue.

**Comment by whizkidwwe1217** [comment]
@brandonroberts Please take a look at this plunker:
[https://plnkr.co/edit/8HRU67KIAn97VJUjhqvM?p=preview](https://plnkr.co/edit/8HRU67KIAn97VJUjhqvM?p=preview)
I don't how to build that in production mode using plunker. I am using angular-cli command: ng build --prod and it's not working.

**Comment by brandonroberts** [comment]
There is usually an error produced when using the reducers object with AOT. Try updating your page.reducer.ts file like below:

```ts
import { Store, Action, ActionReducer, combineReducers } from '@ngrx/store';
import { select, compose } from '@ngrx/core';
import { Page } from "./page";

export function PageReducer(state: Page[], action: Action): Page[] {
    switch (action.type) {
        case "GET_PAGES":
            return action.payload;
        default:
            return state;
    }
}

export const reducers = {
  PageReducer
};

export const rootReducer = compose(combineReducers)(reducers)
export function reducer(state, action) {
  return rootReducer(state, action);
}
```

Then in your `AppModule`

```ts
imports: [ BrowserModule, StoreModule.provideStore(reducer) ],
```

**Comment by whizkidwwe1217** [comment]
I have no idea what you did there but I got it working with your code above. Thanks man. 👍
