### ISSUE TITLE
Storing key value pair in store

### ISSUE THREAD

**Issue by blaur** [ngrx/store#402]
Hi guys,

I have just recently started working with ngrx/store and excuse me if this is a simple question. I have not been able to find help anywhere so I am hoping to get some help by some experts in here.

First of all, I fully understand the example provided about the counter. What I have difficulty implementing myself is expanding that logic to take a "general" store with key value pairs. I do not wish to create a store per each of my objects  but I want one for all of my domain data model which can then be pulled from that same store. 
Since the objects are immutable I am not able to alter/extend objects in the store so I am looking for a way to implement this.

Any suggestions on how to achieve this?

Thanks in advanced and have a great day!

/B

**Comment by orizens** [comment]
hi @blaur 
you can use a ```Map<type-of-choice, type-of-choice>``` as for an app's reducer:
```typescript
interface IAppStore {
  store: Map<any, any>;
}
```
however, you can also create a more generic interface:
```typescript
interface IAppStore {
  [key: string]: any;
}
```

**Comment by blaur** [comment]
Hi orizens, 

I was indeed looking for the Map<any, any>. Thank you very much!

/Brian
