### ISSUE TITLE
General Question - handle a lot of updates

### ISSUE THREAD

**Issue by dominikstrasser** [ngrx/store#407]
hey guys :)

On startup i've got a lot of items to dispatch to my store. So changeDetection will fire a lot and causes my app to be quite unresponsive on startup. 
Example -> i've got a few chats and load the relevant user informations async on startup. 

My Question is - how do you guys handle this issue?

To solve this i'm using `sampleTime` (combined with onPush and cdRef.markForCheck) to decrease the number of times angular needs to run changeDetection.

```
this.store.select(getUserState)
      .sampleTime(100)
      .subscribe((user) => {
        this.user = user;
      });
```
It really decreases the number of changeDetection loops significantly 
but it has a few side effects and i'm not really happy with the solution...

I know it's a pretty general question but maybe someone can tell me his/her opinion on this matter :)

**Comment by crysislinux** [comment]
Is there a chance for you to batch the HTTP request? I guess that you are issuing a lot of requests for each user or chat.

**Comment by dominikstrasser** [comment]
Hey :)

No i'm afraid not - i'm using Firebase and my code is more reactive than active ;)
Maybe i try to batch the store dispatch...
So right now i'm saving performance in the components by using `sampleTime(100)` 
But `sampleTime` works with some kind of timeouts which run every 100ms and causes my cd run every 100ms...
If i figure out a decent solution i will let you know :)
If someone else has solved a similar problem please tell me :D

**Comment by robwormald** [comment]
You might consider batching your *actions*, rather than state notifications, and having your reducers handle a "meta" action. 

Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
