### ISSUE TITLE
Failing unit test on selector which uses createSelector, can you help?

### ISSUE THREAD

**Issue by daBishMan** [ngrx/store#410]
Hello, 

I am having a problem unit testing a selector which I pass a value to.  I am using reselect.

I am trying to follow the official example:  
https://github.com/ngrx/example-app/blob/master/src/app/reducers/book.spec.ts 

My selectors code:
`
export const getProfileSearchState = (state: ApplicationState) => state.profileSearch;

export const isProfileSelectedSelector = (selectedProfile: SelectedProfile) =>
  createSelector(getProfileSearchState, (state) => {
    const isSelected = (_.findIndex(state.selectedProfiles, item => item.id === selectedProfile.id)) >= 0;
    return isSelected;
  });`

My Test Code:
`
it('getProfileSearchState should return profileSearchState from ApplicationState', () => {
    const results = getProfileSearchState(testingApplicationState);
    expect(results).toBe(testingApplicationState.profileSearch);
  });
  
 xit('isProfileSelectedSelector should return true if profile exists in ProfileSearchState.SelectedProfiles', () => {
    const results = isProfileSelectedSelector(firstSelectedProfile);
    expect(results).toBe(true);
  });
`

I get the following error:
` Failed Tests:
 ProfileSearchReducer Selections:
    isProfileSelectedSelector should return true if profile exists in ProfileSearchState.SelectedProfiles
       Chrome 58.0.3029 (Windows 10 0.0.0)
          1) Expected Function to be true.
             at Object.<anonymous> (webpack:///src/app/stateStore/reducers/profile-search-reducer.spec.ts:137:20 <- src/test.ts:40186:25) [ProxyZone]
             at ProxyZoneSpec.Array.concat.ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- src/test.ts:117772:39) [ProxyZone]
             at Zone.run (webpack:///~/zone.js/dist/zone.js:113:0 <- src/polyfills.ts:2816:43) [<root> => ProxyZone]
             at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:117487:34) [<root>]`

**Comment by dmytroyarmak** [comment]
@daBishMan 
The problem is that in your code `isProfileSelectedSelector(...)` returns result of `createSelector(..)` and it returns `Function`. So it's why you have `1) Expected Function to be true` in your test report.

To fix your test you need to call `isProfileSelectedSelector` "twice" - first time with `firstSelectedProfile` and after that call returned function with your `testingApplicationState`:

```
it('isProfileSelectedSelector should return true if profile exists in ProfileSearchState.SelectedProfiles', () => {
  const results = isProfileSelectedSelector(firstSelectedProfile)(testingApplicationState);
  expect(results).toBe(true);
});
```

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
