### ISSUE TITLE
Reducer to change multiple states

### ISSUE THREAD

**Issue by cristianqr** [ngrx/store#414]
I can't find the way to create a reducer that changes multiple state, the API Rest returns nested data, which I normalize using normalizr library. Here is my code.

**Api returns data:**
`
[
{id: 1, firstName: 'CRISTIAN', lastName: 'QUISPE', country: {id: 1, name: 'PERU'}},
{id: 2, firstName: 'ISRRAEL', lastName: 'ALCAZAR', country: {id: 10, name: 'ESPAÑA'}}
]
`

**Schema normalizr:**
import {schema} from 'normalizr';
export const country = new schema.Entity('countries');
export const person = new schema.Entity('people', {
     country: country
});

**Normalized data:**
<img width="315" alt="screen shot 2017-05-11 at 7 58 18 pm" src="https://cloud.githubusercontent.com/assets/7727204/25977875/5f327b9a-3684-11e7-80f5-d3f10907211e.png">

**State tree expected:**
<img width="584" alt="screen shot 2017-05-11 at 7 50 45 pm" src="https://cloud.githubusercontent.com/assets/7727204/25977765/5fcd16ba-3683-11e7-9824-cfb21beda1d1.png">

Please help me how to create the reducer to get the previous state tree.

**Comment by jotatoledo** [comment]
what have u tried until now?

**Comment by cristianqr** [comment]
@jotatoledo you mean which solution I have, if so here is the solution: [http://stackoverflow.com/questions/43927997/ngrx-reducer-to-change-multiple-states/](http://stackoverflow.com/questions/43927997/ngrx-reducer-to-change-multiple-states/)

**Comment by jotatoledo** [comment]
So u didnt tried to implement something by your own?
If u need examples of how to implement things, I strongly recommend u to take a look on the [example app ](https://github.com/ngrx/example-app)of NgRx. Your problem was most likely solved on it ;)

**Comment by jotatoledo** [comment]
close @brandonroberts

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
