### ISSUE TITLE
Allow Symbol as action name

### ISSUE THREAD

**Issue by govorov** [ngrx/store#415]
Hi!
When I'm trying to use symbol as action name I receive a this error:
`TS2678: Type 'symbol' is not comparable to type 'string'.`

due to this interface definition:
https://github.com/ngrx/store/blob/master/src/dispatcher.ts#L4

```
export interface Action {
  type: string;
  payload?: any;
}
```

I think it's reasonable to allow action names to be Symbols, not only strings.
Thank you.

**Comment by govorov** [comment]
Hey, is anyone interested in this feature?)

**Comment by robwormald** [comment]
hi @govorov - we're migrating over to https://github.com/ngrx/platform. Feel free to re-open this over there if it's still a feature you need. Thanks!
