### ISSUE TITLE
How to get HMR using ngrx store ?

### ISSUE THREAD

**Issue by junimohano** [ngrx/store#421]
I applied ngrx store and effects which are so nice for me..
I wanna use HMR with ngrx Store on Angular-cli.
Any quides?

**Comment by slivcode** [comment]
I started learning angular 2 yesterday, I looked at source code on ngrx/store and the angular-hmr-loader etc, many things are awfully confusingly(P.S. haven't tried angular2 throughly) named.

But there are a simple way to persist the state across session.
In your appModule.
```
// inject your ngrx/store.
constructor(private redux: Store<AppState>){
}
// ...
hmrOnInit(store) {
this.redux.dispatch({ type: 'replace', payload: store.state.lastReduxState });
}
// ...
hmrOnDestroy(store) {
// after removeNgStyles() or whatever
let v;
let sub = this.store.subscribe(x => {
v = x;
sub.unsubscribe();
});

// or whatever action it just need a tick to trigger the sub on top, due to the lack of getState on ngrx/store.
this.redux.dispatch({type: 'NOOP'}); 
store.state = {lastReduxState: v};
}
```

```
finally on your reducer;
reducer = (state, action) => {
if(action.type === 'replace') return action.payload;
}
```

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
