### ISSUE TITLE
Why ngRx is not included in Angular framework like  Angular Universal?

### ISSUE THREAD

**Issue by changLiuUNSW** [ngrx/store#422]
ngRx (Redux + Rxjs) is a very awesome framework for Angular, it should includes in the Angular like Angular Universal.

**Comment by fxck** [comment]
Huh?

**Comment by changLiuUNSW** [comment]
At least, it should put in the https://angular.io/features.html

**Comment by fxck** [comment]
It's not part of the framework, it's a third party library. It will be included in "Resources" in the [new site](https://pr17110-758267446a6748cbbac332bd86721c7ecfa37860.ngbuilds.io/resources).

**Comment by jotatoledo** [comment]
then go and ask this on the angular repo
