### ISSUE TITLE
How to get all previous states?

### ISSUE THREAD

**Issue by rupeshtiwari** [ngrx/store#423]
Hi all,
I am new to ngrx store. I have question how do I get all of my previous states. 
Also I am interested on implementing undo redo. Is there any way to get it out of the box. 

I know Redux Undo package has this feature do we also have in ngrx store ? https://github.com/omnidan/redux-undo

**Comment by brandonroberts** [comment]
You need to use the devtools if you want to retain all previous states. https://github.com/ngrx/store-devtools

**Comment by rupeshtiwari** [comment]
Thanks Brandon, I was aware of this tool this tool works with chrome extension. But my requirement was to provide undo redo feature in my app. Is this store dev tools can be deployed in production also. Can you point me to some sample app ?
