### ISSUE TITLE
Documentation/Tutorial?

### ISSUE THREAD

**Issue by cyberbeast** [ngrx/store#425]
Hey guys,

First of all. Great job! 👍  ngrx/store is an eye opener. I was wondering if there is a more comprehensive guide/documentation/tutorial that I could follow to learn ngrx/store. The resources listed in the readme are vague. The videos talk about migrating an existing app structure to incorporate ngrx. None of them talk about building one from scratch. I tried googling extensively before requesting for more resources to learn ngrx.

Thank you :)

**Comment by jotatoledo** [comment]
have u checked the example app? I consider it to be really good.
In the ng-conf channel (youtube) there is a 40min long video building that app from scratch [here](https://www.youtube.com/watch?v=cyaAhXHhxgk)

**Comment by cyberbeast** [comment]
Thank you for that. 
The video really helped.
