### ISSUE TITLE
Ngrx store with Reactive Forms Initialisation

### ISSUE THREAD

**Issue by elamranireda** [ngrx/store#426]
I am trying to initialize reactive forms with NgRX store. I have created a service (customerService) which simply exposes an Observable called customer$ which calls the store.select method as below

`import { Injectable } from '@angular/core';
import { Store, Action } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import { AppStore } from './app-store';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

export interface CustomerProfile {
  firstName: string;
  lastName: string;
  email: string;
  confirmEmail: string;
}

const initialState = {
  firstName: '',
  lastName: '',
  email: '',
  confirmEmail: '',
};

export const customer = (state: CustomerProfile = initialState, action: Action) => {
  switch (action.type) {
    case UPDATE_CUSTOMER:
      return action.payload;
    default:
      return state;
  }
};

@Injectable()
export class CustomerService {

  constructor(private store: Store<AppStore>) { }
  customer$: Observable<CustomerProfile> = this.store.select('customer');
  updateUser(customer) {
    this.store.dispatch({ type: UPDATE_CUSTOMER, payload: customer });
  }
}
`
in my form component i try to initialize the form like bellow 
`import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs/Rx';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { Store, Action } from '@ngrx/store';
import { AppStore, CustomerProfile, CustomerService } from './../../../_state/index';
@Component({
  ......
})
export class GeneralInfoComponent implements OnInit, OnDestroy {
  form: FormGroup;

  private subscription: Subscription;
  constructor(
    private store: Store<AppStore>,
    private customerService: CustomerService,
    private fb: FormBuilder,
    private router: Router
  ) { }
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
  ngOnInit() {
    this.customerService.customer$.subscribe(
       customer => {
        this.initForm(customer);
      });
  }

  initForm(customer: CustomerProfile) {
    this.form = this.fb.group({
      lastName: [customer.lastName, Validators.required],
      firstName: [customer.firstName, Validators.required]
    });
  }
}
`
it's work fine the problem when i run it in Production mode give me this error 
_ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'lastName' of undefined
TypeError: Cannot read property 'lastName' of undefined_

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
