### ISSUE TITLE
Is it possible to use this with redux-devtools?

### ISSUE THREAD

**Issue by jusefb** [ngrx/store#43]
Hi,

Thanks for creating an awesome library to help us newbeis get into good application state management. I have been looking at the Redux ecosystem and have noticed the great dev tools that they have. Is there a way to use ngRx/store with redux devtools extension for Chrome? If so could someone provide some guidance?

Kind regards

Jusef

**Comment by fxck** [comment]
https://github.com/ngrx/store/issues/31

**Comment by robwormald** [comment]
Not directly, but watch https://github.com/ngrx/devtools over the next few days :)

**Comment by jusefb** [comment]
Great thanks for a prompt response and thanks for a great tool
