### ISSUE TITLE
[HELP] Integrating Apollo GraphQL Client into ngrx store

### ISSUE THREAD

**Issue by changalberto** [ngrx/store#432]
How can we merge Apollo Store into `ngrx` as a single store?
This is possible with `ng2-redux`, but how can we do the same with `ngrx`?
http://dev.apollodata.com/angular2/redux.html

Some conversations [here](https://github.com/apollographql/apollo-client/issues/593#issuecomment-255436774) suggests that the ngrx community should take on some form of responsibility to make this compatible (see @alexthewilde comment). Can any of you at least suggest ideas of how we can make this happen? Any implications for backward compatibility?

**Comment by the-dr-lazy** [comment]
Hi
I think apollo-client should adopt with stores. (like a abstract interface)

Ngrx is awesome ✌️

**Comment by cport1** [comment]
There are already mutliple conversations about this over on the apollo repos. I think the most likely thing to happen is to disable the apollo cache / store.
https://github.com/apollographql/apollo-client/issues/1419

**Comment by robwormald** [comment]
We're migrating over to https://github.com/ngrx/platform, so I'm going to close this issue. Feel free to reopen it there.

**Comment by cport1** [comment]
Apollo released https://github.com/apollographql/apollo-link to resolve a lot of these concerns

**Comment by robwormald** [comment]
@cport1 cool, thanks for the link 👍
