### ISSUE TITLE
ngrx projects out of date

### ISSUE THREAD

**Issue by mtabaj** [ngrx/store#434]
I need to use the latest rxjs version, and I have the following error

ERROR in C:/_ xxx/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

I guess this errors are because the projects are not updated since +3 months ago.
There are some plans to update?
Marcos

**Comment by brandonroberts** [comment]
Yes, V4 is actively being developed and will be released soon. See https://github.com/ngrx/platform for the monorepo
