### ISSUE TITLE
Not compatible with rxjs 5.4.2

### ISSUE THREAD

**Issue by mohlendo** [ngrx/store#436]
The changes made for Typescript 2.4 in RxJS are not compatible with the current ngrx/store version:

`ERROR in [at-loader] ./node_modules/@ngrx/effects/src/actions.d.ts:4:22
    TS2415: Class 'Actions' incorrectly extends base class 'Observable<Action>'.
  Types of property 'lift' are incompatible.
    Type '(operator: Operator<any, Action>) => Observable<Action>' is not assignable to type '<R>(operator: Operator<Action, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<Action, R>' is not assignable to type 'Operator<any, Action>'.
          Type 'R' is not assignable to type 'Action'.`

**Comment by fxck** [comment]
This has nothing to do with ngrx and there are about 5 other issues about it already.

**Comment by mohlendo** [comment]
Sorry, you are right - issue can be found here: https://github.com/ngrx/effects/issues/161
