### ISSUE TITLE
Any reason ngrx cannot be used outside Angular

### ISSUE THREAD

**Issue by pvamshi** [ngrx/store#443]
As I see , only `StoreModule` part is dependent on Angular in ngrx/store  .  But I see we can do that with pure javascript. 

```ts
/**
 * @deprecated, use StoreModule.provideStore instead!
 */
export function provideStore(_reducer: any, _initialState?: any): any[] {

...
```

- Is there anything else that stops us using it with other frameworks or libraries ?
- Is it safe to assume this function will remain public so that it can be used and are there any reasons why it should not be used ?

**Comment by luchillo17** [comment]
I think maybe DI could be another reason, if i'm right Angular's DI allows us to have one single store instance (or multiple if you opt-in to it), so maybe using `ngrx` outside of Angular we will need to take care of DI ourselves.

**[Update]:** Just noticed i'm talking from the `ngrx/store` point of view, but maybe it's the same for other modules in same namespace.

**Comment by robwormald** [comment]
@ngrx is assembled with Angular's Dependency Injection setup. You could conceivably manually assemble it without, but generally you'd want to use something like Redux if you're outside of an Angular context. 

> Is it safe to assume this function will remain public so that it can be used and are there any reasons why it should not be used ?

It's removed in v4. So probably not a good idea.
