### ISSUE TITLE
please bring back payload to dispatch Action in ngrx 4, please...

### ISSUE THREAD

**Issue by born2net** [ngrx/store#448]
I have 3 huge application and without the payload I will not be able to move fwd.
the previous release had:

```
export interface Action {
    type: string;
    payload?: any;
}
```
and without the payload I am simply not sure how are we supposed to pass in data.

regards,

Sean

**Comment by brandonroberts** [comment]
See https://github.com/ngrx/platform/issues/128#issuecomment-316680916

**Comment by born2net** [comment]
thank you!!!!!!
