### ISSUE TITLE
missing functions in `BehaviorSubject` after installing 1.3.1

### ISSUE THREAD

**Issue by fxck** [ngrx/store#45]
in 1.2.1 this

``` typescript

var foo = new BehaviorSubject<Action>({ type: null, payload: null });

console.log(foo.filter);
```

returns filter function

after installing 1.3.1 it returns `undefined`

filter's not the only function missing, so is `do`, `flatMap`, basically most of these

![image](https://cloud.githubusercontent.com/assets/1303561/13378952/bca4718c-de17-11e5-93ed-98fa74ea402c.png)

**Comment by robwormald** [comment]
this isn't ngrx related, as none of these should be imported by ngrx other than the few we use internally (map, distinctUntilChanged, etc)

**Comment by MikeRyanDev** [comment]
Just to followup on this issue, it turns out the previous version of @ngrx/store (1.2) was inadvertently pulling in all of the operators. In 1.3+ @ngrx/store is only importing the operators the library depends on.
