### ISSUE TITLE
Unable to run example project

### ISSUE THREAD

**Issue by b-mi** [ngrx/store#455]
After install from git (https://github.com/ngrx/platform), npm install, npm update, ng s --open. Node version 6.11.2

But full of errors like:
- npm WARN ngrx-store-freeze@0.1.9 requires a peer of @ngrx/store@^2.2.1 but none was installed
- ERROR in H:/Data/GitHub/ngrx_platform/example-app/app/auth/auth.module.ts (7,31): Cannot find module '@ngrx/effects'
- ERROR in H:/Data/GitHub/ngrx_platform/example-app/app/app.module.ts (11,45): Cannot find module '@ngrx/router-store'.
- ERROR in H:/Data/GitHub/ngrx_platform/example-app/app/app.module.ts (12,37): Cannot find module '@ngrx/store-devtools'

But if I got package from github, run npm install and ng s --open, example application should run without errors, or not?

There is problem find any present (for Angular 4 (not Angular 2)) functional example project with ngrx/store.

**Comment by krjordan** [comment]
This issue should be moved to the [ngrx/platform repo](https://github.com/ngrx/platform/issues) as it directly relates to that repo. In order to run the example app you will need to run `npm run example:start` or `yarn example:start` if you install with yarn.

**Comment by b-mi** [comment]
Ok, npm run example:start - helper - after installing yarn. Example project wanted some authorization. But I need functional ngrx/store example project for studying ngrx/store, not any various complication. On gitub page are informations about contributors, backers, sponosrs - but not about basic informations - this looks that everything will by problematic. Sorry I'm not so sweet as other - i know, a will have to find another solutions.

**Comment by slipgoat** [comment]
Just use 'test' as username. Password is empty
