### ISSUE TITLE
No exported member OpaqueToken

### ISSUE THREAD

**Issue by ardeshirj** [ngrx/store#461]
ng: 5.0.0-beta.6
ng-cli: 1.3.1
ngrx/core: 1.2.0
ngrx/store: 2.2.3

We are in progress to update our app to Angular 5.0.0-beta.6 which introduces the following breaking change:

`core: OpaqueToken has been removed as it was deprecated since v4. Use InjectionToken instead.`

Some ngrx packages including store, effect, router-store, store-devtool is using `OpaqueToken`, so I got the following error during compile:

`ERROR in /Users/Stark/Github/lopez-ui/node_modules/@ngrx/store/src/ng2.d.ts (1,10): Module '"/Users/Stark/Github/lopez-ui/node_modules/@angular/core/index"' has no exported member 'OpaqueToken'.`

Is there any plan to support upcoming Angular 5.0 in ngrx 2.x since ngrx/platform has been introduced?

**Comment by jotatoledo** [comment]
I dont think the ngrx team has plans to develop minor versions of ngrx 2.x.x, most likely they would do bugfixes but not add new features as the current version is 4.x.x

I would suggest you to update your ngrx versions if you plant to move to angular 5.x.x

**Comment by robwormald** [comment]
There will be no more active development on these repos, and we will not be supporting 2.x with any further versions of Angular. You should update.
