### ISSUE TITLE
Angular 4 Production Build fails.

### ISSUE THREAD

**Issue by cxxuniverse** [ngrx/store#464]
I'm currently running ngrx version 4 and I'm unable to build an angular app with 'ng build --prod'.
The error that I get is: 
ERROR in 27.a70594b6b91442ef8c30.chunk.js from UglifyJs
Unexpected token operator «=», expected punc «,» [node_modules/@ngrx/store/src/utils.js:6,0][27.a70594b6b91442ef8c30.chunk.js:650,48]

**Comment by robwormald** [comment]
This repo is deprecated, and for versions < 4. Please use https://github.com/ngrx/platform
