### ISSUE TITLE
.select like in baobab?

### ISSUE THREAD

**Issue by datoml** [ngrx/store#48]
Hello.

Would it be hard to implement a .select like in [Baobab](https://github.com/Yomguithereal/baobab)?

Like you have a store with this state:

```
items: [
subitems: []
]
```

Then i would be able to create an observeable like this:

```
items: Observable<Item[]>;

constructor(private _store: Store<AppStore>)
{
// Only react to state changes on items.subitems
this.items = this._store.select('items.subitems');
      }
)
```

**Comment by fxck** [comment]
wouldn't this work?

``` typescript
this.items = this._store.select('items').map(res => res.subitems);

```

**Comment by datoml** [comment]
Yes, this would work.
But if I understand it right it will be always triggered when something inside the items array was changed.

For instance:

```
items: [
subitems: [],
isFetched: true
]
```

When I change the isFetched property to false will the subItems observeable be triggered or not?

**Comment by robwormald** [comment]
you can use the `selector` option of .select() : `store.select(state => state.items.subitems)`

**Comment by datoml** [comment]
Awesome :).
Thank you @robwormald !
