### ISSUE TITLE
cannot use `first()` with default value on `merge()` of observables created with `.select()`

### ISSUE THREAD

**Issue by fxck** [ngrx/store#49]
``` typescript

    var x1 = this._store.select('auth').map(res => res['isAuthenticated']); // returns false
    var x2 = this._store.select('auth').map(res => res['mail'] === 'ales@f13.cz'); // returns false

    x1.subscribe(res => {
      console.log('x1', res, x1);
    });

    x2.subscribe(res => {
      console.log('x2', res, x2);
    });

    Observable
      .merge(x1, x2)
      .first(res => res === true, null, false)
      .subscribe(
        next => {
          console.log(next);
        },
        err => {
          console.log(err)
        },
        () => {
          console.log('completed');
        }
      );

```

logs this 

![image](https://cloud.githubusercontent.com/assets/1303561/13398840/810ca1a0-df00-11e5-96df-bb3f2f3da399.png)

when I switch x1 and x2 to 

``` typescript
var x1 = Observable.of(false);
var x2 = Observable.of(false);
```

it correctly logs `false`, which is the third param of `first()` and completes

![image](https://cloud.githubusercontent.com/assets/1303561/13398865/9c5ddad2-df00-11e5-9f39-85d3b15e3997.png)

HOWEVER, when for example `this._store.select('auth').map(res => res['isAuthenticated']);` returns true, it correctly return `true` and completes!!

Is it because `select()` returns `Subject` instead of `Observable`? is it because `distinctUntilChanged()` 

WHAT DO I DOOO

**Comment by escardin** [comment]
What happens when you move the console logging inline?

``` typescript
   var x1 = this._store.select('auth').map(res => res['isAuthenticated']).do(res=>console.log(res)); // returns false
    var x2 = this._store.select('auth').map(res => res['mail'] === 'ales@f13.cz').do(res=>console.log(res)); // returns false

    Observable
      .merge(x1, x2)
      .first(res => res === true, null, false)
      .subscribe(
        next => {
          console.log(next);
        },
        err => {
          console.log(err)
        },
        () => {
          console.log('completed');
        }
      );
```

**Comment by fxck** [comment]
same, logs `false`, `false` from do()

**Comment by fxck** [comment]
so apparently you need to call .first() on x1 and x2 to make it work, because it never completes otherwise

![image](https://cloud.githubusercontent.com/assets/1303561/13399593/7e541138-df04-11e5-8a38-d55b7b28fac0.png)
