### ISSUE TITLE
Design Middleware implementation

### ISSUE THREAD

**Issue by robwormald** [ngrx/store#5]
- as this is Rx powered, middleware will take a different form than Redux would.
- side effects vs no side effects 
- sync vs async.
- etc

needs design

**Comment by fxck** [comment]
There's middleware and there's async... in redux, you use middleware - mainly - to get async working, you can use [this](https://github.com/gaearon/redux-thunk) or [that](https://github.com/acdlite/redux-promise) or whatever, but the question is, do you even need the ability to write _**middlewares**_ ... or you just need to support async out of the box.. it's the latter for me, at least for now.

..then again, maybe you've already got async figured out, I've seen this http://plnkr.co/edit/MYvlnPEMl5GFdFztGpcn?p=preview but I'm not sure if it's just a test or something final :)

**Comment by xgrommx** [comment]
Almost all cases can be covered via [spawn](http://xgrommx.github.io/rx-book/content/observable/observable_methods/spawn.html) or [wrap](http://xgrommx.github.io/rx-book/content/observable/observable_methods/wrap.html). Like an Observable, Promise, thunk, scalar value, complicated Observable etc. https://github.com/Reactive-Extensions/RxJS/pull/855 I made this method a very powerful. Also will be interesting `Rx.Observable.when` which is an implementation of [Join Pattern](https://en.wikipedia.org/wiki/Join-pattern) @fxck @robwormald

**Comment by laurelnaiad** [comment]
Would not [redux-saga](https://github.com/yelouafi/redux-saga)'s be a good fit for async behaviors/side-effects? Would redux-saga notice that it isn't working with a redux store? Would we be confined to the disassociated `runSaga` approach?

**Comment by robwormald** [comment]
See https://gist.github.com/tomkis1/8b3573ca9483d60c8b34 for a few ideas on an Rx version of Saga. I much prefer this style...

**Comment by robwormald** [comment]
this is initially implemented in 1.3.2 :+1:

**Comment by evanjmg** [comment]
To follow up, can I return promises or observables in my meta reducers? - I want to be able to save the state with using promises.
