### ISSUE TITLE
communicate between two different components

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#52]
What is the best practice for communicate between two different components by ngrx/store?
I could not find any articles to answer that. I would glad for an example.

Many thanks,

**Comment by MikeRyanDev** [comment]
Can you give an example of what you are trying to achieve?

Generally speaking, in an @ngrx/store application the `Store` is the single source of authority in the application. Two components should 'communicate' with each other by dispatching state-changing actions and listening for state changes. There would not be any other bridge between these components other than `Store`.

**Comment by wizardnet972** [comment]
Hi MikeRyan52, Thanks for your reply.

I have two Components on the page, Student and Teacher.
Teacher invoke an Action, and create new State by the his reducer.

Now based on the new State of Teacher, Student Component should change his state also. 

This is the story : Teacher say something, and The Student response with some answer.

So I was thinking to do it with event-handling, but the problem is one component should not recognize each other.

Teacher -> Action -> new State.
after that -> Student -> ..(event? action?) -> new State.

So that is the best data-flow between Components?
How to that by ngrx/store way? is it a possible?

**Comment by fxck** [comment]
If you are going with the smart / dumb components approach, you'd inject your service that handles dispatching actions to the reducer to parent component of both student and teacher, then you'd pass it down with `<student [chat]="service.$log" (addMessage)="service.addMessage($event)"></student>` and `<teacher [chat]="service.log$" (addMessage)="service.addMessage($event)"></teacher>`, where `log$` can be something like `store.select('chat').map(res => res.log)` depending on your state shape, then both student and teacher would have `@Input() chat;` and `@Output() addMessage = new EventEmitter(false);`.
