### ISSUE TITLE
error in the Middleware

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#53]
Hi,
I'm try to add  usePreMiddleware(actionLog) and  usePostMiddleware(stateLog) to my app.

but I got this error:
ORIGINAL EXCEPTION: TypeError: action.do is not a function.
In debugger on action event I not see the do() function attach to this action.

What I need to do to apply those functions?

`const actionLog : Middleware = action => {`
 `return action.do(val => {`
    `console.warn('DISPATCHED ACTION: ', val)`
 `});`
`};`

**Comment by fxck** [comment]
import `do`

``` typescript
import 'rxjs/add/operator/do';
```

``` typescript
import {
  Store,
  Middleware,
  usePreMiddleware,
  usePostMiddleware
} from '@ngrx/store';

import 'rxjs/add/operator/do';

const actionLog : Middleware = action => {
    return action.do(val => {
        console.warn('DISPATCHED ACTION: ', val)
    });
};

const stateLog : Middleware = state => {
    return state.do(val => {
        console.info('NEW STATE: ', val)
    });
};

export const NGRXLOGGER_PROVIDERS = [
  usePreMiddleware(actionLog),
  usePostMiddleware(stateLog)
];
```

**Comment by wizardnet972** [comment]
Cool!! Thank You!! :)

**Comment by btroncone** [comment]
Thanks for pointing this out, I think others could experience this issue as well. Once current middleware PR gets merged I'll be updating readme so I'll include a note regarding the inclusion of operators.
