### ISSUE TITLE
angular2 ^version tolerance?

### ISSUE THREAD

**Issue by kylecordes** [ngrx/store#56]
The angular2 dependency is currently specified as "angular2": "2.0.0-beta.7", but from looking through the code it appears to used generally stable angular2 APIs, ideas, etc.

Now that we are past the storm of angular2 dependency and typing changes, how about changing the dependency to "angular2": "^2.0.0-beta.7"? I would guess (though I have not tried at this moment) that ngrx already works correctly with beta.8.

Of course there is some risk with this, but at the moment that risk is perhaps less of a problem than the inconvenience of the nailed down specific-beta-version dependency?

**Comment by robwormald** [comment]
OK with me, i'll change it on the next release.

**Comment by kylecordes** [comment]
Excellent. In fact to make this easy, I just put in a pull request that does it. Right now I'm using a local build to get around the problem, basically I take the branch that I made for the PR, then use npm pack and npm install (packfile).

**Comment by datatypevoid** [comment]
Around how long are we going to be waiting until this is implemented? I could really use it soon!

**Comment by sergi-io** [comment]
+1

**Comment by kylecordes** [comment]
I suspect Rob is pretty busy with Real Work :-) and will get to it soon But if you need this right now, you can get it pretty easily:
- Clone my fork: https://github.com/kylecordes/store
- check out the versions branch
- "npm pack" which will generate a .tgz file
- in your project, npm install path-to-that-tgz-file

**Comment by sergi-io** [comment]
@kylecordes Thank you for the workaround :)

**Comment by datatypevoid** [comment]
@kylecordes I am using a workaround similar to yours in a personal repo, but I am just writing some tutorials using the store that I am hoping to be able to publish soon. But the master branch of the framework is already at Angular 2 beta 8. That's why I was wondering if there is an ETA. Thanks for your response regardless.

**Comment by robwormald** [comment]
closed in #59

**Comment by datatypevoid** [comment]
@robwormald Thank you for all of your contributions good sir!
