### ISSUE TITLE
Getting "action.do is not a function" when trying to use Middleware

### ISSUE THREAD

**Issue by jusefb** [ngrx/store#57]
Hi,

I was trying to use the middleware to record what is going through the reducers but unfortunalty I am getting "action.do is not a function" error. Here my bootstrap code:

`
const actionLog : Middleware = action => {
    return action.do(val => {
        console.warn('DISPATCHED ACTION: ', val)
    });
};

const stateLog : Middleware = state => {
    return state.do(val => {
        console.info('NEW STATE: ', val)
    });
};

bootstrap(HPZoneApp, [
    ROUTER_PROVIDERS,
    //provide(ROUTER_PRIMARY_COMPONENT, {useValue: SdDisplay})
    provide(LocationStrategy, {useClass: HashLocationStrategy}), //remove that once you sort out server side routing
    provideStore({menuZones, currentZone}),
    usePreMiddleware(actionLog),
    usePostMiddleware(stateLog)
])
`

Any idea what I am doing wrong?

Cheers

Jusef

**Comment by MikeRyanDev** [comment]
You need to import the `do` operator from rxjs:

``` ts
import 'rxjs/add/operator/do';
```

**Comment by jusefb** [comment]
Perfect thanks
