### ISSUE TITLE
plunker demo fails on latest angular beta7

### ISSUE THREAD

**Issue by yaroslavya** [ngrx/store#58]
I've tried to change the version numbers to beta7 and it gives the following error:
`{message: "No Directive annotation found on e", stack: "Error: No Directive annotation found on e↵    at n…ularjs.org/2.0.0-beta.7/angular2.min.js:10:16821)"}`
The search didnt give me any relevant results. My best guess is that I need to upgrade the ngrx/store to the latest version(1.3.2) that is beta7 compatible, is that right?
Heres the link to the changed plunker: http://plnkr.co/edit/eg44QZ90E95WX2cvIHEg?p=preview

**Comment by brandonroberts** [comment]
Use the dev bundles on betas after beta.0. Change the angular2.min.js to angular2.dev.js There are minification problems after beta.0

**Comment by yaroslavya** [comment]
Thanks a lot @brandonroberts , it worked!
Just in case anyone stumble upon the similar issue, heres the link to the updated plunker: `http://plnkr.co/edit/eg44QZ90E95WX2cvIHEg?p=preview`
