### ISSUE TITLE
Cannot get Example Thunk middleware to work

### ISSUE THREAD

**Issue by roelleor** [ngrx/store#63]
The example code for the thunk middleware results in a typescript error:
(9,5): error TS2346: Supplied parameters do not match any signature of call target.
I probably didn't get the Thunk interface right. But setting parameter and output to any also doesn't work.
I would love to get this running, thanks for any help!

```
import {createMiddleware, Action, Dispatcher} from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
interface Thunk {(action: Action): void} // <---- what should I do here?

export const thunk = createMiddleware(function(dispatcher: Dispatcher<Action>) {
  return function(all$: Observable<Action | Thunk>){
    const [thunks$, actions$] = all$.partition(t => typeof t === 'function');

    thunks$.forEach(thunk => thunk(action => dispatcher.dispatch(action)));

    return actions$;
  }
}, [Dispatcher]);
```

**Comment by robwormald** [comment]
if you're still having issues with this, please try asking in the [gitter channel](https://gitter.im/ngrx/store) - thanks!
