### ISSUE TITLE
"ghost" reducers

### ISSUE THREAD

**Issue by laurelnaiad** [ngrx/store#64]
Either I misunderstood its purpose, or I think there's an issue with the `replaceReducer` function -- specifically, that it's not undoing the connection to the prior reducer. 

I first noticed the issue I'm seeing when I logged in one of my reducers and saw it had run three times... hmmm. interesting, that's the same as the number of reducers that I'd merged in via replaceReducer.

I wrote a half-baked unit test to demonstrate my expectation that if I replace the reducer, the old one wouldn't be called.

I'm pretty sure the "offending" line, or at least the instigator, is in the connect function: https://github.com/ngrx/store/blob/master/src/store-backend.ts#L28

```
  connect(nextCallbackFn: (state: any) => void) {
    this._dispatcher
      .let(this._preMiddleware)
      .scan((state, action) => this._reducer(state, action), this._initialState)
      .let(this._postMiddleware)
      .subscribe(nextCallbackFn);
```

If this is a bug, I think I can imagine a fix, but I'll start by pushing my test up.

**Comment by MikeRyanDev** [comment]
I haven't verified the bug for you, but I can explain what's going on with the replaceReducer function.

Before the refactor, replacing the reducer required the state subscriptions to be disposed and a new one to be created. The work around is in this line:

``` ts
.scan((state, action) => this._reducer(state, action), this._initialState)
```

Instead of passing your reducer directly into scan, an anonymous reducer is instead provided which calls your reducer on the fly. I cannot see a code path in the library that would allow for ghost reducers.

With that being said, earlier in the Gitter you mentioned:

> When I tried to use the late-call-to-injector technique, I found it gave me a different instance of store. I chalked this up to being the result of having been given a diferent injector (one that was associated with my current component instead of the one that first instantiated the store

Are you by chance calling `provideStore()` in multiple locations for different components? The idea is that you should only provide the store one time, either in your bootstrap providers or in your root component. If you are providing it multiple times, that may be why you are seeing ghost reducers.

**Comment by laurelnaiad** [comment]
Thanks, Mike.

Re: late-call-to-injector: I'm not even trying to inject the store into any middleware right now. :)

Re: multiple calls to provideStore: I highly doubt that's happening, but I'll double-check. It's theoretically possible, I guess.

I see what you mean abut the scan function already having been anonymously wrapped, which was actually what I was thinking needed to be done before I realized it already seemed to be in place. 

When/if you have a chance to look at my test case, let me know what you think. I might be misunderstanding something altogether.

**Comment by MikeRyanDev** [comment]
Your test will fail because the first reducer _will_ be called a few times (I think twice?). When resolving the Store for the first time, we have to probe the reducer for the initial state if it wasn't provided: https://github.com/ngrx/store/blob/master/src/ng2.ts#L71

Otherwise the scan function has strange behavior.

**Comment by laurelnaiad** [comment]
Yeah, I was just realizing that the connect function would have called it. But why twice?

**Comment by MikeRyanDev** [comment]
Once to determine initial state, and second to dispatch an initial action.

**Comment by laurelnaiad** [comment]
This passes.... which means I need to look for another way to explain my extra calls to the reducer. :)

```
  it('should not call "ghost" reducers after replacing the reducer', function() {

    let lastValue: any;
    backend.connect(t => lastValue = t);
    expect(Reducer.reduce['calls'].count()).toEqual(1)
    const NewReducer = { reduce: () => 234 };
    backend.replaceReducer(NewReducer.reduce);
    expect(Reducer.reduce['calls'].count()).toEqual(1)
  });
```

**Comment by laurelnaiad** [comment]
It does appear that an expectation that _new_ reducers also get called once initially might fail, though:

```
  it('should not call "ghost" reducers after replacing the reducer', function() {

    let lastValue: any;
    backend.connect(t => lastValue = t);
    expect(Reducer.reduce['calls'].count()).toEqual(1)
    const NewReducer = { reduce: () => 234 };
    backend.replaceReducer(NewReducer.reduce);
    expect(Reducer.reduce['calls'].count()).toEqual(1)
    expect(NewReducer.reduce['calls'].count()).toEqual(1)
  });
```

That fails -- calls doesn't exist on NewReducer, which I'm guessing in Jasmine means that nobody called the NewReducer to set initial state.... which, if it's a problem, is a completely different problem than the one I'm having.

**Comment by MikeRyanDev** [comment]
It doesn't appear you are spying on the `NewReducer.reduce` function. Try:

``` ts
spyOn(NewReducer, 'reduce');
```

**Comment by laurelnaiad** [comment]
You're right, that line fell out.

This passes, which makes me pretty confident that I have some problem other than the one I reported (in my code, probably!).

```
  it('should support adding a reducer', function() {
    const ReducerA = { reduce: () => 234 };
    const ReducerB = { reduce: () => 234 };
    spyOn(ReducerA, 'reduce').and.callThrough();
    spyOn(ReducerB, 'reduce').and.callThrough();

    let lastValue: any;
    backend.connect(t => lastValue = t);
    expect(Reducer.reduce['calls'].count()).toEqual(1)

    const reduceA = combineReducers({
      'a': ReducerA.reduce
    })
    backend.replaceReducer(reduceA);

    expect(ReducerA.reduce['calls'].count()).toEqual(1)

    const reduceB = combineReducers({
      'a': ReducerA.reduce,
      'b': ReducerB.reduce,
    })
    backend.replaceReducer(reduceB);

    expect(ReducerA.reduce['calls'].count()).toEqual(2)
    expect(ReducerB.reduce['calls'].count()).toEqual(1)

    dispatcher.dispatch({ type: 'test', payload: {} });

    expect(ReducerA.reduce['calls'].count()).toEqual(3)
    expect(ReducerB.reduce['calls'].count()).toEqual(2)
  });
```

**Comment by laurelnaiad** [comment]
I'm starting to wonder whether I bungled your advice to do something like

```
export const storeProviders = [
  provideStore(reducer, {}),
  provide(Store, { useClass: AppStore })
]
```

in order to subclass the Store. Right now I feel like the injectors are playing mind games with me.
