### ISSUE TITLE
git-blame-someone-else

### ISSUE THREAD

**Issue by PatrickJS** [ngrx/store#66]
can has rx GifHub?
![whaaaaaaat-IUp9WRHyCwUEg](https://camo.githubusercontent.com/49cff16902f7af0c97141b0f46f1dead2f6db368/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f495570395752487943775545672f67697068792e676966)

**Comment by robwormald** [comment]
![Iqw9DK2cBqJwc](https://camo.githubusercontent.com/08093e41714f696bd49f1f4582d8c87014c8da52/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f49717739444b326342714a77632f67697068792e676966)
