### ISSUE TITLE
Unable to run @ngrx

### ISSUE THREAD

**Issue by airburst** [ngrx/store#67]
Hi,

at the risk of appearing an utter noob, I have been trying, unsuccessfully, to get @ngrx/store to run for over a week now.  If I create a clean folder, install angular2.beta.8 (or 9) as per the Quickstart guide, install @ngrx/store from npm, setup the counter example code, and modify system.js as below, I always get a console error when trying to bootstrap the provideStore provider:

Error: TypeError: store_1.provideStore is not a function(…)
    [Zone.run @ angular2-polyfills.js:1243]

System.config({
            packages: {  
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            },
            map: {
                '@ngrx/store': 'node_modules/@ngrx/store/dist/store.js'
            }
        });

npm barfs over bufferutil and utf-8-validate dependencies (Nodejs v4.4.0 and 5.8.0).

I'm really keen to get ngrx working, because I want to work with a redux approach, immutable state model and observables.  (vanilla redux works fine, but only handles POJO unless you get busy with middleware).

Many thanks for any steers.  Happy to provide any supporting debug info.

**Comment by MikeRyanDev** [comment]
Try this working SystemJS config: https://github.com/ngrx/store/issues/18#issuecomment-195893273

Let me know if it works for you!

**Comment by airburst** [comment]
Thanks Mike.  I had already tried that and it doesn't help; that returns me to the generic error about a bad token <, which usually means I haven't mapped something properly and the index.html file is being pulled instead of a script.

I've copied the node_modules/@ngrx/store/dist folder up to /dist (I assume that is what the packages section wants).

I'll continue tomorrow.

**Comment by mikekidder** [comment]
windows? npm v 2.x?

**Comment by airburst** [comment]
Yes. I've tried with NPM v3 as well (node 5.8.0)

**Comment by drew-moore** [comment]
yeah, I've been having the same problem running npm 3.8.1/node 5.8.0 on windows, i.e. `provideStore is not a function(…)`  when importing `provideStore` from `@ngrx/store`. 

However, if I `import {provideStore} from "@ngrx/ng2"` it runs (though my IDE is displeased by this)

**Comment by robwormald** [comment]
Generally, you should use map to point to the _folder_, and packages to configure the contents.

**Comment by mikekidder** [comment]
@airburst , @drew-moore  the following will work with the Angular2 Quickstart:

```
    <script> 
      System.config({
        packages: {        
          app: {
            format: 'register'
          },
          '@ngrx/store': {
             main: 'index.js',
             format: 'cjs'           
          }        
        },
        map: {
          '@ngrx/store': 'node_modules/@ngrx/store/dist'
        }  
      });     
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>
```

**Comment by airburst** [comment]
Thanks very much @mikekidder - that works.

Closed as this is clearly not a problem with the @ngrx library.  I am tripping up over Systemjs and Typescript with the latest Angular2 builds..

**Comment by mikekidder** [comment]
Oh trust me, took me a few reads about Systemjs to get that to work, and a lot of old information out there.  Systemjs needs better error handling messages.  It's not just you!!

**Comment by SaturnTeam** [comment]
I think code provided by @mikekidder  should be added to README.md file

**Comment by btroncone** [comment]
Feel free to submit a PR [here](https://github.com/btroncone/ngrx.github.io), under Help > Getting started with SystemJS. This is the WIP docs and it would certainly help to have a SystemJS example included. :+1:
