### ISSUE TITLE
cannot resolve module '@ngrx/store' in ionic build

### ISSUE THREAD

**Issue by damienadermann** [ngrx/store#68]
When adding ngrx to my ionic project I'm getting an unresolved module.

I'm doing a standard import with typescript

``` ts
import {createStore, combineReducers, Store} from '@ngrx/store';
```

this is the error in my ionic console. My editor(vsc) also doesn't recognise the module. I can see the the module in node_modules.

```
./app/app.ts
Module build failed: Error: Cannot resolve module '@ngrx/store' in /Users/damien/Develop/ionic/text-editor/app
```

package json import looks like

```
"@ngrx/store": "github:ngrx/store",
```

```
$ node -v
v4.2.1
$ npm -v
3.7.2
```

**Comment by robwormald** [comment]
does your tsconfig have `moduleResolution: node` ?

**Comment by damienadermann** [comment]
It didn't. Now it does and still no change.

**Comment by damienadermann** [comment]
To add to the confusion I tried to work around the issue until I have a solution by creating a file 

``` ts
// ./ngrx-store.ts
export * from '../node_modules/@ngrx/store/src/index.ts';
```

which appeases my editor. All type checking works but when I run `ionic serve` which builds your project with webpack I get an interesting error

```
./~/@ngrx/store/src/index.ts
Module parse failed: /Users/damien/Develop/ionic/text-editor/node_modules/@ngrx/store/src/index.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export * from './interfaces';
| export * from './store';
| export * from './utils';
```

It seems to not like something about the syntax. Maybe its just a webpack thing. These might be obvious to solve issues. I'm just new to typescript.

**Comment by brandonroberts** [comment]
@damienadermann any particular reason you're installing @ngrx/store from the github repo instead of npm? The built form of the library doesn't exist there.

**Comment by damienadermann** [comment]
@brandonroberts  Thats just what `npm install --save @ngrx/store` gave me.

Also I can't see it on npm which is odd https://www.npmjs.com/search?q=ngrx

**Comment by brandonroberts** [comment]
Here is the package page: https://www.npmjs.com/package/@ngrx/store

Try updating your package.json with this instead

```
"@ngrx/store": "^1.3.3"
```

**Comment by damienadermann** [comment]
That fixed it. Thanks for you patience @brandonroberts  @robwormald
