### ISSUE TITLE
How to inject Service into the Middleware?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/store#69]
Hi, I'm using these example,
How to inject SomeService into the Middleware? what is the right way?

---

import {bootstrap} from 'angular2/platform/browser';
import {App} from './myapp';
import {provideStore, usePreMiddleware, usePostMiddleware, Middleware} from "@ngrx/store";
import {counter} from "./counter";
import {SomeService} from "./someservice";

const actionLog : Middleware = (action, someService: SomeService) => {
    someService.log("something"); /***\* <--- HOW TO INJECT HERE? ***/
    return action.do(val => {
        console.warn('DISPATCHED ACTION: ', val)
    });
};

const stateLog : Middleware = state => {
    return state.do(val => {
        console.info('NEW STATE: ', val)
    });
};

bootstrap(App, [
  provideStore({counter},{counter : 0}),
  usePreMiddleware(actionLog),
  usePostMiddleware(stateLog)
]);

**Comment by drew-moore** [comment]
https://github.com/ngrx/store#middleware-with-dependencies

**Comment by noammazuz** [comment]
ok... so we can inject service to the middleware.
bu how can i inject the state with the createMiddleware?

```
export const thunk = createMiddleware(function(dispatcher: Dispatcher<Action>) {
  return function(all$: Observable<Action | Thunk>){
    const [thunks$, actions$] = all$.partition(t => typeof t === 'function');

    thunks$.forEach(thunk => thunk(action => dispatcher.dispatch(action));

    return actions$;
  }
}, [Dispatcher]);

```

like this approch

```
export const stateLog : Middleware = ( **state**) => {
    return state.do(val => {
        console.info('NEW STATE: ', val)
    });
};
```

**Comment by noammazuz** [comment]
i found the solution
this is how u do it.
the Storage is my service.

```
export const stateStorage = createMiddleware(function(storage: Storage) {
    return function(state){
        return state.do(val => {
            storage.set('state', val);
            console.info('LOCAL STOARGE - STATE SAVED: ', val)
        });
    }
}, [Storage]);
```

enjoy guys!
