### ISSUE TITLE
real world example

### ISSUE THREAD

**Issue by fxck** [ngrx/store#7]
TODOs and counters are cool and stuff, but once this https://github.com/ngrx/store/issues/5 is figured out, it would be worth creating some sort of real world example, similar to the one in redux - https://github.com/rackt/redux/tree/master/examples/real-world

What I find extremely common in real world is list of things with pagination, detail of a thing, editing a thing. 

How about:
- paginated list of users(id / name / email)
- detail of a user(id / name / email) with ability to change the name / email

It should probably use the [proper state structure](http://stackoverflow.com/a/33946576/301596). 

I'll happily give it a try myself once the async is working.

**Comment by fxck** [comment]
https://github.com/ngrx/angular2-store-example

**Comment by frederikprijck** [comment]
@fxck, Sorry for bumping this old issue, but is there an existing example demonstrating paging (preferably server side) with ngrx store ? I can't seem to find it in the example-app: https://github.com/ngrx/example-app

Apparantly the angular2-store-example mentioned above doesn't exist anymore.

**Comment by thiagogjt** [comment]
@frederikprijck
https://github.com/laurelnaiad/angular2-store-example
