### ISSUE TITLE
Is this the correct process?

### ISSUE THREAD

**Issue by curlyfro** [ngrx/store#70]
i have a details page where i fetch the data from http.

first off, does this process look correct?

` export class MeetingDetailsContainer  {
    meetingDetail: any;

```
constructor(private meetingService: MeetingService, private store: Store<AppStore>, private routeParams: RouteParams) {
    let meetingDetail = store.select('meetingDetail');
    meetingDetail.subscribe(data => {
        if (data)
        {
            this.meetingDetail = Object.assign({}, data.ViewModel);
            console.log('this.meetingDetail', this.meetingDetail); 
        }
    });

    const id: string = routeParams.get('meetingId');
    meetingService.getMeetingById(id);
}
```

}
`

i can see my this.meetingDetail in console.log but why do i need an elvis operator to see a parameter?  
`<header><span *ngIf="meetingDetail?.MeetingID > 0">Edit Meeting</span> <span *ngIf="meetingDetail?.MeetingID === 0">New Meeting</span></header>`

also, i guess along the same lines, i get a undefined when i pass meetingDetail as a parameter to another object.  does anyone know why?

`<meeting-details-form-header [details]="meetingDetail"></meeting-details-form-header>`

**Comment by fxck** [comment]
go thru the examples, it looks like you are doing it completely wrong.. https://github.com/fxck/angular2-store-example/tree/fxck-refactoring

amongst other things, you don't want to subscribe in your components, you want to use async pipe instead
