### ISSUE TITLE
I need help converting a ng1 app to ng2/ngrx store pattern

### ISSUE THREAD

**Issue by curlyfro** [ngrx/store#71]
i have a ng1 app details page that looks similar to this: [http://www.codecovers.eu/materialadmin/pages/contacts/add](url)

in ng1 i'm using ui router.  in my abstract route i'm resolving my http and putting my data in my routedata for all the views to share.  onSave simply saves the shared routedata.

in ng2 i have something that looks like this:
`<form role="form" class="form">
    <meeting-details-form-header></meeting-details-form-header>
    <meeting-details-tabs></meeting-details-tabs>
    <router-outlet></router-outlet>
</form>
<meeting-save-buttons></meeting-save-buttons>`

my form-header and views within my router-outlet get the deails from the store.  but how do i save?
i'm struggling architecting this with ngrx.  ideas?

**Comment by robwormald** [comment]
@curlyfro could you ask this in the [gitter channel](https://gitter.im/ngrx/store) please? We try to keep github issues for actual bugs / issues with the codebase, rather than support requests. Thanks!
