### ISSUE TITLE
provideStore is not a function

### ISSUE THREAD

**Issue by PhilippeOberti** [ngrx/store#72]
Hi guys,

I feel stupid to ask this question but I just can't figure it out.
I've been using ngrx for a while now, version 1.2.1 and everything works beautifully. I would like to update and move to 1.3.x (tested all 3 newest versions) and it's giving me the following error:

>  TypeError: store_1.provideStore is not a function

This appends in my main.ts file that looks basically like this

![screen shot 2016-03-17 at 10 59 26 am](https://cloud.githubusercontent.com/assets/17276605/13852275/57850ae8-ec2f-11e5-8702-140d3a1a5a7d.png)

In my index.html I have the ref to @ngrx/store like this

![screen shot 2016-03-17 at 10 57 02 am](https://cloud.githubusercontent.com/assets/17276605/13852204/129f4006-ec2f-11e5-8b67-c1effe1a12be.png)

I see that there is no more provideStore export in the store.js file.
I load the ngrx library from the package.json within the dependencies.

Any ideas what I'm doing wrong?
Again sorry for a newbie question and thanks a lot in advance :)

**Comment by philipooo** [comment]
Hi @filoucpp 

Have a look at this https://github.com/ngrx/store/issues/67#issuecomment-196151894
You have to change your systemjs configuration.

Cheers

**Comment by PhilippeOberti** [comment]
thanks @philipooo ! I feel even more stupid now knowing the answer was right there... :(
got it working though so thanks again!
