### ISSUE TITLE
Why aren't observables completed on dispatching?

### ISSUE THREAD

**Issue by dannylagrouw** [ngrx/store#75]
I would like to execute some code on a state change, _after_ all reducers have been called. So I thought I'd specify the third argument to the subscribe method (oncomplete). But complete() is not being called from Dispatcher.dispatch(), only next(). Is there any other way to accomplish this?

**Comment by fxck** [comment]
try adding `.delay(1)` in your saga

**Comment by dannylagrouw** [comment]
Yes that works, thanks!

**Comment by fxck** [comment]
really? I kinda posted it before reading your issue, so I deleted it afterwards :) but I guess it was the problem I though it was after all.. so yeah, the answer is to use `.delay(1)` as a temporary fix for this knows problem
