### ISSUE TITLE
ngrx unit test - No provider for Store!

### ISSUE THREAD

**Issue by BaruchFisherman** [ngrx/store#78]
Hi guys,
I'm trying to write test that runs custom component that depends on Action Creator with ngrx store injection.

I don't deeply familiar with writing unit tests.
My spec throws exception:
*\* Error: Cannot resolve all parameters for 'Store'(?, ?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Store' is decorated with Injectable.**

This is my code:

`

import {  it,  inject,  describe,  expect,  beforeEachProviders } from "angular2/testing";
import { CredentialsLogin, Customer, ICustomer } from "../../../modules/customer/index";
import { Action, Store } from "@ngrx/store";

export function main() {
  describe("Login Route", () => {

```
// let credentialsLogin: CredentialsLogin = new CredentialsLogin();
beforeEachProviders(() => [CredentialsLogin, Customer, Store]);

it("should validate stuff", inject([CredentialsLogin], (service => {
  console.log("CredentialsLogin:::: ", service);

  expect(false).toBe(true);
})));

it("should return the current state when no vaild actions has been made", () => {


 // console.log("credentialsLogin.customer ********** ",
   // credentialsLogin.customer);

  expect(true).toBe(true);
});
```

  });
}
`

Thanks.

**Comment by bzums** [comment]
Currently trying to test a service class which uses `Http` and `Store` (via DI) and I am not getting this to work...I did not find any examples either which do so. Did anybody something like that already? In https://github.com/ngrx/angular2-store-example for example there are no tests for that.

So +1 for some info on that ;)
Best

**Comment by bzums** [comment]
I just found this one: https://github.com/ngrx/devtools/blob/master/spec/store_spec.ts
That maybe helpful, will have a look at it.

**Comment by wizardnet972** [comment]
Instead of Store inject in beforeEachProviders, you should inject provideStore.
In general you should inject all the dependencies in bootstrap in beforeEachProviders section.

Good lack :)

**Comment by BaruchFisherman** [comment]
Thanks.

**Comment by sitharthan** [comment]
I can'r access your link. It's opened with "Page Not Found". Can You please anyone suggest me what i can do for this Error?. "No provider for Store! ". @bzums

**Comment by michaelwills** [comment]
@sitharthan this issue is closed but perhaps you are looking for is this:

https://github.com/ngrx/store-devtools/blob/master/spec/store.spec.ts

**Comment by martinkronstad** [comment]
Anyone else having issues with this? 

I have a Service-class where I inject ngrx/store, and it works fine when I use systemjs, but when running the exact same code in an Ionic 2 project with webpack it failes. Also when using webpack for the Angular 2 project it also failes. It failes with "No provider for Store"

**My app.module.ts:**

```
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';

import {StoreModule} from '@ngrx/store';

import {PersonReducer, PersonService} from './shared/person';
import {SharedReducer, SharedService} from './shared/shared/';
import {DataService} from './shared/shared/data.service';


@NgModule({
  imports: [
    IonicModule.forRoot(MyApp),
    StoreModule.provideStore({people: PersonReducer, common: SharedReducer})
  ],  
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [PersonService, SharedService, DataService]
})
export class AppModule {}

```

**This is the PersonService:**

```
import { Injectable} from '@angular/core';
import { Store, Action } from '@ngrx/store';
import { AppState } from '../appstate.interface';
import { Observable } from 'rxjs/Observable';
import { Person,PersonIdPayload } from './person';
import { DataService } from '../shared/data.service';

@Injectable()
export class PersonService {

    constructor(private store: Store<AppState>,private dataService: DataService){}

```

When trying to inject Store into my app.component.ts it works fine, but if I inject my PersonService into my app.component.ts it fails.

**Comment by hanschun** [comment]
@martinkronstad It looks like you are not providing the StoreModule that you have imported in your app.module.ts. You should add this to your providers array as StoreModule (no provideStore).

**Comment by martinkronstad** [comment]
@hanschun I don't think that is correct for the ngrx/store, because when I look at the code for provideStore it will define a provider-factory for the module. And if I understand how the import-section works it will actually just add any providers, imports and declarations that the imported module defines. 

Since we need to tell StoreModule what reducers we want to use, we need to use StoreModule.provideStore ...

So the code for StoreModule.provideStore is:
```
@NgModule({})
export class StoreModule {
  static provideStore(_reducer: any, _initialState?:any): ModuleWithProviders {
    return {
      ngModule: StoreModule,
      providers: provideStore(_reducer, _initialState)
    };
  }
}
```

We can see that it will return the ngModule, and some providers generated by the provideStore-function of ng2.ts
```
export function provideStore(_reducer: any, _initialState?: any): any[] {
  return [
    Dispatcher,
    { provide: Store, useFactory: _storeFactory, deps: [Dispatcher, Reducer, State] },
    { provide: Reducer, useFactory: _reducerFactory, deps: [Dispatcher, INITIAL_REDUCER] },
    { provide: State, useFactory: _stateFactory, deps: [INITIAL_STATE, Dispatcher, Reducer] },
    { provide: INITIAL_REDUCER, useFactory: _initialReducerFactory, deps: [_INITIAL_REDUCER] },
    { provide: INITIAL_STATE, useFactory: _initialStateFactory, deps: [_INITIAL_STATE, INITIAL_REDUCER] },
    { provide: _INITIAL_STATE, useValue: _initialState },
    { provide: _INITIAL_REDUCER, useValue: _reducer }
  ];
}
```

Anyway about the error, I have no idea why it started working, but as I was trying to isolate what made the error occur by making a minimum code example everything started working.

Then I tried to add all the different code back, and I was not able to get the error back.. My app.module.ts ended ut looking like:

```import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { StoreModule } from '@ngrx/store';
import { PersonReducer } from './core/person/person.reducer';
import { PersonService } from './core/person/person.service';
import { DataService } from './core/shared/data.service';


import { AppComponent } from './app.component';


@NgModule({
  imports:      [ BrowserModule, StoreModule.provideStore({people: PersonReducer}) ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ], 
  providers: [PersonService, DataService] 
})
export class AppModule { }
```

**Comment by hanschun** [comment]
@martinkronstad Glad this is not a blocking issue for you. Good luck in resolving the mystery!

**Comment by klaascuvelier** [comment]
@martinkronstad I currently have the same issue. 
Let me know if you'd have any more insights on how to solve this issue

**Comment by martinkronstad** [comment]
@klaascuvelier How many reducers do you have? Paste your app.module.ts file.

**Comment by beeman** [comment]
For future reference, I fixed this issue by updating my spec:

```typescript

// Add the import the module from the package 
import { StoreModule } from '@ngrx/store';

   // Add the imported module to the imports array in beforeEach 
   beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        StoreModule.provideStore({})
      ],
      declarations: [
        // The component that's being tested
      ]
    })
    .compileComponents();
  }));
```

**Comment by klaascuvelier** [comment]
martinkronstad :
My issues is actually not related to the unit test, so maybe I should open a new issue.
I have an `prod.ts` and `dev.ts` which are slightly different. 
`dev.ts` works, `prod.ts` doesnt

**prod.ts**
```
import {NgModule, CUSTOM_ELEMENTS_SCHEMA} from "@angular/core";
import { reducer } from "../state-management/root-reducer";
import {StoreModule} from "@ngrx/store";
import {Component} from "@angular/core";
import { AppModule } from "../app/app.module";

@Component({
    selector: "application-wrapper",
    template: `<application></application>`,
})
export class ApplicationWrapperContainer {
}

@NgModule({
    imports: [
        StoreModule.provideStore(reducer),
        AppModule
    ],
    declarations: [ApplicationWrapperContainer],
    bootstrap: [ApplicationWrapperContainer],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class ProdModule {
}
```

**dev.ts**
```
import { NgModule } from "@angular/core";
import { provideStore } from "../hot-store";
import { StoreLogMonitorModule, useLogMonitor } from "@ngrx/store-log-monitor";
import { StoreDevtoolsModule } from "@ngrx/store-devtools";
import { Component } from "@angular/core";
import { AppModule } from "../app/app.module";
import { reducer } from "../state-management/root-reducer";

@Component({
    selector: "application-wrapper",
    template: `   
        <application></application>
    `
})
export class ApplicationWrapperContainer {
}
@NgModule({
    imports: [
        provideStore(reducer),
        StoreLogMonitorModule,
        // Use chrome extension: https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en
        StoreDevtoolsModule.instrumentOnlyWithExtension(),
        AppModule
    ],

    declarations: [ApplicationWrapperContainer],
    bootstrap: [ApplicationWrapperContainer]
})
export class DevModule {
}
```

and this is my reducer:
```
import { activitiesReducer } from "./reducers/activities.reducer";
import { environmentReducer } from "./reducers/environment.reducer";

import { recommendedContentReducer } from "@showpad/recommendations";
import { popularContentReducer } from "@showpad/recommendations";
import { themesReducer } from "./reducers/themes.reducer";
import { combineReducers, ActionReducer } from "@ngrx/store";
import { ApplicationState } from "./state-types/app.state";

const reducers = {
    activities: activitiesReducer,
    recommendedContent: recommendedContentReducer,
    popularContent: popularContentReducer,
    environment: environmentReducer,
    themes: themesReducer
};

const rootReducer: ActionReducer<ApplicationState> = combineReducers(reducers);


export function reducer(state: any, action: any) {
    return rootReducer(state, action);
}```

**Comment by brechtbilliet** [comment]
I have the same issue... works if I disable AOT though...

**Comment by martinkronstad** [comment]
@klaascuvelier you should probably try make the prod.ts step by step identical to the dev.ts. This way you can track down what made the problem.

**Comment by gund** [comment]
I can confirm an error appears only when running an AOT compiled version of app.
The error doesn't give any more info in which module it fails.

**Comment by fxck** [comment]
Getting this as well, only in AOT.

@MikeRyan52 @robwormald ?
