### ISSUE TITLE
Possbile timing issue

### ISSUE THREAD

**Issue by bzums** [ngrx/store#79]
Hi,
I encountered a problem with updating the store dependent on another store observable. Not sure whether this a problem withing angular2, ngrx or my app... Given the following component: 

``` typescript
@Component({
  selector: 'shop-activity',
  template: `
    <div class="component shop-content">
        ...
        <content-workflow [transitions]="transitionService.transitions | async"></content-workflow>
    </div>
  `,
  directives: [ContentWorkflowComponent]
})
export class ShopActivityContainer {
  @Input() selectedShop: Shop;
  @Input() selectedCountry: Country;

  constructor(private contentService: ContentService, private transitionService: TransitionService) {
    this.contentService.content
      .subscribe((content: Content) => {
          this.transitionService.getTransitions(content.state);
          //setTimeout(() => {
          //  this.transitionService.getTransitions(content.state);
          //}, 0);
        }
      });

    this.transitionService.transitions.subscribe(transitions => {
      console.log('test', transitions);
    })
  }

 loadContent() {
    this.contentService.getContent(this.selectedShop, this.selectedCountry);
  }
}
```

where `loadContent` is triggered via a `click` callback. `this.transitionService.getTransitions(content.state);` just dispatches an action (synchronously) like so:

``` typescript
this.store.dispatch({
  type: LOAD_TRANSITIONS_SUCCESS,
  payload: some_local_array[state]
});
```

The initial state of `transitions` is an empty array. Now, what happens when clicking on a button to trigger `loadContent`? Some content is loaded, we subscribed to the content observable, so loading transitions is triggered. The corresponding action is fired, reducer function called, everything seems to work fine. But in the `content-workflow` component the array with the transitions never arrives. When subscribing to the transitions observable one sees, that after the new array was propagated, immediately a new value is propagated, which is the inital value, an empty array.

However, all this works fine when using `setTimeout` (see 3 out-commented lines) instead. Hopefully the problem is understandable, if you need more input/context just ask ;)

Any ideas? I am totally clueless ^^ Thanks!

**Comment by barinovos** [comment]
+1
if dispatch any action inside any subscriber of a store, the target subscription will be fired twice with the new and the legacy value once by once..
