### ISSUE TITLE
Post middleware should emit not only state value, but also latest action 

### ISSUE THREAD

**Issue by baio** [ngrx/store#83]
Post middleware should emit not only state value, but also latest action.

As workaround here I use separate store which is only contains latest action, but this is hack.
Please fix it or explain why it wont work.

Thanks.

**Comment by MikeRyanDev** [comment]
Why would post middleware emit the latest action? _Post middleware_ is applied after the action stream has been scanned into state.

If for whatever reason you need the latest action, just use Rx operators:

``` ts
import 'rxjs/add/operator/withLatestFrom';
import 'rxjs/add/operator/map';
import { createMiddleware, Dispatcher, Action } from '@ngrx/store';

const middleware = createMiddleware(function(dispatcher$: Dispatcher<Action>) {
  return state$ => state$
    .withLatestFrom(dispatcher$)
    .map(([ state, action ]) => {
      // Do something with the action
      return state;
    });
}, [ Dispatcher ]);
```

**Comment by baio** [comment]
Got it, thanks, just not considered this technique.

**Comment by baio** [comment]
Actually it change behavior somehow, and now in binding of may component I have state is undefined exception

```
[item] = (state | async).activeView

```

===>>

```
Cannot read property 'activeView' of undefined in [(state$ | async).activeView in ...
```

**Comment by drew-moore** [comment]
@baio at some point you're emitting an undefined value from `state$`. Look at where you're setting the initial value (either in the reducer or in `provideStore`), and make sure all switch cases in your reducer are returning a value (**including the default case**) .

**Comment by baio** [comment]
Thanks!
