### ISSUE TITLE
broken with rxjs 5.0.0-beta.5

### ISSUE THREAD

**Issue by wmaurer** [ngrx/store#85]
New with rxjs 5.0.0-beta.5, Subjects have been moved directly under the `/src` folder:
https://github.com/ReactiveX/rxjs/commit/30c4ef339d8ed7381e9353018891aa0362cb5d0a

@ngrx/store imports would need to be adjusted, and the rxjs peerDependency version should be upped to ^5.0.0-beta.5.

In the meantime the fix for client applications is to specify beta.4 in `package.json`, i.e. `"rxjs": "5.0.0-beta.4"`

**Comment by jon301** [comment]
👍

**Comment by kinggolf** [comment]
Just saw same thing today when updating dependencies on an Ionic2 hybrid app. I reverted back to rxjs beta.2. I find ngrx a pleasure to work with and appreciate everyone's efforts very much.

**Comment by robwormald** [comment]
thanks for this - we're working through some issues in ng core wrt some changes in beta4 and 5 and typescript 1.8+ - i'll merge this as soon as they're resolved 👍

**Comment by wmaurer** [comment]
This was fixed some time ago.

**Comment by kinggolf** [comment]
Thanks all. Working well today with ngrx/store 1.5.0 & rxjs 5.0.0-beta.6. Cheers!
