### ISSUE TITLE
'ngrx/store' is not in the npm registry.

### ISSUE THREAD

**Issue by jimseiwert** [ngrx/store#89]
when I add ngrx-store to my package.json I get the below error.
- Package.json
  "dependencies": {
    "angular2": "2.0.0-beta.13",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.9",
    "reflect-metadata": "0.1.2",
    "es6-shim": "0.35.0",
    "systemjs": "0.19.25",
    "@ngrx/store": "^1.3.3"
  }

-npm output
npm http GET https://registry.npmjs.org/ngrx/store
npm http 404 https://registry.npmjs.org/ngrx/store
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'ngrx/store' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it

**Comment by ericmartinezr** [comment]
@jimseiwert did you do `npm install @nrgx/store --save` ? Note the `@`

**Comment by jimseiwert** [comment]
yes, received the same error.

**Comment by ericmartinezr** [comment]
@jimseiwert I can't reproduce it, btw is `@ngrx` I wrote above `@nrgx`. Try cleaning npm's cache `npm cache clean` and then try to install again. It's working fine for me using `node v5.10.1` and `npm 3.8.6` with and without `@`.

**Comment by jimseiwert** [comment]
the cache clean worked in npm. I still have the same issue if I try to add it in visual studio. I am sure that is a different version of npm they are using. Back to the drawing board!

Thank you for your help.
