### ISSUE TITLE
idea: reference token keys

### ISSUE THREAD

**Issue by mikehaas763** [ngrx/store#90]
I'm completely new to ngrx/store so forgive me if this makes no sense. Just an idea I had.

I'd like to introduce a similar but alternative API to the store. What constructs the API lives on, what the naming's are, the exact contract of the APIs etc. may not make sense in my example below but the example should best show what I'm looking for.

My goal is to completely eliminate strings and magic "handshakes". By handshakes I'm referring to putting a reference to the string in the module that contains `counter` and exporting it then importing that into MyApp or wherever it may be used in order to eliminate the use of strings. I'd rather shoot for using references to the functions directly. Thoughts? Am I missing a big point?

``` typescript
import {bootstrap} from 'angular2/platform/bootstrap';
import {provideStore} from '@ngrx/store';
import {App} from './myapp';

import {counter} from './counter';

bootstrap(App, [ provideStore([counter], [{ref: counter: value: 0}]) ]);
```

``` typescript
import {Store} from '@ngrx/store';
import {counter} from './counter';

class MyApp {
    counter: Observable<number>;
    constructor(public store: Store<AppState>){
        this.counter = store.selectByRef(counter);
    }
}
```

**Comment by robwormald** [comment]
Internally, store is just an object with a shape like:

``` js
{
  foos: [Foo, Foo, Foo],
  bars: [Bar, Bar, Bar]
}
```

and thus you're naturally using property names, which are pretty much strings by default. In theory you could use a Symbol, but I've looked at it before and the complexity wasn't really worth it. Using a Map, one could in theory do state.get(SomeRef), but again, it ups the complexity.

**Comment by kylecordes** [comment]
The problem with symbols is not only extra complexity. I was curious about symbols before there even was a NgRx, over in the redux community. The issue has been discussed many times, and a fundamental obstacle is is: you really want as much as possible of this stuff (actions, but also state) to be "just data", which could be stored and reloaded later. But JavaScript symbols don't work that way, you can't write a symbol out as text/JSON and get the same symbol back. So you end up needing a translation layer to turn them all back into just plain strings (plain old ordinary data) anyway, negating most of the benefit.

(I find this slightly irritating, over in Clojure we serialize and deserialize :symbols with less trouble...)
