### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by MarkPieszak** [ngrx/store#94]
Looks we should look into updating numerous dependencies (see if it breaks any core logic).

Angular2 is @ beta 16.
RxJs @ beta 6.
es6shim, lodash, typings, and zone all have many updates as well.

https://david-dm.org/ngrx/store#info=devDependencies&view=table

https://david-dm.org/ngrx/store#info=peerDependencies&view=table

**Comment by kylecordes** [comment]
Yes, please.

**Comment by MikeRyanDev** [comment]
Angular2 is at beta 16, but it still requires RxJS beta 2. The next Angular 2 beta shouldn't resolve this.

**Comment by MarkPieszak** [comment]
Ah yes you're right.
I was just wondering if it'd be a good idea to keep up and make sure everything still works. I had tried but was receiving a lot of random errors from devtools :(

**Comment by ncrawlins** [comment]
angular2 just bumped to 17 and rxjs-beta6.  It seems to break @ngrx/store because "BehaviorSubject" was moved in rxjs at some point.

**Comment by kylecordes** [comment]
No doubt we'll all have 100 chances to talk about NgRx at ng-conf next week... hopefully it won't start with "well, I am behind N betas because of NgRx, how about you?"

No pressure @robwormald  :-)

**Comment by laurelnaiad** [comment]
The only beta you can't use with it is 17, which came out this morning. I wouldn't worry too much. The template variable changes in beta 17 will probably  be more painful.

**Comment by MikeRyanDev** [comment]
Since ngrx/store is semantically released, bumping to the latest rxjs beta would result in a breaking change on our end. It may be better to introduce the dependency update in the 2.0 refactor.

**Comment by kylecordes** [comment]
To me it seems that keeping up with the rapidly evolving Angular 2 is much more important than following semver, but it seems like something for post-release rather than during development? Deciding not to keep up with the betas for the sake of not burning up a "2" semver version, seems like the cart before the horse.

**Comment by laurelnaiad** [comment]
I think that as long as ngrx/store is compatible with itself, you're allowed to change the deps to ng-beta17 and rxjs-beta6 in a hotfix if you want. At the very least a minor version.... no? Why would semantic versioning prevent changing the dependencies?

**Comment by laurelnaiad** [comment]
it would just be saying that to use ngrx/store@vnext, you need to be using at least ng-beta17 and and rxjs-beta6.... not a semver foul.

**Comment by MikeRyanDev** [comment]
@kylecordes @laurelnaiad Normally I would agree and say that updating to the latest beta isn't necessarily a breaking change, however the the most recent betas and Angular 2 and rxjs have some serious breaking changes of their own. If we broke semver on our end that doesn't sound like we'll be helping developers much at all. 

Also, for as long as `OnPush` change detection is broken I don't personally see a compelling reason to upgrade an ngrx/store-based app to the latest betas.

**Comment by MarkPieszak** [comment]
I'll close this out out for now, maybe we should wait until ng2 is out of beta to start tracking and patching every update. 

Who all is going to ngconf next week? Hope there's some ngrx talks :)

**Comment by NathanWalker** [comment]
@MikeRyan52 there are other reasons users need these updates in ngrx/store... they may need fixes in other libs their projects are using that are now using beta.17 with rxjs beta.6... but use this lib as well and cannot get the fixes from other libs because this lib is holding everything back.

Can this PR at least be merged, then a new version published to clear people from this frustration?:
https://github.com/ngrx/store/pull/86

**Comment by robwormald** [comment]
I'll merge it this afternoon. Sorry, been incredibly busy prepping for
ngConf!

**Comment by kylecordes** [comment]
If the commits are any indication, the Angular 2 development team is working like crazy, trying to fit in many weeks of development to the last week before the conference. I'm hoping it pays off, and during the conference we are all sitting there revamping our tooling on all of our projects, including NgRx projects, to use the new build time template compilation.

**Comment by robwormald** [comment]
1.4.0 released

**Comment by NathanWalker** [comment]
Thanks @robwormald !!!

**Comment by MarkPieszak** [comment]
Nice @robwormald ! Excited to meet everyone in a few days @ ngConf this week
