### ISSUE TITLE
create postMiddleware with dependency

### ISSUE THREAD

**Issue by divramod** [ngrx/store#95]
Hey, 

i am fairly new to redux and rxjs.
i like to create a middleware with which i can call a function i defined in an own service.
I called that Service StateService and i like to call a function test() from that service after each action dispatch.

that is how far i am:

```
export const thunk = createMiddleware(function(stateS: StateService) {
  return function(stateS){

    stateS.test();
    return Observable.of(true);
  }
}, [StateService]);
```

could someone give any hints, what i have to learn/do next?

**Comment by robwormald** [comment]
Middleware has been deprecated. Please see https://github.com/ngrx/effects/ for the new model.
