### ISSUE TITLE
store.js Can't find BehaviourSubject (moved in the lasts releases of rxjs)

### ISSUE THREAD

**Issue by sebasgavi** [ngrx/store#96]
seems like they moved `BehaviorSubject` from rxjs/subject to rxjs/ in 5.0.0-beta.5

I'm getting the error on store.js line 8
`var BehaviorSubject_1 = require('rxjs/subject/BehaviorSubject');`

works normally using rxjs 5.0.0-beta.3

using jspm with rxjs 5.0.0-beta.7
Windows 10 - Chrome
Node v4.3.1 - npm 2.14.12

**Comment by jon301** [comment]
I'm getting the same error after upgrading to rxjs 5.0.0-beta.7

**Comment by littleStudent** [comment]
currently you can not use angular beta 16. 
discussed in #94

**Comment by sebasgavi** [comment]
@littleStudent thanks, didn't see that. 
I'm using angular2 beta 15 but the problem for me is with ngrx/store.
They already talked about that in #94 so I'm closing this.
