### ISSUE TITLE
AngularJS version

### ISSUE THREAD

**Issue by dsebastien** [ngrx/store#98]
Hi,

I'm creating this issue to check if there's some interest for the creation of a version of ngRx compatible with AngularJS (either in this repo or in a separate one).

At work we're currently working on an internal framework based on AngularJS (due to time pressure and the choice of Material Design), which we plan to later migrate to Angular 2. In order to simplify the migration, it would be great if we could use ngRx directly or at least a version compatible with AngularJS.

Is anyone interested?
How would you see this? In the same repo or in another one (i.e., thus meaning a sort of split between the pure redux functionality and the Angular version-specific code? (e.g., ngrx, ngrx-ng2, ngrwx-ng1)..

**Comment by kylecordes** [comment]
I can't speak for the NgRx team, but I can offer an educated guess. NgRx is a reimplementation of the Redux ideas, connected to Angular 2 and based on RxJS. AngularJS 1.x doesn't use RxJS (although of course there is nothing to stop you from doing so), and might be suited to a different implementation approach. I suggest looking at the following project, it might be what you're looking for.

https://github.com/angular-redux/ng-redux

**Comment by iamdey** [comment]
Hi, 
Obviously creating a bridge angularJs + RxJs + redux sounds difficult and time consuming, I'm agree ng-redux is way better. But this issue remember me a good question I got for my use case: 

I'm using angularJs + ng-redux in CaliOpen/web-client-ng and planning to migrate to Angular2.
Currently I have a little idea of the cost of angular2 migration but absolutely no idea for ng-redux to ngrx/store (+ reduxUiRouter). I didn't go further because the api looks the same as redux. 

Someone who knows both ng-redux and ngrx/store may be able to answer that?

**Comment by dsebastien** [comment]
@kylecordes well the value I see in having ngRx for ng1 is being able to use the exact same API, based on RxJS (as you said, nothing prevents us from using Rx with ng1), meaning that a later upgrade to ng2 would be easier for that part. There's also the fact that ngRx uses TypeScript, and again it makes sense to use TypeScript with ng1 too.

**Comment by kylecordes** [comment]
I agree, there is certainly room to use RxJS with AngularJS 1. Have even occasionally recommended companies move in this direction, as part of a gradual transition strategy.

**Comment by Hotell** [comment]
Hey @dsebastien indeed I'm interested to back port this to angular 1, because the same reasons you've mentioned. We are using at work [ng-metadata](https://github.com/ngParty/ng-metadata) (which backports almost every angular 2 API to ng1 ), so we can flawlessly migrate to ng2 when the right time( managers approval ) comes :) Speaking of ng-metadata, when I implement this issue https://github.com/ngParty/ng-metadata/issues/85, then back porting of ngRx would be no brainer. Lemme know what do you think

**Comment by dsebastien** [comment]
@Hotell sounds great! :)
We'll be looking at ng-metadata at work; I stumbled upon the project a while ago and it looked promising

**Comment by fxck** [comment]
I don't want to speak for others, but I think that ng2 should be the priority, and porting to ng1 should be up to the community. This applies to the whole ngrx ecosystem.

**Comment by Hotell** [comment]
@fxck yes this is what I wrote/meant in my comment

**Comment by JamesHenry** [comment]
Hey @Hotell,

I did actually successfully port ngrx back to Angular 1 a couple of months ago. I mainly did it for the fun of it, and to dig into ng2 DI.

I haven't really touched it since then, so it will need to be updated to reflect the latest changes in ngrx, but it could be a good starting point for us for ng-metadata.

**Comment by Hotell** [comment]
Perfecto @JamesHenry ! 🚀

**Comment by JamesHenry** [comment]
My implementation had an accompanying directive to naively mimic the async pipe from ng2 and call $scope.$apply when the Observable produced a new value, but if the Zone.js stuff could be done as you mentioned above, then we could make it much cleaner

P.S. @dsebastien ng-metadata is awesome, you should definitely dig into it for any ng1 + TS projects

**Comment by robwormald** [comment]
The codebase is (kind-of) set up for this already, as most ng2-specific functionality is centralized into the ng2.ts file.

I honestly don't want the maintenance and issue overhead in this repo, but there's no reason that an ng1-compatible version of store couldn't depend on @ngrx/store code and simply re-export the appropriate hooks for ng1. 

I'm going to close this as non-actionable on this end, but feel free to carry on discussion and hollar if you need any help.

**Comment by Hotell** [comment]
![ngrx](https://cloud.githubusercontent.com/assets/1223799/15829184/dc105182-2c12-11e6-8d50-e6bb86dbec1a.gif)

**Comment by Hotell** [comment]
here is live version with loggerMiddleware thanks to @JamesHenry https://gist.run/?id=d93766a07c516361fa75a376273590d4 will publish the polyfill soon...

**Comment by JamesHenry** [comment]
Huge thanks to @robwormald and @MikeRyan52 for removing the ng2 dependency from this project!

**Comment by dsebastien** [comment]
Nice. 

We've spent a few hours on this at work and we've realized that we only needed to configure an angularJS provider to create the store instance using ngrx. It works with ngrx as is (although we do pull ng2 deps that we don't need.

**Comment by dougiefresh49** [comment]
Hey @dsebastien 

thats exciting to hear! I was hoping to something along those lines. 

> configure an angularJS provider to create the store instance using ngrx

Mind sharing what how you pulled it off? Would love to see how you did that!!

**Comment by dsebastien** [comment]
Yes, we will publish that on GitHub & npm.

**Comment by dougiefresh49** [comment]
Awesome @dsebastien !

**Comment by dougiefresh49** [comment]
hey @dsebastien , any progress on this? Glad to help out if it is still in the works.

**Comment by jbadeau** [comment]
Any update on this?

**Comment by Hotell** [comment]
@jbadeau I think this is not possible anymore because angular 2 is a peer dependency again 
https://github.com/ngrx/store/blob/master/package.json#L38

am I right @JamesHenry  ?

**Comment by jbadeau** [comment]
What a shame :(

**Comment by jbadeau** [comment]
Seems the angular 2 peer dependency is only needed for exporting exporting a module, preventing namespace collisions and wrapping the provider module. This can easily be done in angular 1. I'll give it a go this evening

**Comment by jbadeau** [comment]
Just reporting back that:

```
    "angular": "1.6.1",
    "ng-metadata": "4.0.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/db": "^2.0.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1"
```

all work well together.
The only thing really missing is:

```
@NgModule({})
export class StoreModule {
  static provideStore(_reducer: any, _initialState?:any): ModuleWithProviders {
    return {
      ngModule: StoreModule,
      providers: provideStore(_reducer, _initialState)
    };
  }
}
```
whereby ModuleWithProviders is not provided by ng-metadata. The deprecated

`provideStore`

still works

**Comment by jamesbrobb** [comment]
@jbadeau Hi, does this still work? Do you have any examples showing it in action?

**Comment by jbadeau** [comment]
Hi,

Unfortunately ngrx no longer works beacuse of the ModuleProvider feature. However, you can bootstrap an angularjs app in hybrid mode and then downgrade the store service.

Jose

**Comment by niamleeson** [comment]
Hi,

Just came to report that bootstrapping Angular 1 with Angular 4 and downgrading ngrx store to be injectable to Angular 1 works. It looks like you won't need ng-metadata.

I saved an example here https://github.com/niamleeson/angular1-angular2-ngrx-downgrade

It was originally forked from angular-typescript-webpack repo, so I'm not claiming that the Angular 1 code is mine at all, but I just wanted to share that it works.

Thanks.

**Comment by d-nation** [comment]
This works for me in dev mode, but not when using AOT 😢 

`Error: No provider for e!`
